### ISSUE TITLE
Get the zoom level of org chart

### ISSUE THREAD

**Issue by TobiasKrok** [bumbeishvili/org-chart#101]
Hey!

Is it possible to get the zoom level of the org chart? I want a specific behavior if the zoom level is lower than x amount.

**Comment by bumbeishvili** [comment]
You can invoke the following method
```javascript
chart.lastTransform()
``` 

it will return object in this structure:
```javascript
{ 
  x: 0, 
  y: 0, 
  k: 1 
}
```

Where `k` is a zoom level.

K ranges between these values (`1` equals normal zoom level, `<1` is zoom out, `>1` zoom in)
```javascript
[0.001, 20]
```

**Comment by TobiasKrok** [comment]
> You can invoke the following method
> 
> ```js
> chart.lastTransform()
> ```
> 
> it will return object in this structure:
> 
> ```js
> { 
>   x: 0, 
>   y: 0, 
>   k: 1 
> }
> ```
> 
> Where `k` is a zoom level.
> 
> `k` ranges between these values (`1` equals normal zoom level, `<1` is zoom out, `>1` zoom in)
> 
> ```js
> [0.001, 20]
> ```

Thank you! Are you able to set the zoom level as well through this?

**Comment by bumbeishvili** [comment]
No, you can't directly do it

You can only set `chart.initialZoom(0.4)` initially.

In the runtime, there is a way to still manipulate zoom level 

if you look into `zoomIn` and `zoomOut` implementation, you will be able to see that you can set relative zooming using this code

```javascript
  const { svg, zoomBehavior } = chart.getChartState();
  svg.transition().call(zoomBehavior.scaleBy, 0.78);  // Current zooming parameter multiplied to passed number
```

If you combine this code with above method, I'd say you can achieve desired result
