### ISSUE TITLE
How to set width of svg?

### ISSUE THREAD

**Issue by sebarti** [bumbeishvili/org-chart#102]
Hi. How can i set the width of the chart (underlying svg element)? It defaults to 800 but i'd like to make it 100% for example. I tried to set the attribute on the chart instance directly which has no effect.

**Comment by bumbeishvili** [comment]
It fits the container, so just set container width and it will fit

![Screenshot 2021-11-16 at 12 08 26](https://user-images.githubusercontent.com/6873202/141999528-a63e5d5c-4c8b-4708-a63a-5d3a5cc69ad3.png)

**Comment by bumbeishvili** [comment]
Can you provide an online example?

You can extend https://stackblitz.com/edit/d3-org-chart-react-integration-hooks
