### ISSUE TITLE
Chart instance methods and attributes documentation

### ISSUE THREAD

**Issue by sebarti** [bumbeishvili/org-chart#103]
Thanks for this libaray. I think it has some good potential.

Is there any intention to improve it's documentation, especially documentation of public methods and attributes of the chart instance?

**Comment by bumbeishvili** [comment]
It's planned - won't be done until I get a major freelancing project involving org chart development

**Comment by bumbeishvili** [comment]
@sebarti  probably not what would you expect, but in the new v3 versio I've divided the code inside the org chart and added comments on what each property does.

https://github.com/bumbeishvili/org-chart/blob/f85dcd4bea42fa0d0ebb1cf5ff4b86ea5879d7ba/src/d3-org-chart.js#L40-L449
