### ISSUE TITLE
Order subordinates alphabetically

### ISSUE THREAD

**Issue by TobiasKrok** [bumbeishvili/org-chart#104]
Hi!

Is it possible to have the org chart order subordinates alphabetically? Does the array it gets data from need to be ordered?

**Comment by bumbeishvili** [comment]
To be honest, I don't know if it retains order (I think it will), array most certainly will need to be ordered

**Comment by TobiasKrok** [comment]
> To be honest, I don't know if it retains order (I think it will), the array most certainly will need to be ordered

Sorted the array and it layed it out in the correct order :)
