### ISSUE TITLE
Spurious curly brace?

### ISSUE THREAD

**Issue by TildeWill** [bumbeishvili/org-chart#106]
I believe the first closing curly on [this line](https://github.com/bumbeishvili/org-chart/blob/4f84ee6256f127b0503bbaf3093ed9ce48bc31e4/src/d3-org-chart.js#L61) is not needed. If someone can confirm this is the case, I'm happy to make a PR if needed.

**Comment by bumbeishvili** [comment]
I think you are right, feel free to create PR

**Comment by bumbeishvili** [comment]
#107
