### ISSUE TITLE
How to get the nodeID when we click on the expand collapse button

### ISSUE THREAD

**Issue by pradshan** [bumbeishvili/org-chart#108]
Firstly I wanted to convey to you that this is an awesome library and really appreciate your work.

I have a question:

Q). I would like to get the id of the node when the expand or collapse button is clicked. I do see onButtonClick method but I am not exactly sure how to use it. Is there an example code as to

**Comment by bumbeishvili** [comment]
Unfortunately event for this particular action is not exposed so you won't be able to get it directly.

For the workaround, you can attach your own event handler to each node and listen to it
```javascript
chart.nodeUpdate(function(e,d){
   d3.select(this).on('click.node-update',(event,data)=>console.log('clicked',data.id))
})
```


In order to not compromise performance, don't forget to add named event listener `click.node-update`, that way after the node gets removed, event handlers also get taken care of.

**Comment by pradshan** [comment]
Thanks a ton for the prompt response. I am able to get the node id. However this is what I am trying to do and I am facing an issue.  Not sure if there is a better way to handle this.

-  I want to highlight upto the root when I click on the expand and collapse button. 
- Currently I added this code and it works as expected when I click on the node. 
- If I click on the button it doesn't highlight.

Snip of the code that I already had:

```js
chart.linkUpdate(function (d) {
  d3.select(this)
  .attr('stroke', (d) =>
    d.data._upToTheRootHighlighted ? '#14760D' : '#ffffff'
  )
  .attr('stroke-width', (d) =>
    d.data._upToTheRootHighlighted ? 10 : 1
  );

  if (d.data._upToTheRootHighlighted) {
    d3.select(this).raise();
  }
})
.nodeUpdate(function (d) {
  d3.select(this)
  .select('.node-rect')
  .attr('stroke', (d) =>
    d.data._highlighted || d.data._upToTheRootHighlighted
      ? '#14760D'
      : 'none'
  )
  .attr(
    'stroke-width',
    d.data._highlighted || d.data._upToTheRootHighlighted ? 15 : 1
  );
})
.onNodeClick(d => {
  chart.clearHighlighting();
  chart.setUpToTheRootHighlighted(d).render();
})
```

**Changes in the code:**

- After you clarified as to how to get the node id I tried removing the NodeClick
-  Moved the clearHighlighting method and setUpToTheRootHighlighted method inside nodeUpdate. 
-  But none of the nodes are getting highlighted. Just the links. I am not sure how to get this done:

```js
chart.nodeUpdate(function(e,d){
   d3.select(this).on('click.node-update',(event,data)=>{
          if ([...event.srcElement.classList].includes("node-button-foreign-object")) {
               chart.clearHighlighting();
               chart.setUpToTheRootHighlighted(data.id).render();
          }
    })
})
.linkUpdate(function (d) {
  d3.select(this)
  .attr('stroke', (d) =>
    d.data._upToTheRootHighlighted ? '#14760D' : '#ffffff'
  )
  .attr('stroke-width', (d) =>
    d.data._upToTheRootHighlighted ? 10 : 1
  );

  if (d.data._upToTheRootHighlighted) {
    d3.select(this).raise();
  }
})
```

I am wondering how do I add this below snip of code into the newly updated nodeUpdate method so that It highlights each node on its way to the root.

```js
 d3.select(this)
  .select('.node-rect')
  .attr('stroke', (d) =>
    d.data._highlighted || d.data._upToTheRootHighlighted
      ? '#14760D'
      : 'none'
  )
  .attr(
    'stroke-width',
    d.data._highlighted || d.data._upToTheRootHighlighted ? 15 : 1
  );
```

**Comment by bumbeishvili** [comment]
Probably like this

```javascript
chart.nodeUpdate(function(e,d){

    d3.select(this)
      .select('.node-rect')
      .attr('stroke', (d) =>
        d.data._highlighted || d.data._upToTheRootHighlighted
          ? '#14760D'
          : 'none'
      )
      .attr(
        'stroke-width',
        d.data._highlighted || d.data._upToTheRootHighlighted ? 15 : 1
      );


   d3.select(this).on('click.node-update',(event,data)=>{
          if ([...event.srcElement.classList].includes("node-button-foreign-object")) {
               chart.clearHighlighting();
               chart.setUpToTheRootHighlighted(data.id).render();
          }
    })
})
```

**Comment by pradshan** [comment]
Fantastic!!! it works like a charm. I need to dig deep to understand what is happening behind the scenes to understand the magic :)
