### ISSUE TITLE
Expand plus and minus sign not pixel perfekt

### ISSUE THREAD

**Issue by AndorLundgren** [bumbeishvili/org-chart#11]
Because of the different font-size of the chars +- (26 resp 40) with possible combination of char placement in font, it looks like they are little off center.

Not 100% certain if it is a easy fix or just a fix for given font-family, but you could off the - sign little to make the feel more aligned.
Have tried with replacing:
`.attr('y', this.isEdge() ? 10: 0)` 
with
`.attr('y', ({ children }) => this.isEdge() ? 10 : children ? -3 : 0)`
and it feels a little better.

**Comment by bumbeishvili** [comment]
Will take a look at this once will find time to keep working on new features

**Comment by bumbeishvili** [comment]
In the new version, we will have new icons for expand collapse, and that button will be user-configurable/overridable as well

<img width="802" alt="Screenshot 2021-07-18 at 00 36 51" src="https://user-images.githubusercontent.com/6873202/126048822-52b41dfc-1fbd-4897-a3ae-e248b2c9045d.png">

1. https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L626

2. https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L65

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
