### ISSUE TITLE
onClick handler for the toggle (expand/collapse) button

### ISSUE THREAD

**Issue by martindavid** [bumbeishvili/org-chart#110]
First of all, thanks for building this library. So far this library has most of the functionality that we need to build our visualisation.

There's one thing that's missing that's crucial to our needs, which is the capability to add the tree node on the fly using the expand/collapse button. 

The use case that we're looking for:
- At the first render, we'll only render the first level of the org-chart
- When the user clicks on the toggle button, the component will make an API request to fetch the data for the node and generate the new tree node.

My question, is there a way to inject the `onClick` event handler to that toggle button? My understanding, looking at the code, currently it's being added as an internal state, nothing is exposed to the consumer.

**Comment by bumbeishvili** [comment]
@martindavid take a look at this issue

https://github.com/bumbeishvili/org-chart/issues/108

It's another use case, but basically, it answers your question.

Also, let me know if it will work in the end and if you will be able to lazy load nodes that way

**Comment by martindavid** [comment]
Thanks, @bumbeishvili for your quick response. I'll try the suggested solution there and will come back to you soon.

**Comment by martindavid** [comment]
@bumbeishvili yes, the solution to that issue works for my case. Just want to confirm with you, by utilising the `node_update` event, I can only use `data.children` to infer the expanded state of the node, right?

**Comment by bumbeishvili** [comment]
Yes, it will have either 
```
data.children  => expanded
data._children  => collapsed
or both of above property will be null , which means node does not have a children at all
``

**Comment by martindavid** [comment]
Thanks, I think we can close this issue now.
