### ISSUE TITLE
M.linkHorizontal is not a function

### ISSUE THREAD

**Issue by david-baghdasaryan97** [bumbeishvili/org-chart#111]
URL's 
https://d3js.org/d3.v7.min.js
https://cdn.jsdelivr.net/npm/d3-org-chart@2
https://cdn.jsdelivr.net/npm/d3-flextree@2.1.2/build/d3-flextree.js
            
![image](https://user-images.githubusercontent.com/94369743/147566998-6194863b-4263-4619-9bad-1a9a7b6d8b48.png)

Error src  - d3-org-chart@2

![image](https://user-images.githubusercontent.com/94369743/147569892-e12ae08a-154b-4c62-b146-c68ef86a6e0f.png)

**Comment by bumbeishvili** [comment]
That's strange. The only thought I have is that d3 was not loaded when that code run. 

Can you provide an online example so I can check it?

For me, it seems to work for the linked versions.

You can copy this part and paste it into https://realtimehtml.com and you will see that it works
```
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-org-chart@2"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-flextree@2.1.2/build/d3-flextree.js"></script>
    <div
      class="chart-container"
    ></div>

    <script>
      var chart;
      d3.csv(
        'https://raw.githubusercontent.com/bumbeishvili/sample-data/main/org.csv'
      ).then(data => {
        chart = new d3.OrgChart()
          .container('.chart-container')
          .data(data) 
          .render();
      });
    </script>
```

**Comment by david-baghdasaryan97** [comment]
let chart = new d3.OrgChart()
This code work , accordingly d3 loaded when run code, but after  return error , and chart not show 


code e.g 


         let chart = new d3.OrgChart()
                .container('.chart-container')
                .data(data)
                .nodeWidth(d => 250)
                .initialZoom(0.7)
                .nodeHeight(d => 175)
                .childrenMargin(d => 40)
                .compactMarginBetween(d => 15)
                .compactMarginPair(d => 80)
                .nodeContent(function (d, i, arr, state) {
                 ...my html template 
                }
                  chart.render();

**Comment by david-baghdasaryan97** [comment]
Sometimes return error 

[DEMO](https://drive.google.com/file/d/17vk7Ns2Dwt-7VMasHpME_5E5zIaH5Y9n/view?usp=sharing)

**Comment by bumbeishvili** [comment]
@david-baghdasaryan97  can you provide online fiddle where this issue is reproduced? 

You can extend this example - https://stackblitz.com/edit/web-platform-sgsxzp

**Comment by david-baghdasaryan97** [comment]
@bumbeishvili  unfortunately I can't , but problem not in loaded d3 
after loaded d3 return error. 

My code similar to your example , please check video demo in previous commit
