### ISSUE TITLE
Getting data in real time

### ISSUE THREAD

**Issue by JaggerLS** [bumbeishvili/org-chart#117]
Hello friends, it's possible to get the data in realtime?

I´m trying to do this using ajax, but i can´t get with the solution. I need somehow change the data.json(), to not get the data from an external file otherwise from a variable that i get from the ajax response. No matter if i have to do it on another way, i just need the real time data. Because many people manipulate the data, making it changes a lot. It´s annoying to refres the page every time. This is the way i´m trying to accomplish this: 

The response in method.php is in json_encode();
 $.ajax({
            url: 'method.php',
            type: "POST",
            data: {
                id: 'O-6066'
            },
            success: function(data) {
              d3.json(**i need the data work in this place, not with an url**).then((dataFlattened) => {
                dataFlattened.forEach((d) => {
                const val = Math.round(d.name.length / 2);
                d.progress = [...new Array(val)].map((d) => Math.random() * 25 + 5);
            });
            }
        });

Thanks for the help.

**Comment by bumbeishvili** [comment]
The question is not clear

**Comment by JaggerLS** [comment]
Let me explain, i´m getting the data from a database, and this database is updated a lot of times. That´s why i´m using ajax, to make a request to the server. What i need is to get the data in real time, without refreshing the page to get the new data.

**Comment by bumbeishvili** [comment]
Ajax is definitely a way to go, but what I don't understand is question relevance to the org chart library. For me looks like your question belongs to stackoverflow

**Comment by bumbeishvili** [comment]
d3.json is just the ajax wrapper, you can invoke the chart just with your own data. d3.json just downloads the data

**Comment by JaggerLS** [comment]
Oh okay, i need to know if there is a way with the org chart library to get the json locale (in a variable), no in a external file. d3.json() uses an url.

**Comment by bumbeishvili** [comment]
Org chart just takes your data and draws it. How you load the data is up to you. 

If you will use ajax just invoke the graph with your data and that's it


If you can provide online stackblitz sample with the problem showcased that would be helpful

**Comment by JaggerLS** [comment]
The json is locale in a variable, i need to read the variable to work with this. 

var json = [
    {
        "name": "Jagger",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/cto.jpg",
        "area": "Corporate",
        "profileUrl": "http://example.com/employee/profile",
        "office": "CTO office",
        "tags": "Ceo,tag1,manager,cto",
        "isLoggedUser": "false",
        "positionName": "Chief Executive Officer",
        "id": "O-6066",
        "parentId": "",
        "size": ""
    },
    {
        "name": "Jagger",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/cto.jpg",
        "area": "Corporate",
        "profileUrl": "http://example.com/employee/profile",
        "office": "CTO office",
        "tags": "Ceo,tag1,manager,cto",
        "isLoggedUser": "false",
        "positionName": "Chief Executive Officer",
        "id": "O-6067",
        "parentId": "O-6066",
        "size": ""
    },
    {
        "name": "Jagger",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/cto.jpg",
        "area": "Corporate",
        "profileUrl": "http://example.com/employee/profile",
        "office": "CTO office",
        "tags": "Ceo,tag1,manager,cto",
        "isLoggedUser": "false",
        "positionName": "Chief Executive Officer",
        "id": "O-6068",
        "parentId": "O-6066",
        "size": ""
    },
    {
        "name": "Jagger",
        "imageUrl": "https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/cto.jpg",
        "area": "Corporate",
        "profileUrl": "http://example.com/employee/profile",
        "office": "CTO office",
        "tags": "Ceo,tag1,manager,cto",
        "isLoggedUser": "false",
        "positionName": "Chief Executive Officer",
        "id": "O-6069",
        "parentId": "O-6066",
        "size": ""
    }
];
        d3.json(json).then((dataFlattened) => {
            dataFlattened.forEach((d) => {
                const val = Math.round(d.name.length / 2);
                d.progress = [...new Array(val)].map((d) => Math.random() * 25 + 5);
            });

**Comment by bumbeishvili** [comment]
In that case just remove d3.json part and write

`
chart.data(data).render()
`

Please extend this [example]

](https://stackblitz.com/edit/web-platform-3gwnsg)

And provide online url so I can make slight adjustments

**Comment by JaggerLS** [comment]
https://stackblitz.com/edit/web-platform-nwdzmn?file=index.html

**Comment by bumbeishvili** [comment]
Here, just removed d3.json part and passed your data instead of dataFlattened

https://stackblitz.com/edit/web-platform-kzjy7j?file=index.html

**Comment by JaggerLS** [comment]
Thank you so much for your help, i was able to accomplish what i needed to do. In the future i´ll ask more things, this lib have a lot of interesting things. Have a good day.
