### ISSUE TITLE
Order nodes arrangement by data value

### ISSUE THREAD

**Issue by neolution** [bumbeishvili/org-chart#118]
Is it possible to rearrange the nodes by a data value?

Ex. for a data structure:

`{
    "name": "flare",
    "children": [
        {
            "name": "analytics",
            "children": [
                {
                    "name": "cluster",
                    "children": [
                        {
                            "name": "AgglomerativeCluster",
                            "value": 3938
                        },
                        {
                            "name": "CommunityStructure",
                            "value": 3812
                        },
                        {
                            "name": "HierarchicalCluster",
                            "value": 6714
                        },
                        {
                            "name": "MergeEdge",
                            "value": 743
                        }
                    ]
                },`

Now I want to arrange the nodes by the "value"-attribute in ascending order, so that the nodes with the lowest value is shown left and the node with the highest value is shown right (in a horizontal layout, left to right).

Thank you!

**Comment by bumbeishvili** [comment]
Check this - https://github.com/bumbeishvili/org-chart/issues/104

**Comment by neolution** [comment]
Sorry but I'm a little bit confused ...

Here my code:

`
 sortNode(nodeId) {

        const attrs = this.getChartState();
        const node = attrs.allNodes.filter(({ data }) => attrs.nodeId(data) == nodeId)[0];
        if (!node) {
            console.log(`ORG CHART - SORT - Node with id "${nodeId}" not found in the tree`);
            return this;
        }

        // sort node childs
        const sortedNode = node.sort((a, b) => d3.ascending(a.data.orgData.orderNo, b.data.orgData.orderNo));
        attrs.allNodes.map(node => {
            if (node.id == nodeId) {
                node = sortedNode
            }
            return node
        })

//so here the node order is correct, but I don't know how to order the associated data so the chart represents the new order
`

Thank you for your hints.

**Comment by neolution** [comment]
OK I sorted the data array before generating the chart. That's ok for me. Thank you.
