### ISSUE TITLE
Update chart on new data

### ISSUE THREAD

**Issue by alexaac** [bumbeishvili/org-chart#119]
Hi, is there an option to update the whole chart based on new data?

Something like chart.updateData(newData)

For example 
updateData: function (newData) {
  const attrs = this.getChartState();

  // Reassign data
  attrs.data = newData;

  const updateNodesState = this.updateNodesState.bind(this);
  // Update state of nodes and redraw graph
  updateNodesState();

  return this;
};

I know you are working on this project mostly for free, I have mentioned this feature more as a suggestion than as a request.
And to find out if the feature exists and I somehow haven't seen it.

Thank you.

---

**Comment by bumbeishvili** [comment]
Hi, have you tried 

`chart.date(newDate).render()?`

**Comment by alexaac** [comment]
That's it, chart.data()... It was too easy to spot, that's why I haven't seen it. :) 
Thank you, sorry for bothering you.

**Comment by bumbeishvili** [comment]
No problem, I am sure this question will be helpful to someone
