### ISSUE TITLE
display bug on safari for macos,  on chrome+safari for iphone

### ISSUE THREAD

**Issue by n1crack** [bumbeishvili/org-chart#120]
**Describe the bug**
Safari does not display the chart as it should be.

**To Reproduce**
1. Open safari
2. Go to the example : https://stackblitz.com/edit/web-platform-lwyild 
3. See error

**Expected behavior**
Everything should be in their place..

**Screenshots**
![image](https://user-images.githubusercontent.com/712404/152028935-bac6cb0e-19dd-4b03-ab93-890dbd5be28c.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 12.1
 - Browser : Safari 15.2

**Smartphone (please complete the following information):**
 - Device: iPhone8 Plus
 - OS: latest
 - Browser: Both Chrome & Safari

**Comment by bumbeishvili** [comment]
It's a known issue - https://github.com/bumbeishvili/org-chart/issues/69

I made the first two examples safari safe - so if you want them to work in safari, extend the first two examples.

I do not intend to fix them, I think it's a safari issue, and hoping they will fix it

**Comment by n1crack** [comment]
i played with the examples and mix them. :) somehow I got what I need.

I'll share it here maybe it helps someone else.

https://stackblitz.com/edit/web-platform-xkdtpd

thx.

**Comment by bumbeishvili** [comment]
Nice, please link it in the mentioned issue as well, since that is where people with similar issue land

**Comment by n1crack** [comment]
feel free to close the issue  👍

**Comment by bumbeishvili** [comment]
Closing as #69 Duplciate

**Comment by meta5xserver** [comment]
Found the issue and fixed it. Thought was a big issue. but very simple check your div box is position is absolute just remove and use top left to position your text or image.

Below is just an eg:- 
From
This : <div style="color:#ffffff;position:absolute;right:15px;top:-20px; width:165px;">
to
This : <div style="margin-left: 140px;margin-top: -175px;left:0;right:100;top:-20px;">
