### ISSUE TITLE
Export functionality - styles not applied

### ISSUE THREAD

**Issue by mehdy-karimpour** [bumbeishvili/org-chart#121]
We are using your great library in a C#-TypeScript-React project. It is awesome but there is a problem with the export functionality.

This is the org chart

![org-chart](https://user-images.githubusercontent.com/75680087/152363163-6300fd0d-971c-4664-bff7-6efb423de3a8.png)

When I export it to png for example, this is the output result:

![exported-org-chart](https://user-images.githubusercontent.com/75680087/152363172-b77337b0-9618-4241-8c0a-5730185e7cd1.png)

I did not try pdf but now we need png.
Would you please help?

best regards,
mehdy

**Comment by bumbeishvili** [comment]
Mos probably styles for nodes are defined outside. In order to maintain styling for nodes when exporting, it should be defined as inner styles

Take a look at this example  - https://stackblitz.com/edit/web-platform-o5t1ha

I had to apply inner styling to SVG just because of that 

<img width="615" alt="Screenshot 2022-02-02 at 19 33 21" src="https://user-images.githubusercontent.com/6873202/152185333-70f0e2e2-e301-46d2-b38d-139dcc51422c.png">

This is the export result , it retains every styling which was applied to it

![graph](https://user-images.githubusercontent.com/6873202/152185809-162c6cf7-bfbf-447d-9c9f-96e517bc6f8d.png)

**Comment by mehdy-karimpour** [comment]
Hi, thanks for your consideration,

This is my code. I have used standard bootstrap classes.

```
return (
    <div>
      <OrgChart
        data={orgChartData}
        nodeContent={(node: any) => {
          const dto = node.data as OrganizationChartVisualDTO;
          return <>
            <div className="text-center">
              <div className="border bg-primary text-white font-weight-bold" >{`${dto.personnel.firstName} ${dto.personnel.lastName}`}</div>
              <div className="border bg-info text-white" title={`(OrgChart.Id=${dto.id})`}>
                <div>{dto.personnel.departmentName}</div>
                <div>{dto.personnel.title}</div>
              </div>
            </div></>
        }}
        nodeHeight={() => 85}
        nodeWidth={() => 250}
        onNodeClick={onNodeClick}
        extraButtons={(chart) =>
          <>{currentUserOrgChart?.id &&
            <label className={classes("btn", getToolbarButtonClass())} title={OrganizationChartMessage.CenterMyPosition.niceToString()}
              onClick={() => {
                chart.setExpanded(currentUserOrgChart.id!.toString(), true)
                  .setCentered(currentUserOrgChart.id!.toString())
                  .updateNodesState();
              }}><FontAwesomeIcon icon='user' ></FontAwesomeIcon> </label>}
          </>}
        keyNodeId={currentUserOrgChart?.id!.toString()}
      />
    </div>
  );
```

**Comment by bumbeishvili** [comment]
Makes sense, instead, you will need to apply styles as inner class . 

`style="font-weight:bold"` etc

like this, as I see from your image, it's not much hard to reproduce the same styling.

There may be a second workaround, after export is invoked, you can plug in a script (before invoking export), which will loop over all DOM elements inside the org chart and will apply external styling as inner styles. Not sure if this is possible though, worth a try  (If it works, please also post a script here, it may help others with similar issues)

**Comment by mehdy-karimpour** [comment]
Hi again,

I did it and works fine, thanks.
