### ISSUE TITLE
get the real-time zoom level when zooming the chart 

### ISSUE THREAD

**Issue by zhoufenfens** [bumbeishvili/org-chart#123]
Hi, thanks for your library, it works great.
but I have some questions,
1. the chart.lastTrasform().k provided the zoom level, but is it a way to get the zoom event when I am zooming the chart by using the touchpad ?  
another questions :
2. Does this chart has destroy or dispose method ?
3. I wanted to recover the chart to initial zoom level(1) after zoomed the chart, is it possible to make it?

**Comment by bumbeishvili** [comment]
Hi,

> the chart.lastTrasform().k provided the zoom level, but is it a way to get the zoom event when I am zooming the chart by using the touchpad ?

It uses d3.zoom, if d3.zoom registers the touchpad event, then  chart.lastTrasform().k will also update

> Does this chart has destroy or dispose method ?
No

> I wanted to recover the chart to initial zoom level(1) after zoomed the chart, is it possible to make it?
At this point, it's not possible to reliably do that (without strange issues)

**Comment by zhoufenfens** [comment]
thanks for your reply.
in consideration of my poor English,  i think i did not describe my question clearly.
our productManager has a requirement, he wants to show the zoom level on the chart,   the chart.lastTrasform().k works well, but I do not know how to get the zoom level instantly when user zooming the chart 
here is the design draft below
<img width="230" alt="image" src="https://user-images.githubusercontent.com/3303836/154429034-5b3b2f27-8a87-4f34-978b-2183205a39fa.png">

**Comment by bumbeishvili** [comment]
I see, at this point I don't have a viable solution (except doing setInterval in every 200 ms and getting the value like that)

**Comment by zhoufenfens** [comment]
thank you for your reply.
I found the MutationObserver could detect the mutations of dom`s attributes, although it is a bit of dirty.
```javascript
let observerOptions = {
  childList: false,
  attributes: true,
  subtree: false,
};
let callback = function(mutationList, observer) {
  mutationList.forEach((mutation)=> {
    if (mutation.attributeName === 'transform') {
      _this.scale = _this.chart.lastTransform().k;
    }
  });
}
let observer = new MutationObserver(callback);
observer.observe(d3.select('g.chart')._groups[0][0], observerOptions);
```

**Comment by bumbeishvili** [comment]
I was searching on google in the same direction as well.

Yes, seems dirty but I don't suppose that we have another choice at this point. I will keep this issue open and will expose a method in v3 for zoom callback

**Comment by bumbeishvili** [comment]
In the new v3 version, we will have the following callbacks

<img width="568" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/769710c5-552c-466e-87d6-b5cf0197d839">

If you want to get zoom level when it changes, you can just log 

```javascript
chart.onZoom(e=>console.log(e.transform.k))
```
