### ISSUE TITLE
Group Nodes with no-childrens

### ISSUE THREAD

**Issue by dkunze** [bumbeishvili/org-chart#126]
**Is your feature request related to a problem? Please describe.**
For example, I can add A, B and C nodes. So, If I add ten A nodes, 10 B nodes and 10 C nodes I will have a bigger graph on the screen.

**Describe the solution you'd like**
Is there any way to group all of these A, B and C nodes (30 in totals, 10 for each of them) in only 3 groups? So, If I add a children node to any A node, I will see A with this new children, a group for A's (with 8 more A's), a group for B's (with 9 B's) and a group for C's (with 9 C's)

---

**Comment by bumbeishvili** [comment]
There is not any functionality like it, there may be workarounds, but for me they seem complex, so won't mentione them here

**Comment by bumbeishvili** [comment]
Heads up,

Currently, I am working on pagination, which is somehow related to this issue. While not exactly the same, the final purpose is to make the graph more compact and user friendly to use, the same purpose as this ticket

https://user-images.githubusercontent.com/6873202/169758663-0a117074-e6d5-4be4-a981-afff3fd21037.mp4

**Comment by bumbeishvili** [comment]
Also, potentially this is a path to allow lazy loading nodes

**Comment by dkunze** [comment]
@bumbeishvili oh this seems to be amazing! keep us updated please! thank you so much for let me know! :)
