### ISSUE TITLE
Multi-Structure Support

### ISSUE THREAD

**Issue by husseinaltaaf** [bumbeishvili/org-chart#128]
**Is your feature request related to a problem? Please describe.**
I need to display two structure in one diagram with only 1 parent (above & below it) on my website. because the 2 structure's meanings are different so I wanted it to be displayed apart but in 1 diagram

**Describe the solution you'd like**
One parent should be displayed with 1 structure above & 1 structure below.

**Comment by bumbeishvili** [comment]
I don't exactly understand  what you need to do

**Comment by husseinaltaaf** [comment]
I want to be able to add 1 structure above the main parent(node 0) and also below it.

E.g: a company has 2 types of peoples tree hierarchy below it. I wish to be able to displays one hierarchy above the company & 1 below it...

Hmm got it or not?😅
Is there any possibility or hope for this kind of feature?

**Comment by torchsmith** [comment]
I think he's saying this:

N&nbsp;&nbsp;&nbsp;N
&nbsp;\\&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/
&nbsp;&nbsp;\\&nbsp;/
Root
&nbsp;&nbsp;&nbsp;/\\
&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;\\
N&nbsp;&nbsp;&nbsp;N

**Comment by bumbeishvili** [comment]
Makes sense.

Generally answer is no, that structure is not supported.

Although everything is overridable and with some limitations, there is a chance that similar thing can be built
