### ISSUE TITLE
React Compiler "export 'event' (imported as 'd3') was not found in 'd3'"

### ISSUE THREAD

**Issue by JosefSaltz** [bumbeishvili/org-chart#133]
**Describe the bug**
When compiling with create-react-app using the react integration example. Webpack generates an error saying export 'event (imported as 'd3') was not found in 'd3' and then goes on to list possible exports.

**To Reproduce**
1. Generate a fresh project with create-react-app
2. Copy files from React Integration Example
3. Run the start script in package.json

**Expected behavior**
No Compiler Errors

**Desktop (please complete the following information):**
 - OS: WSLv2
 - Browser Firefox
 - Version 98.0.1

**Comment by JasonFoglia** [comment]
> Since version 6 "D3 now passes events directly to listeners, replacing the d3.event global and bringing D3 inline with vanilla JavaScript and most other frameworks." [https://observablehq.com/@d3/d3-6-0](url)
> 
> Unless you need features of version 6 or 7 of D3 just use version 5 as a quick fix

@nanosekun-de thank you. 

As mentioned d3.event was replaced and passing them in as parameters works good.
