### ISSUE TITLE
How to spread out the tree horizontally, in top-down mode

### ISSUE THREAD

**Issue by ajmas** [bumbeishvili/org-chart#134]
I am wanting to display the chart in a top down manner, but with the unexpanded child nodes spread out horizontally. As an example:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/682269/159557343-d36e30fc-e79a-4c53-8da2-9a6cc5e1779d.png">

How would I go about this?

**Comment by bumbeishvili** [comment]
```javascript
chart
  .compact(false)
  .layout('top') // default

```
