### ISSUE TITLE
Disable zoom on scroll only

### ISSUE THREAD

**Issue by rasmushassenkam** [bumbeishvili/org-chart#136]
Hello, first off I want to thank you for this library.

Second, Is there any way of disabling zoom only on wheel scroll?
I see that zoomBehaviour is exposed in the types, but there is no documentation about how to use it.

**Comment by bumbeishvili** [comment]
Org chart does not have a specific way of doing it, but it exposes the state which has the original SVG element attached. You can disable wheel zoom for it

```javascript
chart.getChartState().svg.on("wheel.zoom", null);
```

**Comment by rasmushassenkam** [comment]
Great! Thank you for a quick answer!

**Comment by gustavog6** [comment]
> Org chart does not have a specific way of doing it, but it exposes the state which has the original SVG element attached. You can disable wheel zoom for it
> 
> ```js
> chart.getChartState().svg.on("wheel.zoom", null);
> ```

Is there a way to activate the zoom in the same way that it is deactivated? I'm implementing a solution that depending on the current zoom level allows the chart to be moved or not and I can't figure out how
