### ISSUE TITLE
How to not have rounded edged on joining lines

### ISSUE THREAD

**Issue by usmanaslam1555** [bumbeishvili/org-chart#137]
i am trying to reduce the curve on the edges of the lines that connect my cards, i checked all the examples but couldnt find how they did it so please help. In the screenshots below u can see how it looks rightnow(more curved) vs how i want it to look like
<img width="534" alt="Screenshot 2022-03-29 at 11 47 02 AM" src="https://user-images.githubusercontent.com/79101329/160529337-4cfc16f2-1b6f-4c99-8dde-fea5a5c652d8.png">
 
<img width="371" alt="Screenshot 2022-03-29 at 11 46 53 AM" src="https://user-images.githubusercontent.com/79101329/160529331-ca21d987-fc18-48c0-a2b1-535740d917b6.png">

**Comment by bumbeishvili** [comment]
You'll need to learn about custom SVG shape path commands.

Here is a notebook where built those links, you can play with it. In the end you will need to copy the source code, replace diagonal code and use your own
https://observablehq.com/@bumbeishvili/curved-edges-compacty-vertical

**Comment by usmanaslam1555** [comment]
not sure where am supposed to put the code, how did u do it this example :
https://stackblitz.com/edit/web-platform-o5t1ha

 i cant see anywhere u override the code?

**Comment by Chmer** [comment]
> i am trying to reduce the curve on the edges of the lines that connect my cards, i checked all the examples but couldnt find how they did it so please help. In the screenshots below u can see how it looks rightnow(more curved) vs how i want it to look like <img alt="Screenshot 2022-03-29 at 11 47 02 AM" width="534" src="https://user-images.githubusercontent.com/79101329/160529337-4cfc16f2-1b6f-4c99-8dde-fea5a5c652d8.png">
> 
> <img alt="Screenshot 2022-03-29 at 11 46 53 AM" width="371" src="https://user-images.githubusercontent.com/79101329/160529331-ca21d987-fc18-48c0-a2b1-535740d917b6.png">

hi,
I can see that you added marker-end, how did you do that?
also could you find out how to change the rounded edges?
appreciate if someone can help ASAP

**Comment by Chmer** [comment]
hi, @usmanaslam1555 
I can see that you added marker-end, how did you do that?
also could you find out how to change the rounded edges?
appreciate if someone can help ASAP

**Comment by bumbeishvili** [comment]
In the new v3 version, you'll have the possibility to override that diagonal function I mentioned.

You'll still need to understand how svg path commands work though if you want to override it with something different

https://github.com/bumbeishvili/org-chart/blob/f85dcd4bea42fa0d0ebb1cf5ff4b86ea5879d7ba/src/d3-org-chart.js#L220-L257
