### ISSUE TITLE
Two Parent Root

### ISSUE THREAD

**Issue by galihprasetio** [bumbeishvili/org-chart#138]
Can create chart with two parent root on top hirarchy ?

**Comment by bumbeishvili** [comment]
No

**Comment by Ayesha-Sayyed** [comment]
Can we achieve this Fake multi-rooted tree example @bumbeishvili 
http://bl.ocks.org/ialarmedalien/c92a58f2fee695c3931c1b6e30540d98 here in this library?

**Comment by bumbeishvili** [comment]
I guess so

You can just use CSS to hide first  node and first two links

<img width="727" alt="image" src="https://user-images.githubusercontent.com/6873202/163801006-19f1f716-bfe7-42c1-8bd6-abc45dab96aa.png">


it's just SVG

![image](https://user-images.githubusercontent.com/6873202/163801031-5e2f9fdc-1852-4bee-9ad0-43a65586709d.png)


You will probably also need to:
* Decrease first `nodeHeight`
* Decrease the first level `childrenMargin`
* Set `chart.compact(false)`

**Comment by Ayesha-Sayyed** [comment]
Hi @bumbeishvili thanks for the reply, actually I'm able to hide the node but the links-wrapper class is created once and it changes reflects all the links as shown in your image above is there a way to only access root link and modify it ?

**Comment by Ayesha-Sayyed** [comment]
Thanks! It worked @bumbeishvili

**Comment by m-gallesio** [comment]
> You can just use CSS to hide first node and first two links

It seems the order of the links is not guaranteed, though.

I have tried with the following code:
```javascript
let linkCount = chart.getChartState().root.children.length;
if (linkCount > 0) {
    const wrapper = document.querySelector(".links-wrapper"); // or extract from getChartState().linksWrapper, I guess
    while (linkCount > 0) {
        wrapper.firstChild.remove();
        linkCount--;
    }
}
```

Sometimes it does work, but other times the first N links are **not** those which start from the root.

I have also considered overriding `connectionsUpdate` as explained [here](https://github.com/bumbeishvili/org-chart/issues/59) to prevent their generation altogether, but the `state.connectionsUpdate` function / option does not seem to be called at all (I have tried putting `debugger` / `alert` into it and they do not seem to get reached).

**Comment by bumbeishvili** [comment]
You can also use `chart.connections`  to fake multi root
