### ISSUE TITLE
Can we change default onload depth of tree?

### ISSUE THREAD

**Issue by Lazeeez** [bumbeishvili/org-chart#139]
Can we change default on-load depth of the chart?

for example currently it shows 1 layer of sub-nodes as soon as the page loads
can we make it 3 or maybe even 4?

like currently when i load the page is loads like this
![Screenshot-2022-04-07-at-1 44 51-PM](https://user-images.githubusercontent.com/64376519/162153697-6bbad268-cb85-41fe-92ef-3d56cb06cff9.jpeg)

whereas i want it to load like this
![Screenshot-2022-04-07-at-1 42 53-PM](https://user-images.githubusercontent.com/64376519/162153890-507cff93-f304-4cce-ac16-4d0ff397f656.jpeg)

**Comment by Lazeeez** [comment]
using this repository for my college project to organise a organisation graphically its just the professor wants to load more nodes on the starting page.

i would really appreciate the help.

**Comment by Lazeeez** [comment]
@bumbeishvili @TildeWill

**Comment by bumbeishvili** [comment]
There is no direct way. You could try setting the `_expanded` property to the certain level  of nodes and render it. It will probably work

**Comment by Lazeeez** [comment]
@bumbeishvili can you please help me with it? this is my first project with TS and I don't really have much idea.

**Comment by Lazeeez** [comment]
@bumbeishvili could you atleast tell me where should i make the changes, it'll hardly take 5 mins im almost done with everything only this depth thing is remaining

**Comment by thefoxie** [comment]
@Lazeeez there's `expandAll()` if you want to expand all on load.

**Comment by Lazeeez** [comment]
> @Lazeeez there's `expandAll()` if you want to expand all on load.

thanks for suggesting it but the tree is actually very big and just expanding 2-3 level on startup makes it more presentable. so i don't think I should use `expandAll()`

**Comment by Lazeeez** [comment]
@bumbeishvili is there a way with which i can get the depth of most recent node?

**Comment by bumbeishvili** [comment]
What do you mean by the `most recent node` ?

**Comment by Lazeeez** [comment]
> What do you mean by the `most recent node` ?

The data i have is a list of dictionaries I've formatted it like your `sample data` and that the root node has no `parentId` (thats how it's a root) and the rest of them have other people's Id as `parentId` so the most recent dictionary that I'm getting is my most recent node refer to this image for the data I'm getting.. ![IMG_20220408_152149.jpg](https://user-images.githubusercontent.com/64376519/162412060-e957f2f4-55a3-40a5-8a7e-6f8b4dafccd4.jpg)

**Comment by bumbeishvili** [comment]
Ah, I understand now. 

There is no direct way of it.

What you can do however is to include use [d3.stratify](https://observablehq.com/@d3/d3-stratify) (independent library), pass your data, and then loop over it, find your node and check  the level

**Comment by Lazeeez** [comment]
> Ah, I understand now.
> 
> There is no direct way of it.
> 
> What you can do however is to use [d3.stratify](https://observablehq.com/@d3/d3-stratify) (independent library), pass your data, and then loop over it, find your node and check the level

it worked! it works perfectly.

**Comment by Lazeeez** [comment]
@bumbeishvili I had another question, can we put a limit on the chart container. right now, its a endless white canvas with the chart in between. so what i want is if the user tries to navigate above the chart, after a point it wont go any further.

**Comment by bumbeishvili** [comment]
No, at this point it's not possible, but I will keep it in mind for future versions

**Comment by Lazeeez** [comment]
> No, at this point it's not possible, but I will keep it in mind for future versions

sure, thanks for the help

**Comment by Lazeeez** [comment]
@bumbeishvili is there a way with which we can hide the sibling nodes and see one particular branch?

to be more precise, i want to implement something like 
```
Setuptotheroothighlight function
```
but only the highlight nodes will be visible. i tried removing the rest of the nodes from the chart and it looks perfect but i don't want to remove the nodes.

**Comment by bumbeishvili** [comment]
I can't think about any workaround which will achieve a similar effect

**Comment by Lazeeez** [comment]
> I can't think about any workaround which will achieve a similar effect

what if I pass few nodes and create another temp chart.. just for those nodes.. is there any function for that?

**Comment by Lazeeez** [comment]
@bumbeishvili can we increase the container height somehow?

**Comment by bumbeishvili** [comment]
You can use `chart.chartHeight(number)` for height

**Comment by 180and170** [comment]
Can the size of each container be dynamic ？   @bumbeishvili 

Two containers named A1 and A2 on my organization chart need to be displayed. A1 and A2 are different in size. For example, the width of A1 is 100px and the width of A2 is 50px. I set the width of the container to 100px at the beginning, but the A2 interval will appear a little wide. Is there a way to dynamically set the width of the container at this time

**Comment by bumbeishvili** [comment]
I am updating the expand-level functionality.

From now on you. can configure the depth at which the org chart will open 

```javascript
chart.initialExpandLevel(0) // Only root node will open

chart.initialExpandLevel(1) // Default behavior, root and its children will be expanded

chart.initialExpandLevel(2) // All nodes with depth 2 will be expanded
```
