### ISSUE TITLE
calling chart.fit() after expanding/collapsing a node (onButtonClick)

### ISSUE THREAD

**Issue by MehdyKarimpour** [bumbeishvili/org-chart#140]
Hi,
I want to call chart.fit() after a node is expanded or collapsed. How can I do that?
I am using React/TypeScript but you can explain in JS too.

**Comment by bumbeishvili** [comment]
The only workaround that comes to my mind is to listen to expand/collapse click and the invoke `fit()` method inside setTImeout with 2-3 sec delay
