### ISSUE TITLE
Orgchart - all nodes automatically opened

### ISSUE THREAD

**Issue by mjaskulski1** [bumbeishvili/org-chart#141]
Hi,
I try to prepare org chart and I found your solution on github.
Please - help me - what I should do to have all nodes automatically opened ?

Kind regards, Michal

**Comment by bumbeishvili** [comment]
I think just setting `_expanded=true` property to each node you want to be opened will be enough

**Comment by marcellino-ornelas** [comment]
I needed to make all nodes open for my project. Im using `chart.expandAll();` 😃 

This method is not chainable tho

**Comment by bumbeishvili** [comment]
I think it's chainable. That function basically just sets the same thing for all nodes and rerenders graph

![014E8D4F-8701-41C6-BBCB-58A04FA9E25E](https://user-images.githubusercontent.com/6873202/170351852-b886700a-ee86-4df9-910a-3c4ad2899ca6.jpeg)

**Comment by marcellino-ornelas** [comment]
TIL, looks like a typescript error instead then sorry about that 😃 

![Screen Shot 2022-05-25 at 12 29 38 PM](https://user-images.githubusercontent.com/35247622/170352370-ac41b732-35b3-4fd9-bbfd-7127aa9da1bb.png)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c432b1015151bc90947ea2ac3b1a50a86734ad0b/types/d3-org-chart/index.d.ts#L169

**Comment by bumbeishvili** [comment]
Yes, unfortunately I don't have capacity to maintain that as well.
