### ISSUE TITLE
Unable to use setExpanded

### ISSUE THREAD

**Issue by abha1281** [bumbeishvili/org-chart#143]
I am struggling to use the chart.setExpanded function, would appreciate assisting in figuring out the issue. Let me know if you need anything else

**Below is an image of the code I'm using**
![image](https://user-images.githubusercontent.com/55664644/165465793-ff4fd736-8371-41c4-9515-4b8db59ca1d4.png)

**Comment by bumbeishvili** [comment]
Please provide an online demo and try to follow instructions highlighted in this image

![image](https://user-images.githubusercontent.com/6873202/165468599-c7c82938-dbe4-44a4-bac4-d3da8831e0ee.png)

**Comment by abha1281** [comment]
setExpanded() works for the root node, however, when clicked on the node of a child with setExpanded passed it does not work. 

Below is a live example.
[Example Link](https://stackblitz.com/edit/nextjs-wj2snq?file=components/OrgChart.js)

**Comment by bumbeishvili** [comment]
Works for me. 

Note, you are setting expansion flag as false (so, you are not expanding, but actually collapsing the node)



https://user-images.githubusercontent.com/6873202/165488247-f54a6935-b413-4e60-a0fd-a8f2a5f84afc.mp4

**Comment by abha1281** [comment]
After watching the video, realized the ID passed into the function was of the child's not the parents. Thanks for the help

**Comment by Shadowfita** [comment]
@bumbeishvili I've noticed that "setExpanded" won't allow you to close a node that was open by user clicking.

If I do setExpanded(node, false); with a node that is already visible, and was made visible by user interaction, nothing happens. If I do setExpanded(node, true); first, then false, it works as expected.

**Comment by bumbeishvili** [comment]
@Shadowfita  #154 , opened a new issue about that. It will be on my radar

**Comment by Shadowfita** [comment]
> @Shadowfita #154 , opened a new issue about that. It will be on my radar

Legend, thank you.
