### ISSUE TITLE
Can I set the size of each container

### ISSUE THREAD

**Issue by 180and170** [bumbeishvili/org-chart#145]
Can I set nodewitdh or nodeheight of containers one by one,
For example, for the container named A1, I want to set the width to 100px, and for the container named A2, I want to set the width to 50px

**Comment by bumbeishvili** [comment]
Yes, bot nodeWidth and nodeHeight receive function as an argument and you can specify your own dimensions.

One catch is that when specifying unusual values, for example like `Math.random()*400` I observed that in the several cases layout function broke 

`chart.nodeWidth(n=> 200).nodeHeight(n=>100)`
