### ISSUE TITLE
How do I open all the child nodes under this node

### ISSUE THREAD

**Issue by 180and170** [bumbeishvili/org-chart#146]

**Comment by bumbeishvili** [comment]
Check this example - https://stackblitz.com/edit/web-platform-o5t1ha?file=index.html

```javascript
chart.expandAll()
```

**Comment by 180and170** [comment]
Let me be clear. What should I do when I just want to open the child nodes under the non root node

**Comment by 180and170** [comment]
My only way now is to find the data of the child nodes under the currently selected node and add them one by one_ Expand property, then update the data source, and then re render
However, how can I obtain the expansion status of other peer or parent nodes other than the currently selected node? The above operation of updating the data source will lead to the loss of the expansion status of other nodes, which is not what I want

**Comment by 180and170** [comment]
Help me, boss

**Comment by bumbeishvili** [comment]
I am not still exactly sure, can you provide an example and video recording what is the issue and what are you trying to do?

**Comment by 180and170** [comment]
![image](https://user-images.githubusercontent.com/33509410/168605602-9206ddf8-5b8d-4187-8676-9e73b4506a1c.png)
 Thank you very much. After I read the source code, I know the solution
I can solve my problem by changing the value of "_expand"
