### ISSUE TITLE
Is there a way to input JSON datastructure to the orgchart plugin?

### ISSUE THREAD

**Issue by Chethan-7** [bumbeishvili/org-chart#149]
My data will come from MongoDB database and i need to display the parent-child relationship. I see that the examples are all using CSV data. Can i instead use JSON data?

**Comment by bumbeishvili** [comment]
Yes, org chart actually receives array of objects, so JSON will work without issues

**Comment by schindld** [comment]
It won't work with JSON objects nested in a tree structure though. Your json will have to be flattened like a csv file. For example, `data = JSON.parse('[{...}, {...},...]')`, where each object is a single layer of key/value pairs with parentIds pointing to ids of other rows.

**Comment by bumbeishvili** [comment]
That's true, although it's fairly easy to convert nested tree structures to the flattened structure

#93 issue was about that
