### ISSUE TITLE
Getting id of active node

### ISSUE THREAD

**Issue by seven700** [bumbeishvili/org-chart#150]
Hi, in the full futuristic example found [here](https://stackblitz.com/edit/web-platform-o5t1ha?file=index.html), the onclick events for the buttoms have the node id hard coded:

```
  <button onclick='chart.setHighlighted("O-6162").render()'  class="btn btn-action-button waves-effect waves-light">
        <i class="fas fa-highlighter"></i> mark</button
```

Is there are way so that the last known active id, eg a node that has just been expanded, can be referenced in an onclick event? I might be missing something simple here, but any help would be appreciated.

**Comment by bumbeishvili** [comment]
I don't think that there is a straightforward way to do it.

As I can see you have two workarounds

Workaround . in the node update function add an additional custom event listener for the button content and save activeNode reference in external variable
```javascript
 let activeNode;

 chart.nodeUpdate(function(){
   d3.select(this).select('.node-button-g').on('click.active-node',d=>{
      activeNode = d;
    })
})
```
