### ISSUE TITLE
Adding an Assistant

### ISSUE THREAD

**Issue by DeathStapler** [bumbeishvili/org-chart#151]
Is there any way to add an assistant to the org chart?  If not, is there any plan to add that functionality?

**Comment by bumbeishvili** [comment]
What do you mean exactly by an "assistant"?

**Comment by DeathStapler** [comment]
This is an example.

https://plumsail.com/docs/orgchart/v1.x/how-tos/display-assistant-in-sharepoint-orgchart.html

**Comment by bumbeishvili** [comment]
Ah, no you won't be able to do it easily.

But you can manipulate `nodeWidth`, `nodeHeight`,  `layoutBindings` and you could achieve something like that. But again, it's not straightforward

**Comment by DeathStapler** [comment]
Ok.  Thanks.
