### ISSUE TITLE
.compact(true) not working

### ISSUE THREAD

**Issue by nikhilthakur001** [bumbeishvili/org-chart#152]
chart
        .container(d3Container.current)
        .svgHeight(window.innerHeight - 10)
        .data(props.data)
        .nodeHeight((d) => 200)
        .nodeWidth((d) => 250)
        .initialZoom(0.7)
        .childrenMargin((d) => 40)
        .compactMarginBetween((d) => 15)
        .compactMarginPair((d) => 80)
        .neightbourMargin((a, b) => 50)
        .siblingsMargin((d) => 100)
        `.compact(true)`
        .nodeContent((d, i, arr, state)
       .render()

Trying to do .compact(true) still the org chart does not renders in compact mode. It still shows the vertical mode only.

**Comment by nikhilthakur001** [comment]
I was supposed to do compact(false). My bad.

**Comment by bumbeishvili** [comment]
By default, it's a compact version (which you called a vertical)
