### ISSUE TITLE
Child node connected to two parent nodes

### ISSUE THREAD

**Issue by zedgell** [bumbeishvili/org-chart#153]
We are trying to find a way to connect one child node to two parent nodes. Is this possible?

![image](https://user-images.githubusercontent.com/37593687/175832930-9e41e25e-43dc-4fde-b3eb-8de46bebd89d.jpeg)

**Comment by bumbeishvili** [comment]
It's **not** possible

**Comment by torchsmith** [comment]
Can't you make the Business Loan a child of Guarantor, and then draw just the link between Primary Borrower and Business Loan as an extra link?

**Comment by bumbeishvili** [comment]
It's possible to add connections array

```javascript
chart.connections([{from:'fromId',to:'toId',label:'connection name'}]).render()
```
