### ISSUE TITLE
setExpanded" won't allow you to close a node that was open by user clicking.

### ISSUE THREAD

**Issue by bumbeishvili** [bumbeishvili/org-chart#154]
![image](https://user-images.githubusercontent.com/6873202/175869001-68ebe79c-acf0-45a7-af70-594ba53d7822.png)

**Comment by kodelio** [comment]
Hello,
Even by using setExpanded(node, true) before false is not working. Is there any other workaround to open only one node at a time ?
Here the logic I tried
`chart1.setExpanded(previouslyClicked).setExpanded(previouslyClicked,false).render();`

**Comment by bumbeishvili** [comment]
Possibly related #184

**Comment by bumbeishvili** [comment]
Just informing you about possible changes in org chart v3 which also concerns setExpanded method.

From now on `setExpanded(nodeId,false)` will actually collapse the node, even when it's expanded by the user.

In the background, it will just set `_expanded` flag to all siblings and descendants (before it would set that flag only to the node itself, but if siblings also had this flag, rerender would not collapse this node).

Also improved collapsing position behavior. Now collapsed nodes always go to direct parent position (before, they'd go to root)
