### ISSUE TITLE
How can i pass json in Data instead of CSV ?

### ISSUE THREAD

**Issue by gunaseelane** [bumbeishvili/org-chart#157]
How can i pass json in Data instead of CSV ? #157

**Comment by bumbeishvili** [comment]
It actually receives JSON as a data, not CSV, so you can just use fetch to load JSON files and pass it to the chart directly


```javascript
fetch('json_data_url.json')
 .then(d=>d.json())
 .then(data=>{
  const chart = new OrgChart()
     .data(data)
     .container ...
     ...
     .render()
})
```

**Comment by gunaseelane** [comment]
can I directly pass JSON  data, instead of JSON file without d3?

**Comment by gunaseelane** [comment]
I'm passing this directly to org-chart, not to d3

**Comment by bumbeishvili** [comment]
take a look at #149 and #93

**Comment by gunaseelane** [comment]
Thank you so much, it worked, sorry I am new to d3 and its packages.

**Comment by emmaMinty12** [comment]
NOT AN ISSUE - Need a help 

I'm new to d3, here from this [comment](https://gist.github.com/bumbeishvili/dbc0beff4baf64674b0f05b94cb4462e?permalink_comment_id=3366404#gistcomment-3366404)

looked into https://github.com/bumbeishvili/org-chart/issues/93 but still not getting it, how can I use JSON data 

On D3 v3 for hierarchy chart, the following JSON data is used ```https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/redesignedChartLongData.json```
  
want to create this [example](https://stackblitz.com/edit/web-platform-3gwnsg?file=index.html) with the above JSON data.

**Comment by bumbeishvili** [comment]
@emmaMinty12 

so, first you have to convert it to flat data and then you can supply it to org chart. 

```javascript
d3.json(`https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/redesignedChartLongData.json`,hierarchyData=>{
 
// Flatten data
const flatDataNodes = d3.hierarchy(hierarchyData)
  .descendants()

// Then we want to  add id & parentId to maintain hierarchy within the flat data
flatDataNodes.forEach(d=>d.data.id = Math.random()*1000000000); // close enough id generation

// Add parent id
flatDataNodes.forEach(d=>d.data.parentId = d.parent?.data?.id;)

//Then get original data
const finalFlatData = flatDataNodes.map(d=>d.data);

// Then supply flat data to graph and that's it
 chart = new d3.OrgChart()
          .container('.chart-container')
          .data(data) 
          .render();

})
```

Haven't tested the code, written directly in Github editor

**Comment by emmaMinty12** [comment]
@bumbeishvili Thank you for your quick reply

I have checked with the above code, I'm not getting any issues or o/p  please check this my [Example](https://stackblitz.com/edit/web-platform-wewu2h?file=index.html), the layout is blank

**Comment by emmaMinty12** [comment]
Hello, I don't know if something wrong with the above code, but today I'm facing 
![issue image](https://user-images.githubusercontent.com/114071494/191675757-69abb4a4-962d-499a-91c4-604a68861215.png) issue 

till yesterday it was a blank layout with no issue, I haven't changed anything

**Comment by bumbeishvili** [comment]
Hi, @emmaMinty12 

Unfortunately I don't have a time to test the code, treat it as a general direction and try to understand each part of it

**Comment by emmaMinty12** [comment]
I facing the same issue in every example with CSV data too, which is listed on the repo.

https://stackblitz.com/edit/web-platform-jyncb9

**Comment by bumbeishvili** [comment]
@dlgoodchild  can you link at least one example which does not work? I checked and it was working for me

**Comment by dlgoodchild** [comment]
@bumbeishvili sure...
I've just tried this one: https://stackblitz.com/edit/web-platform-thplyq?file=index.html

And this is what I see (I get exactly the same for all of them):
<img width="1901" alt="Org-Chart_-_V2_-_Layouts_-_Transition_to_v2_-_StackBlitz" src="https://user-images.githubusercontent.com/366030/203521465-8702dc3d-d697-4d9c-b5ed-bdfe6a554db0.png">

I'm using the very latest FireFox.

**Comment by bumbeishvili** [comment]
The same happens on my firefox, but they work in chrome. I am guessing it's something related to stackblitz

**Comment by muhammedsafeero** [comment]
> @emmaMinty12
> 
> so, first you have to convert it to flat data and then you can supply it to org chart.
> 
> ```js
> d3.json(`https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/redesignedChartLongData.json`).then(hierarchyData=>{
>  
> // Flatten data
> const flatDataNodes = d3.hierarchy(hierarchyData)
>   .descendants()
> 
> // Then we want to  add id & parentId to maintain hierarchy within the flat data
> flatDataNodes.forEach(d=>d.data.id = crypto.randomUUID()); // close enough id generation
> 
> // Add parent id
> flatDataNodes.forEach(d=>d.data.parentId = d.parent?.data?.id;)
> 
> //Then get original data
> const finalFlatData = flatDataNodes.map(d=>d.data);
> 
> // Then supply flat data to graph and that's it
>  chart = new d3.OrgChart()
>           .container('.chart-container')
>           .data(data) 
>           .render();
> 
> })
> ```
> 
> Haven't tested the code, written directly in Github editor

`var chart;
 
d3.json(https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/redesignedChartLongData.json).then(hierarchyData=>{
 
 // Flatten data
 const flatDataNodes = d3.hierarchy(hierarchyData)
   .descendants()
 
 // Then we want to  add id & parentId to maintain hierarchy within the flat data
 flatDataNodes.forEach(d=>d.data.id = crypto.randomUUID()); // close enough id generation
 
 // Add parent id
 flatDataNodes.forEach(d=>d.data.parentId = d.parent?.data?.id)
 
 //Then get original data
 const finalFlatData = flatDataNodes.map(d=>d.data);
 
 // Then supply flat data to graph and that's it
  chart = new d3.OrgChart()
           .container('.chart-container')
           .data(finalFlatData) 
           .render();
 
 });`

**Comment by muhammedsafeero** [comment]
var chart;
 
d3.json(https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/redesignedChartLongData.json).then(hierarchyData=>{
 
 // Flatten data
 const flatDataNodes = d3.hierarchy(hierarchyData)
   .descendants()
 
 // Then we want to  add id & parentId to maintain hierarchy within the flat data
 flatDataNodes.forEach(d=>d.data.id = crypto.randomUUID()); // close enough id generation
 
 // Add parent id
 flatDataNodes.forEach(d=>d.data.parentId = d.parent?.data?.id)
 
 //Then get original data
 const finalFlatData = flatDataNodes.map(d=>d.data);
 
 // Then supply flat data to graph and that's it
  chart = new d3.OrgChart()
           .container('.chart-container')
           .data(finalFlatData) 
           .render();
 
 });
