### ISSUE TITLE
direct subordinates with no children

### ISSUE THREAD

**Issue by chekyassine** [bumbeishvili/org-chart#158]
Hi, 
Is there a way to add direct subordinates with no children like example below ?  
![image](https://user-images.githubusercontent.com/5337918/179494332-6d33d76e-0be3-4f79-9fdc-b9c1c0e55e9e.png)
source : https://observablehq.com/@satgi/orgchart-demo
Many thanks

**Comment by chekyassine** [comment]
any direction ?

**Comment by bumbeishvili** [comment]
If direct subordinates do not have children, you could make them part of the parent's data. Then you could make those parent nodes bigger and generate custom HTML in a way, to take direct subordinate data into account

**Comment by chekyassine** [comment]
This could be a fix, but what i'm looking for is getting the layout in the picture above. Actually, the code in the link above also uses flextree (same as org-chart) to build this layout. 
I've looked inside org-chart code but i couldn't find a way to customize flextree.
Any ideas?
