### ISSUE TITLE
Connect to collapsed children only from the top

### ISSUE THREAD

**Issue by Danieliverant** [bumbeishvili/org-chart#160]
Can we change the behavior of siblings has connecting lines between them, as:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1301334/182408595-b0d755be-2a30-4024-985c-b8cadb530418.png">

To have lines only "on-top" of them, as same as:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/1301334/182408660-2eb06bff-a875-4e77-ad3a-eebdcdea1b2e.png">

Thanks in advance.

**Comment by bumbeishvili** [comment]
Not exactly sure if I got the question right.

Do you mean this kind of layout?

<img width="838" alt="image" src="https://user-images.githubusercontent.com/6873202/182594408-79b5748b-5dbd-4eac-aa8c-38d1a2324a35.png">

**Comment by Danieliverant** [comment]
> Not exactly sure if I got the question right.
> 
> Do you mean this kind of layout?
> 
> <img alt="image" width="838" src="https://user-images.githubusercontent.com/6873202/182594408-79b5748b-5dbd-4eac-aa8c-38d1a2324a35.png">

No I mean use the "compact" layout but not have the children connected through the middle but just a stack connected from the top

something like this:

![image](https://user-images.githubusercontent.com/1301334/182602463-ea447445-daa4-4d36-9550-f519417d01ab.png)

**Comment by bumbeishvili** [comment]
Ok, I understand.

You have the possibility to override the function, which generates links and supply your own.

https://github.com/bumbeishvili/org-chart/blob/3b7cc9d332d657ed5e710631abaad36dfc5ebe0f/src/d3-org-chart.js#L191

https://github.com/bumbeishvili/org-chart/blob/3b7cc9d332d657ed5e710631abaad36dfc5ebe0f/src/d3-org-chart.js#L1043

You can play with the current implementation here

https://observablehq.com/@bumbeishvili/curved-edges-compacty-vertical

Diagonal function receives three arguments (`source,target, middle`), each of them have `x,y` properties. They correspond source node and target node coordinates. Your end goal is to generate SVG shape `d` [path](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d)

**Comment by Danieliverant** [comment]
@bumbeishvili Thanks!
