### ISSUE TITLE
What does the tags column serve to do?

### ISSUE THREAD

**Issue by MageRoyal** [bumbeishvili/org-chart#161]
In the example data, there is a tags column. My data does not have this, but it has the same parentId to ID relationship where the CEO parentid is blank. The only thing that i can see is the tags column is missing that would prevent it from having the starting point. Is there a way to declare the CEO ID without adding in a column?

**Comment by bumbeishvili** [comment]
The only necessary columns are `id` and `parentId`. You can name & use other columns as you want.

That data which you referenced is quite old, I'd suggest using 

https://github.com/bumbeishvili/sample-data/blob/main/data-oracle.csv

This data for playing around instead

**Comment by MageRoyal** [comment]
Thank you! I will use that data to compare to my own. I'm just trying to troubleshoot why I keep getting in promise errors with my data.

I want to keep playing with it to see if I can figure it out!

**Comment by bumbeishvili** [comment]
I think, you should not be getting promise errors unless data is incorrectly formatted (when uploaded on Github, it should be visible as table)

**Comment by MageRoyal** [comment]
The issue was the sorting of the data. I corrected that! Is there a way to change the column names from id to ID and parentId to SuperID?

**Comment by bumbeishvili** [comment]
Yes, you can override `id` and `parentId` accessor functions

https://github.com/bumbeishvili/org-chart/blob/3b7cc9d332d657ed5e710631abaad36dfc5ebe0f/src/d3-org-chart.js#L43-L44

using 

```javascript
chart
  .id(d=>d.ID)
  .parentId(d=>d.SuperID)
```
