### ISSUE TITLE
Do you have or plan json support?

### ISSUE THREAD

**Issue by adrianaioanei94** [bumbeishvili/org-chart#162]
Hello,

Very interesting your project but why csv? You need to have those ids in order to know the connection between object.
Why not a imbricated json? Do you have support for something like this or do you plan to add ?
Thanks

**Comment by bumbeishvili** [comment]
https://github.com/bumbeishvili/org-chart/issues/157

**Comment by tdekoekkoek** [comment]
+1.  JSON is critical for me.  Love the product though

**Comment by bumbeishvili** [comment]
It already works with the JSON

I've added new examples involving several scenarios here

https://github.com/bumbeishvili/org-chart/tree/dev#features
