### ISSUE TITLE
I have trouble to set height of svg-chart-container

### ISSUE THREAD

**Issue by abides** [bumbeishvili/org-chart#165]
Hello Everyone,

I would like to use orgchart in angular 14 project. I'm having trouble to set height of the svg-chart-container.
I just want to change the width and height of the container on resize and update/render chart accordingly.

```
 @HostListener('window:resize', ['$event'])
    onResize(event: Event): any {
        const width = window.innerWidth-48;
        const height = window.innerHeight-362;
        //do something and set width and height of the container
        //this.chart... something...
        this.updateChart();
    }
```

This is the code where i can detect window resize in angular. There is no problem about the width, i can see its changing on resize depends on its container but height is always same and not changing.

![1](https://user-images.githubusercontent.com/726511/189918623-042fad09-3ae3-4c31-965a-4eebdd956d07.jpg)
![2](https://user-images.githubusercontent.com/726511/189918646-f6d48a7f-4d3d-4c2d-b2ff-cb908012906f.jpg)

Best regards.

**Comment by bumbeishvili** [comment]
Width is automatically set based on container width, height always stays fixed, but you have the possibility to override it
