### ISSUE TITLE
the image exported was incorrected when the scale param was setted to greater than 19

### ISSUE THREAD

**Issue by zhoufenfens** [bumbeishvili/org-chart#168]
**Describe the bug**
Hi, i found that when export an larger image by call the chart.exportImage, the exported image was broken, its size was zero,  
```
this.chart.exportImage({
  full: true,
  scale: 20,
});
```
this is the link   [https://web-platform-dr9pob.stackblitz.io](https://web-platform-dr9pob.stackblitz.io)
**To Reproduce**
1. Go to [test page](https://web-platform-dr9pob.stackblitz.io)
2. Click on 'export full img'
3. See error

**Expected behavior**
the image was correct

**Screenshots**

<img width="209" alt="image" src="https://user-images.githubusercontent.com/3303836/190358515-f64f4c3a-9abc-4bbe-ab82-33ef5a604245.png">

**Desktop (please complete the following information):**
 - OS: macos 10.15.7
 - Browser  chrome 
 - Version 105

**Additional context**
i also found that if the screen was narrow,  the exported image works fine,  if you open the link in a new window, the image was broken.

**Comment by bumbeishvili** [comment]
Yep, it's about how much browser can handle. 

In my trials, I think 2-3X is optimal enough  and it still would struggle for large screens

**Comment by zhoufenfens** [comment]
how about using the exportSvg ?  i found that the svg mode only support the "scale = 3"

**Comment by bumbeishvili** [comment]
For the SVG scale  parameter does not matter, since it is Vector and it does not lose quality when zoomed in
