### ISSUE TITLE
Trying to stop zooming

### ISSUE THREAD

**Issue by abides** [bumbeishvili/org-chart#169]
Hello,

I'm trying to stop zooming on scroll when mouse over item in the node which is overflow and need to be scrolled up/down. maybe even stop panning too for mobile when pointer on the same overflow object.

Any suggestion?
Best regards.

**Comment by bumbeishvili** [comment]
Not exactly sure how to approach this problem.

If you can modify the source code, then I'd check the event here and would see if I could get access to the source element. If yes, then would not allow zooming (easier to say than done, since it might need to play with d3 zoom parameters)

https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L1251

**Comment by abides** [comment]
maybe this can be the approach;
zoomDisabled = true on mouseenter on that specific object has entries bigger than x number and zoomDisabled=false on mouseleave then return; zoomed function if zoomDisabled. probably there is some protection needed for this approach, mouse leave can be missed easily, there should be timeout go back zoomDisabled=false in case of mouse outside of entered area without trigger mouse leave. I'm not sure what happens mobile on this approach. Maybe also click on that overflowed object can set zoomDisabled=true.

i will change the source when i have time for it, maybe it can be the good contribution. Also i made angular method calls from elements inside nodes (add node, delete node, update node) this can help someone else on angular too.

**Comment by bumbeishvili** [comment]
In the new, upcoming version, I am adding the possibility to create your own zoom & panning behavior, which will allow you to set additional state, which will help conditionally deciding when to block zoom events and when to pass


```javascript
chart.createZoom(() => {
    return d3.zoom().filter((e,d) => {
        if (['TR', 'TD', 'TH'].includes(e.srcElement.tagName)) {
            return false;
        }
        return true;
    })
})
```

Above code makes it possible to have both, scroll  inside node and scroll-based zoom outside of node

https://github.com/bumbeishvili/org-chart/assets/6873202/377afca3-81ff-4557-95be-06bcb0b6fcd8
