### ISSUE TITLE
Stacked nodes view

### ISSUE THREAD

**Issue by Vin-1991** [bumbeishvili/org-chart#17]
Hey David,
This chart is awesome and very flexible too. I'm trying to manipulate this chart as per my need but i'm little bit in dilemma when it comes to view of nodes they are all scatter on the screen and looks ugly and frustrating at times when there are lots of nodes under a parent. Could it be possible to make them stacked one on another. Though i have tried several hit and trial but unable to achieve. It would be very helpful if you can give some idea around this implementation.

Thanks for your valuable contribution.
![stacked_view](https://user-images.githubusercontent.com/15855698/79637005-5c7e9380-8199-11ea-93b1-c7714a601523.JPG)

**Comment by bumbeishvili** [comment]
I know what you mean @Bunny1991  

Everything comes down to assigning x,y coordinates to nodes, I did it once in [the private project](https://davidb.dev/images/projects/leadership-connect/preview.gif) (can't share code), and it was a pretty complex task, I don't remember the exact algorithm 

![Screen Shot 2020-04-18 at 20 57 33](https://user-images.githubusercontent.com/6873202/79644023-47186200-81b7-11ea-89b8-8e12e79fad4d.png)

I plan to add this compact layout in v2 version of org-chart, but it's a long time ahead before release and it will take good chunk of time too

Meantime, I will keep this open and will inform you once that will be implemented

**Comment by Bunny1991** [comment]
No worries david will track this feature. Many Thanks

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
