### ISSUE TITLE
Initial node push and addNode working differently

### ISSUE THREAD

**Issue by abides** [bumbeishvili/org-chart#170]
**Describe the bug**
Because of the different nature of initial value comparison and addNode value comparison if the id's of the records are numeric (integer) addNode complains about can't find the parentId in nodes.

**To Reproduce**
1. parse data with integer type of id and parentId values
2. Its working on initial render
3. try to add new node on runtime using addNode method with integer or string id and parentId values

**Expected behavior**
Initial node rendering and addNode method need to behave same nature.

**Additional context**
on addNode method convert to string on both comparison can fix the problem.
```
const nodeFound = attrs.allNodes.filter(({ data }) => attrs.nodeId(data).toString() === attrs.nodeId(obj).toString())[0];
const parentFound = attrs.allNodes.filter(({ data }) => attrs.nodeId(data).toString() === attrs.parentNodeId(obj).toString())[0];
```

**Comment by bumbeishvili** [comment]
Just for your information.

In the new upcoming v3 version this will be addressed (both will be converted to toString() before comparing to each other)

This will also happen for similar methods, so it should be more forgiving now
