### ISSUE TITLE
Odd behavior with multiple charts and selecting a node

### ISSUE THREAD

**Issue by GrubHubGitTub** [bumbeishvili/org-chart#171]
I have a project set up with NextJS. Everything is working as it should be until my node on click function. I'll try to explain below:

I display some info on a screen when clicking on a node. This works as it should. 

 I have a navbar above the orgchart that links to another chart. When going to the new orgchart through this link, it will display normally.

I then click a node on this new orgchart, however the orgchart will quickly re render and display the info from the node id in the first chart! This will happen in any order- whichever orgchart is first loaded will be the one that the second goes back to. 

I'm not sure what is causing this issue, any guidance would be appreciated.

**Comment by bumbeishvili** [comment]
Interesting, is it possible for you to provide a live example?

**Comment by GrubHubGitTub** [comment]
Here, I recorded my screen so you can better understand. Here's a gif https://imgur.com/kTWxudo

**Comment by bumbeishvili** [comment]
That's odd indeed, I was getting a same issue back then 2 years ago, but could not track down the bug.

Somehow these org chart states are mixed, but I don't know what causes it

**Comment by GrubHubGitTub** [comment]
Is there a way to rename the container/ chart class? Perhaps if they are different this wouldn't happen.

I've also noticed the bug goes away when I refresh the page, but then will happen again as soon as I go to the next one.

**Comment by GrubHubGitTub** [comment]
Just to give an update, it seems to happen with charts with the same parent link. So this issue happens with /1/chart1/ and /1/chart2, but goes away if it links to /2/chart3/.

**Comment by GrubHubGitTub** [comment]
Another update- this only happens locally. I hosted my app on Vercel and the issue is gone.

**Comment by bumbeishvili** [comment]
I suspect it might have to do something with the hot reloading. I think somehow old and new chart references are mixing which causes issues

**Comment by GrubHubGitTub** [comment]
Ok final update just to help anyone else who may be having this problem and stumble upon this. 

After another bug in my app I went searching on the Next.js repo, and came across this fix: 
https://github.com/vercel/next.js/issues/9992#issuecomment-910459956

All is fine now. Never was an issue with this package!

**Comment by bumbeishvili** [comment]
Interesting, thank you for linking it
