### ISSUE TITLE
Children connection are "hard" to read

### ISSUE THREAD

**Issue by xuanngo2001** [bumbeishvili/org-chart#172]
**Describe the bug**
See the screenshot below. The connection between Carlos and Sven make it hard to read the tree. It require extra thinking to know that Carlos and Sven are children of Leverling. Is it possible to have 2 direct connections from Leverling: 1 for Carlos and 1 for Sven.

**To Reproduce**
1. Go to futuristic example and expand all: https://web-platform-o5t1ha.stackblitz.io/

**Expected behavior**
See screenshot.

![image](https://user-images.githubusercontent.com/8182563/192006409-4e06109c-f7fd-4cb6-96b6-e8541f457af0.png)

**Comment by bumbeishvili** [comment]
@xuanngo2001 Just set `.compact(false)` and you'll get the org chart in your desired form
