### ISSUE TITLE
Is it possible to delete root on runtime?

### ISSUE THREAD

**Issue by abides** [bumbeishvili/org-chart#173]
Hello,

I can delete all nodes runtime but root node. It give "no root" error on console.

Any suggestion?
Best regards.

**Comment by marcellino-ornelas** [comment]
Not sure your use case but if your just trying to not show the root node you can probably just add a `display: none`?

**Comment by abides** [comment]
@marcellino-ornelas i'm using this for creating orgchart on runtime. So start with empty data, add node, delete node, edit node...etc. Initialization with empty data, there is no problem, after adding first node (which is root node) i'm not able to delete that node or basically i'm not able to clear all orgchart to start over.

Currently i just edit root node to replace it with another job description if i did any mistake but its not convenient. Clear all data and start over can be good option.

**Comment by marcellino-ornelas** [comment]
Ahhh got ya @abides , I tried playing around with this today but wasnt able to get it either

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-rxbg3h?file=index.js,OrgChart.js

^ was the closest I got but when you remove the root and add another one it shifts to left for some reason 🤔

**Comment by bumbeishvili** [comment]
It was not possible to pass empty data and clear the chart before, but from v3 it'll be possible.
