### ISSUE TITLE
Can we create the nodes only on right side?

### ISSUE THREAD

**Issue by raibove** [bumbeishvili/org-chart#177]
Thank you for creating this package and making it open source.

Currently, we have a layout in which child nodes are arranged both on the left and right sides, as shown in the image below
![left-right-org-chart](https://user-images.githubusercontent.com/44832446/194487931-fc44dea9-b58f-476c-a5e0-7927b6c59598.PNG)

Can we update the layout in such a way that only nodes are displayed on the right side?

![right-org-chart](https://user-images.githubusercontent.com/44832446/194488194-8defbcf7-51b2-4037-aef4-c9c2a15248b5.PNG)

In [this ](https://github.com/bumbeishvili/org-chart/issues/164) issue you mentioned that it is not possible to modify the layout in such a way, but what we want is somewhat different than this issue so I created a new issue.

Also, I had one more question - 
Can we stop/disable the collapse functionality?

**Comment by bumbeishvili** [comment]
I don't think that it will be possible without a significant rework.

> Also, I had one more question -
> Can we stop/disable the collapse functionality?

If you want to completely disable expand as well as collapse, you can just hide the root element of expand/collapse click area (you can find it in inspect element).

If you just want to stop disable but keep expand, then no, it won't be possible out of the box

**Comment by raibove** [comment]
> If you want to completely disable expand as well as collapse, you can just hide the root element of expand/collapse click area (you can find it in inspect element).

Yes, I wanted to disable the expand/collapse functionality and it worked. Thank You

I am closing this issue now.
