### ISSUE TITLE
French Text Support

### ISSUE THREAD

**Issue by Santoua3a** [bumbeishvili/org-chart#179]
Hi,

I'm having an issue with using the french language. 
The special characters as "é" or "è" are displayed with "?" as shown below in the screen shot

I want to know if there's a support for the french in the org or any solution to my problem.

Thanks.

![Capture d’écran 2022-10-14 123005](https://user-images.githubusercontent.com/41911035/195836676-4f5fc6e5-d871-4265-944b-fcc6c82d571b.png)

**Comment by bumbeishvili** [comment]
Can you provide a sample? you can just extend one of the stackblitz applications

**Comment by Santoua3a** [comment]
Here's a sample : 

updateChart(): void {
    if (!this.data) {
      return;
    }
    if (!this.chart) {
      return;
    }
    this.chart
      .container(this.chartContainer.nativeElement)
      .data(this.data)
      .rootMargin(100)
      .nodeWidth(d => 210)
      .nodeHeight(d => 160)
      .childrenMargin(d => 130)
      .compactMarginBetween(d => 75)
      .compactMarginPair(d => 80)
      .nodeContent(function (d, i, arr, state) {
        const colors = [
          '#CE202E',
          '#A11D27',
          '#BD7E16',
          '#96C62C',
          '#BD7E16',
          '#802F74',
        ];
        const color = colors[d.depth % colors.length];
        const imageDim = 80;
        const lightCircleDim = 95;
        const outsideCircleDim = 110;

        return `
            <div style="background-color:white; position:absolute;width:${d.width
          }px;height:${d.height}px;">
               <div style="background-color:${color};position:absolute;margin-top:-${outsideCircleDim / 2}px;margin-left:${d.width / 2 - outsideCircleDim / 2}px;border-radius:100px;width:${outsideCircleDim}px;height:${outsideCircleDim}px;"></div>
               <div style="background-color:#ffffff;position:absolute;margin-top:-${lightCircleDim / 2
          }px;margin-left:${d.width / 2 - lightCircleDim / 2}px;border-radius:100px;width:${lightCircleDim}px;height:${lightCircleDim}px;"></div>
               <img src=" ${d.data.imageUrl
          }" style="position:absolute;margin-top:-${imageDim / 2}px;margin-left:${d.width / 2 - imageDim / 2}px;border-radius:100px;width:${imageDim}px;height:${imageDim}px;" />
               <div class="card" style="top:${outsideCircleDim / 2 + 10
          }px;position:absolute;height:30px;width:${d.width}px;background-color:#3AB6E3;">
                  <div style="background-color:${color};height:34px;text-align:center;padding-top:10px;color:#ffffff;font-weight:bold;font-size:16px">
                      ${d.data.name} 
                  </div>
                  <div style="height:56px;text-align:center;padding-top:10px;padding-bottom:20px;color:#424142;font-size:16px">
                      <div style="margin-bottom:20px">${d.data.positionName}<div>
                  </div>
               </div>
           </div>
`;
      })
      .svgWidth(500)
      .initialZoom(0.6)
      .onNodeClick(d => console.log(d + ' node clicked'))
      .render();
  }

-----------------------------------------------------------------------------------------------

I tried to add encoding mode UTF-8 but no chance in that

**Comment by schindld** [comment]
How are you making your data file? This library will handle data in utf-8 with or without a BOM. Excel needs the BOM to display the accented characters properly though. If you open your data file in and editor like VS Code or Notepad++, you will be able to see the encoding, and change it to utf-8 with bom.

**Comment by Santoua3a** [comment]
> How are you making your data file? This library will handle data in utf-8 with or without a BOM. Excel needs the BOM to display the accented characters properly though. If you open your data file in and editor like VS Code or Notepad++, you will be able to see the encoding, and change it to utf-8 with bom.

The data is generated with a Spring Boot application using OpenCSV dependency. 
I can show you the code that i used to generate the data in a CSV file. 


Service : 
`
    @Override
    public void writeDataToCsvUsingStringArrayOrg(PrintWriter writer, List<OrgCollaboratorDTO> collaborators) {
        String[] CSV_HEADER = { "name", "imageUrl", "area", "profileUrl", "office", "tags", "isLoggedUser", "positionName", "id", "parentId", "size" };
        try (
                CSVWriter csvWriter = new CSVWriter(writer,
                        CSVWriter.DEFAULT_SEPARATOR,
                        CSVWriter.DEFAULT_ESCAPE_CHARACTER,
                        CSVWriter.DEFAULT_LINE_END);
        ){
            csvWriter.writeNext(CSV_HEADER);

            for(OrgCollaboratorDTO collaborator : collaborators) {
                csvWriter.writeNext(getCollaboratorsOrg(collaborator));
            }

            System.out.println("Write CSV using CSVWriter successfully!");
        }catch (Exception e) {
            System.out.println("Writing CSV error!");
            e.printStackTrace();
        }
    }

    private String[] getCollaboratorsOrg(OrgCollaboratorDTO collaborator){
        List<String> line = new ArrayList<String>();
        line.add(collaborator.getName());
        if(StringUtils.isEmpty(collaborator.getImageUrl()) || StringUtils.isBlank(collaborator.getImageUrl())) {
            line.add("https://raw.githubusercontent.com/bumbeishvili/Assets/master/Projects/D3/Organization%20Chart/general.jpg");
        } else {
            line.add(collaborator.getImageUrl());
        }
        line.add(collaborator.getArea());
        line.add(collaborator.getProfileUrl());
        line.add(collaborator.getOffice());
        line.add(collaborator.getTags());
        line.add(collaborator.getIsLoggedUser());
        line.add(collaborator.getPositionName());
        line.add(StringUtils.substring(collaborator.getId(), 0, collaborator.getId().length() - 13));
        if(StringUtils.isNotBlank(collaborator.getParentId()) && StringUtils.isNotEmpty(collaborator.getParentId())) {
            line.add(StringUtils.substring(collaborator.getParentId(), 0, collaborator.getParentId().length() - 13));
        } else {
            line.add(collaborator.getParentId());
        }
        line.add(collaborator.getSize());
        return line.toArray(new String[0]);
    }
`

Controller : 
`
       @GetMapping("/export-csv/org")
        public void exportCSVOrg(HttpServletResponse response) throws IOException {
        DateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        String currentDateTime = dateFormatter.format(new Date());

        String headerKey = "Content-Disposition";
        String headerValue = "attachment; filename=collaborators_" + currentDateTime + ".csv";
        response.setHeader(headerKey, headerValue);
        response.setContentType("text/csv");

        List<OrgCollaboratorDTO> collaborators = collaboratorService.orgCollaboratorsList();

        collaboratorService.writeDataToCsvUsingStringArrayOrg(response.getWriter(), collaborators);
   `

**Comment by bumbeishvili** [comment]
@Santoua3a  if CSV data has issues, you can just feed the JSON data instead, end result will be exactly the same as long as data structure matches
