### ISSUE TITLE
Focus on a node and position it at center

### ISSUE THREAD

**Issue by behiunforgiven** [bumbeishvili/org-chart#18]
Hello
How can I focus on a node by its Id and put it on the center of screen.
Actually I want to search a node via its Id and somehow highlight it.

**Comment by bumbeishvili** [comment]
That's not yet implemented, but it in the coming features list (won't be public at least for several months)

You can track it here - #14

**Comment by behiunforgiven** [comment]
so can you guide me to do it myself?
I can expand it by "setExpanded" method. but I'm not able to focus on selected Item.

**Comment by bumbeishvili** [comment]
Not sure how to do it yet

Maybe this helps - https://jsfiddle.net/Tokker/mwm1sxhh/21/

Or just google `d3 center tree (graph) node` and try several ways

**Comment by behiunforgiven** [comment]
Any good news about search feature?

**Comment by bumbeishvili** [comment]
@behiunforgiven no news. 

Basically there would not be any news until I will have a freelance project involving an org chart. Then I will have time and chance to work on this feature

**Comment by kunal0137** [comment]
I see the fixed in dev label was added, but I'm not sure I see a public dev branch etc? any info on this?

**Comment by bumbeishvili** [comment]
@kunal0137 there is a pinned issue where the dev version is linked 

I will start working on the most common bugs and some important features in 2-3 weeks and they probably it will get merged in 4-5 weeks

**Comment by bumbeishvili** [comment]
In the dev version (development branch) centering and highlighting is already implemented

https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L1006


Here is a sneak how it works/behaves


https://user-images.githubusercontent.com/6873202/126049243-0f3acdea-1414-4757-8c1f-94d5c86b5d9d.mp4

**Comment by rmarin-ro** [comment]
Hi,

I'm also looking forward to these features.
Any update on when they will get merged into production?
Thank you very much!

**Comment by bumbeishvili** [comment]
It will get merged into the master branch (and NPM updated) within the next 10 days

**Comment by rmarin-ro** [comment]
Great, thank you so much! Really appreciate the hard work!

**Comment by bumbeishvili** [comment]
In the new version, automatic centering of an active node is also implemented

https://user-images.githubusercontent.com/6873202/128687794-c53f9e2a-157a-4364-875c-952df85635f0.mp4

**Comment by bumbeishvili** [comment]
You can check the [example of the new version]( https://stackblitz.com/edit/web-platform-jyncb9) from now on. I expect to publish a new version by the next week

https://user-images.githubusercontent.com/6873202/128749314-c58a20fb-f863-4dc0-8e65-78f94445d929.mp4

**Comment by rmarin-ro** [comment]
Looking good! 😃

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)

**Comment by Sanjayashok2512** [comment]
"When I clicked on the children, I need to expand them, and the specific child that I clicked on should be highlighted."
