### ISSUE TITLE
Implement multi  button support

### ISSUE THREAD

**Issue by joelcoxokc** [bumbeishvili/org-chart#180]
**Is your feature request related to a problem? Please describe.**

The problem I have is that I need to have multiple actions on each node. like... Add child node, or remove current node. 

Implement the ability to add multiple buttons, that simply allow you to register click events with each button... not including the expand button. 

**Describe the solution you'd like**
If we could simply pass an array of actions with a selector that will appear in the node content, and a click callback that would be amazing. 

for example:

```js
nodeContent(() => `
   <button class="my-action">Click Me</button>
`)
.actions([
  {
    selector: '.my-action',
    onClick: (event, node, state) => {
        // Do something amazing
    }
  }
])
```

**Describe alternatives you've considered**
Ive considered implementing this myself, but I have not found the time quite yet. 

**Additional context**

Here is an example of how I need to have actions inside the node content.

<img width="313" alt="Screen Shot 2022-10-18 at 6 06 19 PM" src="https://user-images.githubusercontent.com/4668188/196561457-e4a14eb0-011f-4da8-a8cb-62ee8b601744.png">

---

**Comment by joelcoxokc** [comment]
@bumbeishvili  Is it ok to add an event listener inside the update?

**Comment by joelcoxokc** [comment]
Another possible solution, is to pass the event to the `onNodeClick` callback. 
This is what I am currently doing to make this work for our company https://github.com/TaEthni/org-chart/blob/master/src/d3-org-chart.js#L812

I am using the click event to identify which element was actually clicked

**Comment by bumbeishvili** [comment]
> Is it ok to add an event listener inside the update? I always thought you had to add listeners to the nodeEnter

So, html is reRendered on every update, so it's necessary to do it in update.  In practice I did not had any issues with it, although in theory it's not efficient at all.

> I am using the click event to identify which element was actually clicked

Haven't thought about it, I guess this works too, but only for click events. In my useCase, menu was triggered on hover inside node, so I had attach event in `nodeUpdate `  method.
