### ISSUE TITLE
chart.setExpanded method not working as expected

### ISSUE THREAD

**Issue by mrinmays** [bumbeishvili/org-chart#184]
**Describe the bug**
`chart.setExpanded(<nodeid>)` method is not working as expected

**To Reproduce**
1. Go to https://stackblitz.com/edit/web-platform-7zcadz?file=index.html
2. Click on Collapse Button and you'll see nothing happens.
3. However, `chart.collapseAll()` and `chart.expandAll()` seem to work fine. 

**Expected behavior**
Clicking on `Collapse` button should collapse the tree to root node (O-6066). or,
after clicking on `Collapse All` button, clicking on `Expand` button should expand the tree for root node.

**Screenshots**
<img width="455" alt="image" src="https://user-images.githubusercontent.com/104633149/197053719-dd3de1d6-800c-4072-b52c-a19363fa63cc.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 106.0.5249.119

**Comment by devmrin** [comment]
Hey @bumbeishvili, huge fan of this library! 🙌
Wanted to know if this issue looks like a quick fix or something that would take some time?

Thanks

**Comment by bumbeishvili** [comment]
Hi, it's probably a quick fix (not yet convinced that it's a bug actually, since similar action was working in examples) 

Although currently I don't have a time to check it out and don't know exactly when I will be able to

**Comment by kodelio** [comment]
Hi, I have the same issue, although it's working on the example. It could be related to the data ?

**Comment by bumbeishvili** [comment]
I think I figured it out. 

In the past, there were issues when trying to expand & collapse a root node, since by default root and its children were expanded.

After some feedback, I've introduced a new property called `expandLevel` which by default is set to 1 , which means initially chart should be be expanded at first level (root and it's children). If you want to only open a root node, you can set this `expandLevel` to 0;

This `expandLevel` property determines whether to expand & collapse a root node or not. 

So, when we want to expand & collapse a root node, we also have to manipulate above property.

So, for collapsing a root node use:
```
chart.expandLevel(0).setExpanded("O-6066",false).render()
```

For expanding a root node use:
```javascript
chart.expandLevel(1).setExpanded("O-6066").render()
```

Here is an updated Stackblitz code

https://stackblitz.com/edit/web-platform-phvvtg?file=index.html

**Comment by mrinmays** [comment]
Hi @bumbeishvili ,
This issue isn't restricted to root node.
Even when I expand `O-6067` (first child of root to the left) and try to collapse it using only `chart.setExpanded("O-6067",false).render()` - it doesn't work.

Does this mean, I'll always have to first figure out which level a certain node is in, and then pass that level as -
`chart.expandLevel(<calculatedLevel>).setExpanded(<nodeID>).render()` 
to make it work?

**Comment by bumbeishvili** [comment]
I think you are right, issue is more complex than I was expecting.

When expanding a node, its children will get _expanded flag set to `true`. And when collapsing a node, only that node will get a `_expanded=false` attribute set, but we need to set `_expanded=false` to all of its children.


This is indeed a bug. 

For the workaround, I think it's possible to use

`chart.setExpansionFlagToChildren(node,false)` , so collapse function becomes following:


```javascript

      function collapse(id) {
        const state = chart.getChartState();
        const allNodes = state.allNodes;
        const node = allNodes.find((d) => d.id == id);
        node.data._expanded = false;
        chart.setExpansionFlagToChildren(node, false);
        chart.render();
      }
```


Updated stackblitz:

https://stackblitz.com/edit/web-platform-xt2ba7?file=index.html

**Comment by mrinmays** [comment]
Whilst this definitely works for collapse,
how would you propose a solution for expand?

the straight forward -
```js
function expand(id) {
    const state = chart.getChartState();
    const allNodes = state.allNodes;
    const node = allNodes.find((d) => d.id == id);
    node.data._expanded = true;
    chart.setExpansionFlagToChildren(node, false); 
    chart.render();
}
``` 

doesn't seem to work.

**Comment by bumbeishvili** [comment]
Can you outline what is the issue with expand? For me it seems to work as intended (except for the root node).

Currently expanding flag means that that particular node will become visible. If you want to expand it's children, you have to set expanded flag to one of it's children.

I am realising that it might be a little misleading and instead of _expanded, flag should be called _visible or something. I will think about of improving it

**Comment by mrinmays** [comment]
Ohh! I see now what the confusion might be.

my mental model is -  
<img width="711" alt="image" src="https://user-images.githubusercontent.com/104633149/198322839-fe9698d1-cc3e-4d7d-b1d6-8ccaadb3f35e.png">

So, `chart.setExpanded(nodeID)` -> would expand and show it's children
and `chart.setExpanded(nodeID, false)` -> would collapse it's expanded children.

**Comment by mrinmays** [comment]
Thanks, for clearing that up.

For the time being,
how would you recommend programmatically showing children of certain node (say `O-6067`)?

`chart.setExpanded('O-6071')`  doesn't seem to work.

stackblitz link - https://stackblitz.com/edit/web-platform-kr3hwe?file=index.html

**Comment by mrinmays** [comment]
That was my bad. 

Understood! 
This solves all my queries for now.

Thank you once again.

**Comment by bumbeishvili** [comment]
Just informing you about possible changes in org chart v3 which also concerns setExpanded method.

From now on `setExpanded(nodeId,false)` will actually collapse the node, even when it's expanded by the user.

In the background, it will just set `_expanded` flag to all siblings and descendants (before it would set that flag only to the node itself, but if siblings also had this flag, rerender would not collapse this node).

Also improved collapsing position behavior. Now collapsed nodes always go to direct parent position (before, they'd go to root)
