### ISSUE TITLE
nodes in one row, or how can manage the custom col elements like(2,3,6) in one row 

### ISSUE THREAD

**Issue by DSemenenko** [bumbeishvili/org-chart#186]

**Comment by bumbeishvili** [comment]
Hi, can you be more specific?

**Comment by bumbeishvili** [comment]
just pass `chart.compact(false)` and it will be horizontal

**Comment by DSemenenko** [comment]
it was not working for me but
this code is working properly chart.compact(!!(compact++%2)).render().fit(). 

what about groups?  
is it possible to limit the user in row and assign them to group? 
bcs for exmple I have 100 team member in one group so it will be a lot if in one row. 
I want make it like 4 column.

**Comment by bumbeishvili** [comment]
No, it's not possible. We can only have 2 columns in compact view

**Comment by kanth609** [comment]
@fabianhofer8, you can provide **scale** (as highlighted in below screenshot) option by increasing it based on number of nodes. Note that if you increase the scale value, the size of PDF will also increases.
<img width="566" alt="image" src="https://github.com/user-attachments/assets/d30745c9-bc05-4483-b412-8e9252a53525">

**Comment by fabianhofer8** [comment]
Hi, 
thanks for the quick response @kanth609! However I always get this error when I want to export it as a pdf...
Feels like I have to stick around with the SVG export.

![Screenshot 2024-10-14 105831](https://github.com/user-attachments/assets/7036f9bf-7707-42d7-8ea8-2d560bccdb70)

![Screenshot 2024-10-14 105752](https://github.com/user-attachments/assets/634d87d9-f40a-4ecb-a0db-03743c2835ab)

**Comment by kanth609** [comment]
@fabianhofer8 can you add all the options shown in the screenshot and then try. If you still get the error i would recommend you to google it as I'm not aware of this issue
