### ISSUE TITLE
Using Angular Material for the nodeContent? 

### ISSUE THREAD

**Issue by mike818148** [bumbeishvili/org-chart#190]
Hello, 

I am using typescript for the development. And I am wondering can we use Angular Material (or other directives, components) within the nodeContent? If yes, may you share some example for me as a starting point. 

Thanks and Regards,
Mike

**Comment by bumbeishvili** [comment]
Hi , I remember one of the issues having the same question roughly

**Comment by bumbeishvili** [comment]
Here they are #94 and #131

**Comment by mike818148** [comment]
Got it thanks. I will look into it!
