### ISSUE TITLE
Can I implement a hybrid organization chart?

### ISSUE THREAD

**Issue by EzequielTarraga** [bumbeishvili/org-chart#191]
Hello there! firts of all thanks for the hard work on this library.
I have this org allready
![Captura34](https://user-images.githubusercontent.com/42591869/199235264-cadba403-a3d2-4c0a-9aef-b94e6115d16a.PNG)
it's possible to get something like this?
![organigrama](https://user-images.githubusercontent.com/42591869/199268912-32c58660-63fb-409c-b0f9-0cde33935eae.png)
1. The staff, at the side of the line.
2. The hybrid distribution as seen in the example
Again thanks for the hard work
Cheers

**Comment by bumbeishvili** [comment]
Theoretically yes, but it will be basically changing the core of org chart library so, no
