### ISSUE TITLE
Error CORS when call method exportImg

### ISSUE THREAD

**Issue by mtdat15** [bumbeishvili/org-chart#193]
**Describe the bug**
I have img tag with src url from s3 and when i click exportImg this function can not working.
[Link image s3](https://ywqtj-wq78w-public.s3.ap-southeast-1.amazonaws.com/34/avatar/07173dee-1b9d-4fa7-a9d9-d5e3cd991415_134)

In nodeContent:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/111970751/199674560-ffddab5a-b20d-49a9-a7de-17161d82aead.png">

Error CORS when call exportImg
![image](https://user-images.githubusercontent.com/111970751/199674826-62f4656e-bfef-4fe5-ab75-e66f16432423.png)

**Expected behavior**
method exportImg working and export new image

**Comment by bumbeishvili** [comment]
When exporting, org-chart tries to convert images in bas64 string, to do that it needs to access and download images. So, the URL which you specify for images has to be accessible via CORS.


As a workaround, maybe try base64 image URLs instead. Not exactly sure if it will work though. Let me know if it does
