### ISSUE TITLE
Ability to add labels to lines

### ISSUE THREAD

**Issue by shanbady** [bumbeishvili/org-chart#195]
I was wondering if the ability to add labels to paths is planned for a future release. If not I'm wonderingf how to go about implementing it myself.

What I'd like is for me to be able to click on a line connecting two people and add a label to it. the result should look something like the following:
![graph (5)](https://user-images.githubusercontent.com/196425/199829919-d4bbf448-b69b-4bea-b55e-b70d802f8e93.png)

**Comment by bumbeishvili** [comment]
Theoretically, it's possible to place an additional element in `nodeUpdate` handler.

Inside it you have an access to `this`, from which you can get the parent containers and place your [g,rect,text] elements accordingly (you also have an access to coordinates of current and parent nodes, which will make it easy to place the above element at correct location).

Not sure how well it go with animation/transition though.

What I mentioned above is theoretical, I am not sure if it will be possible. Please comment it there if the attempt will be successfull

**Comment by shanbady** [comment]
I got it to function as needed by introducing a 'nodeType' property and creating a "label" node type. not clean or optimal but gets the job done for my purposes and animates properly
<img width="609" alt="Screen Shot 2022-11-04 at 1 24 54 PM" src="https://user-images.githubusercontent.com/196425/200038121-5544b8eb-efa2-4be8-8687-cb33dafac42c.png">
