### ISSUE TITLE
Disabling dragging

### ISSUE THREAD

**Issue by zakb27** [bumbeishvili/org-chart#196]
Hi I was wondering how I could go about disabling the ability to drag the chart around?

**Comment by bumbeishvili** [comment]
#52 might help you

**Comment by zakb27** [comment]
Hi the link that you provided in that question does not point to the line that was originally linked anymore I think, also I am trying to still have  the nodes be clickable so I can not disable pointer events.

**Comment by zakb27** [comment]
Works, thank you very much.
