### ISSUE TITLE
Different compact modes at once inside chart?

### ISSUE THREAD

**Issue by mrinmays** [bumbeishvili/org-chart#197]
Hi @bumbeishvili, so I was wondering, would it be possible to have some children like this - 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/104633149/200115919-b77b0ba8-1f6d-4ab6-9c35-c61bdfea7969.png">

whilst others like this - 
<img width="767" alt="image" src="https://user-images.githubusercontent.com/104633149/200115976-ec03264a-3b92-4850-96f3-7a96d8f6c6d4.png">

This is because `compact:false` help us fill the screen horizontally, but sometimes there are too many children of a given node where it makes more sense to display them in a `compact:true` fashion.

Awaiting your thoughts. 
I want to know where should I look to handle logic for something like this?

Thanks.

**Comment by bumbeishvili** [comment]
It's not possible , in my mind it's not an easy challenge and can't advice you well
