### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by huyongtao-cmd** [bumbeishvili/org-chart#198]
**Describe the bug**
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/71239740/200322462-9dfa2b8a-f5bb-409a-9657-77853e6433c5.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bumbeishvili** [comment]
Closing, since it's not clear at all
