### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by huyongtao-cmd** [bumbeishvili/org-chart#199]
**Describe the bug**
创建OrgChart实例会有警告，不能正常创建实例；d3引入也会报错，这是什么原因呢？
<img width="878" alt="image" src="https://user-images.githubusercontent.com/71239740/200336290-838600db-7c3e-4401-8c18-c77457bf6b05.png">
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/71239740/200336291-bfcb1979-5c46-435f-8aef-3c7a358e6aed.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrinmays** [comment]
Hi @huyongtao-cmd , sorry I'm seeing this a bit late, will leave a fix for someone visiting in the future.

On the top, `chart` declaration can  be updated as follows.
```js
const chart = useRef(null);
```

and inside the `useLayoutEffect` (+ everywhere else), usage would be updated to -
```js
 if (!chart.current) {
    chart.current = new ChartRenderer();
}
```
