### ISSUE TITLE
Changing the orientation of chart

### ISSUE THREAD

**Issue by SRINIVASREDDYPV** [bumbeishvili/org-chart#20]
is it possible to change the orientation of chart ?
We want left to right instead top to bottom.

**Comment by bumbeishvili** [comment]
No, it is not possible currently 

It is planned in v2 release though 

#14

**Comment by Lokesh2096** [comment]
Is it fixed coz it's given on your main git page that horizontal layout is possible but i did not found anything on it in documentation

**Comment by bumbeishvili** [comment]
Check the dev version in pinned issue

**Comment by Lokesh2096** [comment]
How to use it in angular is there any npm for dev version?

**Comment by bumbeishvili** [comment]
Nope, there is not any npm for the dev version (thinking about it, no promises), I guess you have to include it as a normal JS class in your project (It's a single class) and use it as if it was loaded from npm

**Comment by Lokesh2096** [comment]
Thankyou sir for Quick reply

**Comment by bumbeishvili** [comment]
In the new, dev version (development branch),4 layout types are implemented which can be changed at runtime

The layout can be set using

```javascript
chart.layout('left')
chart.layout('top')
chart.layout('right')
chart.layout('bottom')
```

https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L64


https://user-images.githubusercontent.com/6873202/126049326-a4b49ae4-f5ca-4a28-9710-92675c78ace1.mp4

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
