### ISSUE TITLE
Is override link geneneration function available?

### ISSUE THREAD

**Issue by leeyw19837** [bumbeishvili/org-chart#202]
> In the new, upcoming version, we will have the possibility to override entire link generation function algorithm, so this change will be possible without touching the core source code

Is this new ability of overriding entire link generation function algorithm available in version 2.6.0? As I tested and overrided the linkGroupArc attribute with d3.curveStep but not working.
![image](https://user-images.githubusercontent.com/15241031/200534212-5688feb7-46ff-495c-abd4-71eec3cdb8ce.png)

_Originally posted by @leeyw19837 in https://github.com/bumbeishvili/org-chart/issues/167#issuecomment-1306938070_

**Comment by bumbeishvili** [comment]
No, it is not at this point
