### ISSUE TITLE
Simple way to expand level?

### ISSUE THREAD

**Issue by joelcoxokc** [bumbeishvili/org-chart#204]
Before submitting an issue, please make sure to check whether the similar question was asked before. 
You can search for it here - https://github.com/bumbeishvili/d3-organization-chart/issues

Hey there, Ive done some navigating through the code, and I am trying to find an easy way to expand to a certain level without doing too much iteration. 

Basically on load, I would like to expand the the 3rd level. Is there a simple way to do this?

**Comment by bumbeishvili** [comment]
You can either try to set

```javascript
chart.expandLevel(3)
```

Or manually set _expanded to your data at the third level.  (I think you can invoke `chart.data()` to receive hierarchy data and it has necessary properties so you can avoid much of the calculations required for calculating hierarchy)

**Comment by edgarconrado** [comment]
The `chart.expandLevel(3)` does nor works for me, Interestingly it only works at low levels `chart.expandLevel(0)` or `chart.expandLevel(1)` Levels above 2 does not work, But, as you say, I setter manually the property  _expanded according with the level that I need it and works, I created a function to do that:

```
 expandByLevel(level: number) {
  
    const { allNodes } = this.chart.getChartState();
    allNodes.forEach((d: any) => {
      d.depth <= level ? d.data._expanded = true : d.data._expanded = false;
    });
  }
```

**Comment by bumbeishvili** [comment]
expandLevel is buggy at this point

**Comment by bumbeishvili** [comment]
I am updating the expand-level functionality.

From now on you. can configure the depth at which the org chart will open 

```javascript
chart.initialExpandLevel(0) // Only root node will open

chart.initialExpandLevel(1) // Default behavior, root and it's children will be expanded

chart.initialExpandLevel(2) // All nodes with depth 2 will be expanded
```
