### ISSUE TITLE
How can i group nodes by category?

### ISSUE THREAD

**Issue by adrianlemma** [bumbeishvili/org-chart#205]
I am trying to generate an organization chart that displays data by category. I need to display all nodes with the same category at the same height, but I can't generate the background or move the nodes to the desired height. Is there any way of doing this?
(I attach an image as an example)
Thank you!

![Exmple](https://user-images.githubusercontent.com/74475967/200928687-8e13dd56-2bc0-495e-b5f2-e1c2047c16a6.png)

**Comment by bumbeishvili** [comment]
You might want set set

```javascript
chart.compact(false)
```

**Comment by adrianlemma** [comment]
Thanks @bumbeishvili, I tried this, but with "chart.compact(false)" it only shows the nodes at the same height according to their parent... But if there is a parent node that has two children with different categories, they will be shown at the same height.
I attach an image that explains better, keep in mind that "Assistant 1" should be at the same height as "Assistant 2" but since it has the same father as "Director" and "Dep. Boss" it is shown at the same height than these.

![200928687-8e13dd56-2bc0-495e-b5f2-e1c2047c16a6](https://user-images.githubusercontent.com/74475967/201117061-1f716556-afbb-4fa6-8d41-a3784dd572ad.png)

**Comment by adrianlemma** [comment]
Ok, thanks for your prompt response.
Cheers!

**Comment by adrianlemma** [comment]
Ok, thanks for your prompt response.
Cheers!
