### ISSUE TITLE
How to expand / collapse node dynamically?

### ISSUE THREAD

**Issue by hy-net** [bumbeishvili/org-chart#206]
var node = d3.select("#" + d); // d = id

How can I **expand** or **collapse** this specific node without having the user to click on the node button?

    chart.expand(node); // not working
    chart.setExpanded(d); // not working

And if possible, check the state whether it is expanded or collapsed later

**Comment by bumbeishvili** [comment]
You need to rerender the graph after invoking `setExpanded` method. Check example how it is done here

https://stackblitz.com/edit/web-platform-o5t1ha

**Comment by hy-net** [comment]
I don't know why it doesn't work for me. I need to change the ``setExpanded`` function, to set the child property as well.

    node._children.forEach((ch) =>  ch.data._expanded = expandedFlag);

Otherwise it doesn't work. Or is it because I am using a very old version?

    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-org-chart@2"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-flextree@2.1.2/build/d3-flextree.js"></script>

**Comment by bumbeishvili** [comment]
I don't know, if you can provide an online example, I could look on it

**Comment by bumbeishvili** [comment]
1. Share the screenshot 
2. You can listen to node click and then invoke expand for the children manually

**Comment by dmytro-machulskyi** [comment]
Here is screenshot. Also I clicked some buttons and notice that there is some errors. 
<img width="1673" alt="Screenshot 2023-01-25 at 11 20 03" src="https://user-images.githubusercontent.com/18047604/214525257-b03527b8-2268-4b2d-89f9-0f26a694da6a.png">

**Comment by bumbeishvili** [comment]
Thank you for flagging this

There is a type 

`neightbourMargin` vs  `neighbourMargin` , I fixed it but it should have been published, looks like it is loading latest version where this typo is fixed and erroring old version. I pinned d3-org-chart to 2.6.0 and it works now

**Comment by dmytro-machulskyi** [comment]
Perfect, now works! Thank you for quick reply!

**Comment by bumbeishvili** [comment]
2. Yes, find all children and set expanded flag and rerender the graph

**Comment by yudhi115** [comment]
> I don't know why it doesn't work for me. I need to change the `setExpanded` function, to set the child property as well.
> 
> ```
> node._children.forEach((ch) =>  ch.data._expanded = expandedFlag);
> ```
> 
> Otherwise it doesn't work. Or is it because I am using a very old version?
> 
> ```
> <script src="https://d3js.org/d3.v7.min.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/d3-org-chart@2"></script>
> <script src="https://cdn.jsdelivr.net/npm/d3-flextree@2.1.2/build/d3-flextree.js"></script>
> ```
replace node._children with node.children, then works
node.children.forEach((ch) =>  ch.data._expanded = true);
