### ISSUE TITLE
Best way to embed for iOS

### ISSUE THREAD

**Issue by aslattum-addepar** [bumbeishvili/org-chart#209]
I'm interested in using this for an implementation of an org chart on a native iOS application (written primarily in Swift).

What is the best recommended path forward for embedding in iOS? A couple options would be:
- [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview)
- [JavaScriptCore](https://developer.apple.com/documentation/javascriptcore)
- Embed as an SVG

**Comment by bumbeishvili** [comment]
I'd go with webView. Have no idea what other two are

**Comment by aslattum-addepar** [comment]
@bumbeishvili cool that's what I was thinking. Just for clarity:
- JavaScriptCore allows you to execute Javascript as code within swift so you would likely bundle a JS file in the app and then load it and run functions
- SVG.. basically create an SVG from the output of org-chart and then show it
