### ISSUE TITLE
Is it possible to manage the child card on 4 column?

### ISSUE THREAD

**Issue by adupl** [bumbeishvili/org-chart#210]
Now the library organize the card under the "father" in 2 column before expanding them, like in the example below.

![image](https://user-images.githubusercontent.com/42604725/202170924-f8f609ee-45ad-49c8-b1f1-b353a87b0243.png)

is it possible to configure the library to automatically organize the "child cards" in 4 column, like for example if there are 20 "child cards" i need to display them in 4 column of 4 cards?

**Comment by bumbeishvili** [comment]
No, it's not possible
