### ISSUE TITLE
Zoom chart or horizontal scroll if overflow

### ISSUE THREAD

**Issue by kodelio** [bumbeishvili/org-chart#212]
Hello,

Is it possible to automatically zoom out to avoid overflow ? Or make the chart scrollable horizontally with a scroll bar ? Here's my case, when screen is small and there are many nodes :

<img width="1366" alt="CleanShot 2022-11-23 at 20 41 29@2x" src="https://user-images.githubusercontent.com/9209206/203633206-cccc17e8-f6ae-40dd-ae74-73030d80bb7e.png">

I have disabled any moving or zooming because I don't want to let user move chart, I just want to show it entirely

`this.chartReference.getChartState().svg.on('wheel.zoom', null)
      this.chartReference.getChartState().svg.on('touchstart.zoom', null)
      this.chartReference.getChartState().svg.on('touchmove.zoom', null)
      this.chartReference.getChartState().svg.on('touchend.zoom', null)
      this.chartReference.getChartState().svg.on('mousedown.zoom', null)`

Thanks

**Comment by kodelio** [comment]
Using another div as a container with a bigger width than the svg and using `overflow-x: scroll` is enough

**Comment by bumbeishvili** [comment]
BTW, `chart.fit()` could also come in handy
