### ISSUE TITLE
Is there a way to prevent or control the movement of the chart when a node is expanded?

### ISSUE THREAD

**Issue by tdekoekkoek** [bumbeishvili/org-chart#214]
Currently when you click on a node, the chart repositions itself to the left lower portion of the page, often obscuring some of the child nodes.  I'd like to keep it in the center of the area and give it the most real estate to be able to display the open nodes.

**Comment by bumbeishvili** [comment]
@tdekoekkoek  it automatically repositions itself to the active node (last expanded children or last collapsed)

If you want to disable this behavior

```javascript
chart.setActiveNodeCentered(false)
```

Check the behavior here

https://stackblitz.com/edit/js-mc1rt4?file=index.html
