### ISSUE TITLE
Bug found with Sky chart.

### ISSUE THREAD

**Issue by twillisCFB** [bumbeishvili/org-chart#215]
**Describe the bug**
Under specific conditions the joining line does not properly connect to some of the children of a parent. 

**To Reproduce**
Request the following CSV file in your chart, using the **sky** chart. This will not properly display once you drill down and open all the child elements.  

https://raw.githubusercontent.com/twillisCFB/public/main/sample.csv 

**Expected behavior**
Line should connect to all children of any parent element. 

**Screenshots**
![image](https://user-images.githubusercontent.com/118190809/210375221-6849a981-126c-4a63-8d75-99ee2fbd5580.png)

**Desktop (please complete the following information):**
Issue is present on Chrome and Edge. Others not tested.

**Additional context**
Problem only occurs if this specific layout is selected, we have tried other templates and they work as expected.

**Comment by bumbeishvili** [comment]
This is strange and interesting, I will investigate

**Comment by bumbeishvili** [comment]
I think I figured it out

This was the line that was causing issues when `x` was 0 (which was in your example)

https://github.com/bumbeishvili/org-chart/blob/dbf60a1fa6138f05f73935315efd0d44625e408b/src/d3-org-chart.js#L1049

You can fix it by overriding the link generation function

```javascript
const chart = new OrgChart().container....  // Every method stays same, but don't invoke .render yet

// Then override diagonal function for top layout
const bindings = chart.layoutBindings();

bindings.top.diagonal = function diagonal(s, t, m) {
          const x = s.x;
          const y = s.y;
          const ex = t.x;
          const ey = t.y;

          let mx = m && m.x != null ? m.x : x;  // This is a changed line
          let my = m && m.y != null ? m.y : y; // This also is a changed line

          let xrvs = ex - x < 0 ? -1 : 1;
          let yrvs = ey - y < 0 ? -1 : 1;

          let rdef = 35;
          let r = Math.abs(ex - x) / 2 < rdef ? Math.abs(ex - x) / 2 : rdef;

          r = Math.abs(ey - y) / 2 < r ? Math.abs(ey - y) / 2 : r;

          let h = Math.abs(ey - y) / 2 - r;
          let w = Math.abs(ex - x) - r * 2;
          //w=0;
          const path = `
                    M ${mx} ${my}
                    L ${x} ${my}
                    L ${x} ${y}
                    L ${x} ${y + h * yrvs}
                    C  ${x} ${y + h * yrvs + r * yrvs} ${x} ${
            y + h * yrvs + r * yrvs
          } ${x + r * xrvs} ${y + h * yrvs + r * yrvs}
                    L ${x + w * xrvs + r * xrvs} ${y + h * yrvs + r * yrvs}
                    C  ${ex}  ${y + h * yrvs + r * yrvs} ${ex}  ${
            y + h * yrvs + r * yrvs
          } ${ex} ${ey - h * yrvs}
                    L ${ex} ${ey}
         `;
          return path;
};

chart.render()
```



Here is an updated sample

https://stackblitz.com/edit/web-platform-pccu7b?file=index.html
