### ISSUE TITLE
Multiple root support 

### ISSUE THREAD

**Issue by sohhamm** [bumbeishvili/org-chart#216]
let's say we have three co-founders at the root node, and each of them have their own tree, how would I implement that?

**Comment by bumbeishvili** [comment]
You will artificially add one root node in the data, and then you will hide it in `nodeUpdate` and `linkUpdate` method


```javascript
chart
.nodeUpdate(function(d){
  if(d.data.parentId==null){
   d3.select(this).style('display','none')
  }
})
.linkUpdate(function(d){
  if(d.data.parentId==null){
   d3.select(this).style('display','none')
  }
})
```

**Comment by sohhamm** [comment]
Worked thanks 👍🏽
