### ISSUE TITLE
Focus on expand button using keyboard

### ISSUE THREAD

**Issue by iae1** [bumbeishvili/org-chart#220]
Is there a way to to focus on the org chart's expand button using one's keyboard? The expand buttons seem to be built using <g> tags, and those <g> tags don't have a tab-index allowing an immediate focus.

Thank you so much for this library. It overall excellent!

**Comment by bumbeishvili** [comment]
@iae1 haven't thought about that

You can override `buttonContent` and set tab-index manually

![image](https://user-images.githubusercontent.com/6873202/211615221-ef0b6392-1be9-4554-86d7-b89ef3e208ec.png)

![image](https://user-images.githubusercontent.com/6873202/211615321-3120207e-005a-4388-9ce5-d7a94f752eba.png)

https://stackblitz.com/edit/web-platform-cajksr?file=index.html

**Comment by iae1** [comment]
Awesome- thanks David. Then would it be possible to add an event listener for that button for keyboards?

The following screenshot is code that worked for me when I tested it on my local machine, but you might have a more elegant solution.

<img width="704" alt="Screen Shot 2023-01-10 at 12 43 19 PM" src="https://user-images.githubusercontent.com/78219129/211624138-9e8e97c6-5b42-4e13-b5b2-0e20670708b5.png">
