### ISSUE TITLE
Node Content Click

### ISSUE THREAD

**Issue by Karthik-code1010** [bumbeishvili/org-chart#222]
![image](https://user-images.githubusercontent.com/97900968/211981740-4a9c78e7-dd8b-449a-998b-c7849ee445dd.png)

https://user-images.githubusercontent.com/97900968/211981740-4a9c78e7-dd8b-449a-998b-c7849ee445dd.png

Org Chart Node Content "click " event only working entire node, I have three icon inside node content. I need  click event in sperate icon. please tell solution

**Comment by bumbeishvili** [comment]
You can use following

```
chart.nodeUpdate(function(d,i,arr){
   d3.select(this).select('<yourIconCSSSelector>').on('click',d=>{
       // Do whatever you want, you can access original data via d.data property
   })
})
```

**Comment by Karthik-code1010** [comment]
Thanks, Its Working
