### ISSUE TITLE
Search example

### ISSUE THREAD

**Issue by omerkoray** [bumbeishvili/org-chart#224]
Hi David,

Can you show search a text and expand all parent nodes in orgChart ?

**Comment by bumbeishvili** [comment]
Search should be independent of the org chart.

The way I did in one of my projects after the search query was entered, I looped over all nodes and filtered ones where the search matched, then I added their parents up to the root to them (so that we can have a tree structure, I used d3.stratify for it and node.ancestors() function ) and then rerendered graph based on the new data

**Comment by omerkoray** [comment]
can you share me your app link?

**Comment by bumbeishvili** [comment]
No, it was private project

**Comment by omerkoray** [comment]
ok, can you share example code ?

**Comment by omerkoray** [comment]
can anyone help me ? =)

**Comment by dmytro-machulskyi** [comment]
Faced same situation, but I was filtering my original data, finding root and added it to the data passed to chart. So my react component that rendering org chart is received new data, and theoretically it's ok. 
1. can you say how exactly you use this `d3.stratify`? As I understand, on actual chart.data(props.data) it runs under the hood.
2. I am on chart page, after receiving a new data chart is not updating. I mean that when I get new filtered array and pass in to chart it renders old version.

**Comment by bumbeishvili** [comment]
I've prepared a search example here


https://stackblitz.com/edit/js-wdexqc?file=index.html

https://github.com/bumbeishvili/org-chart/assets/6873202/9427915c-2cca-45e9-a13f-dced8aa0ed60

**Comment by omerkoray** [comment]
Hi David,

Thanks a lot for this work. But i need search title, unit, etc. Search area search only names =/
________________________________
Gönderen: David Bumbeishvili ***@***.***>
Gönderildi: 15 Eylül 2023 Cuma 22:35
Kime: bumbeishvili/org-chart ***@***.***>
Bilgi: omerkoray ***@***.***>; Author ***@***.***>
Konu: Re: [bumbeishvili/org-chart] Search example (Issue #224)


I've prepared a search example here

https://stackblitz.com/edit/js-wdexqc?file=index.html

https://github.com/bumbeishvili/org-chart/assets/6873202/9427915c-2cca-45e9-a13f-dced8aa0ed60

**Comment by bumbeishvili** [comment]
Hi,

**Comment by bumbeishvili** [comment]
You should be able to easily adapt this sample to match your data

**Comment by omerkoray** [comment]
I couldn't do it, it didn't work. search works very slowly for 5k rows of data.

________________________________
Gönderen: David Bumbeishvili ***@***.***>
Gönderildi: 16 Eylül 2023 Cumartesi 17:31
Kime: bumbeishvili/org-chart ***@***.***>
Bilgi: omerkoray ***@***.***>; Author ***@***.***>
Konu: Re: [bumbeishvili/org-chart] Search example (Issue #224)


You should be able to easily adapt this sample to match your data
