### ISSUE TITLE
Cycle Error - Dataset structure hasn't changed

### ISSUE THREAD

**Issue by Shadowfita** [bumbeishvili/org-chart#225]
Hi,

This isn't a bug with this project specifically, however I was wondering or hoping anyone was experiencing this or had suggestions.

I've recently started getting the "cycle" error, even though my dataset which has been working fine hasn't had any structural changes. If I comment this error out in the stratify function, the org chart renders perfectly fine, and there are no circular references when I expand all, for example.

This seems very unusual. Any ideas?

**Comment by Shadowfita** [comment]
I've closed this because its not an issue with the project. Still hoping someone can add to this!

**Comment by bumbeishvili** [comment]
Can you post the data? only nodeId, id part will be enough

**Comment by Shadowfita** [comment]
> Can you post the data? only nodeId, id part will be enough

I've figured it out! I *thought* my structure hadn't changed, but a Supervisor dropped off from our list due to payroll issues which made the next person down the Supervisor for the area (and their own). 🙄 Finally sorted, thank you! There must be further sanitation done to prevent infinite renders on the chart.
