### ISSUE TITLE
How can I init the chart with all the nodes expanded?

### ISSUE THREAD

**Issue by nau12345** [bumbeishvili/org-chart#226]
When the chart inits only shows 2 nodes levels, if I want to see more levels, I have to expand the nodes.

How can I init the chart with all the nodes expanded?

When the chart inits:

![image](https://user-images.githubusercontent.com/118267635/214619516-fcb4ddef-43f0-4c28-b9f7-86b08720c0c9.png)

What I'm looking for when the chart inits:

![image](https://user-images.githubusercontent.com/118267635/214619848-b0dbb244-3789-42cc-a2e7-21b2630e3ae2.png)

**Comment by bumbeishvili** [comment]
Currently, there is no straightforward way. For now I'd suggest assigning _expanded property to nodes you want to be expanded

**Comment by nau12345** [comment]
Thanks for the response.

But if I add _expanded, the nodes don't appear expanded.

![image](https://user-images.githubusercontent.com/118267635/215073097-8dddd9af-2229-4e21-bdb9-0d0f5fca6cf4.png)

**Comment by bumbeishvili** [comment]
@nau12345 add that before you pass the data to the org chart

**Comment by nau12345** [comment]
Can you give me an example?

**Comment by bumbeishvili** [comment]
Roughly
```
data.forEach(d=>d._expanded=true)

new OrgChart().data(data)...render()
```

**Comment by nau12345** [comment]
Thanks!
