### ISSUE TITLE
Custom extend/collapse buttons

### ISSUE THREAD

**Issue by Enkkfull** [bumbeishvili/org-chart#231]
Hi, I'm using this wonderful tool for the development of a website showing a flowchart of chess openings. 

You can find it here: https://enkk.me/openings/

So far I've managed to customise almost everything, however, since my nodes have a lot of content the proportion between them and the expand/collapse buttons is way off. I'd like to make them bigger. I've been tinkering with the content of the buttonContent but without success.

An alternative would be to add a static button in each node that could perform this action, however, I wouldn't know how to configure the nodeUpdate function to perform such action (in particular which functions to call in order to manually expand or retract that particular node while also changing the label of the button). 

Do you have any suggestions?

Thanks.

**Comment by Enkkfull** [comment]
A little update. 

I've managed to find a solution in which clicking on the node itself expands/retracts it by using the nodeUpdate function and finding its child `.node-button-div` and launching a `.click()`. This allowed me to customise the button content as a wished. 

This is my function:

```
.nodeUpdate(function(d,i,arr){
         d3.select(this).select('.tree_card').on('click', event=>{
           let clicked_elem = jQuery(event.srcElement)
           if (clicked_elem.prop("tagName") == "I") {
             toChessCom(clicked_elem.parents('a').attr("name"))
           } else {
             var node = jQuery(this)
             node.find(".node-button-div").click() //the expand button
           }

         })
      })
```

As you can see I'm also capturing the click on another element (an icon that acts as link, therefore the tag name `I`) which brings to the chess.com page relative to the position.

Now I only have one last issue, which is that nodes can vary in height which makes the position of the button sometimes a bit off. Is there a way to dinamically change node dimensions?

**Comment by bumbeishvili** [comment]
Hi, you could customize the node button  by overriding `buttonContent` and related properties

https://github.com/bumbeishvili/org-chart/blob/dev/src/d3-org-chart.js#L58-L61

As for your question:

> So far I've managed to customise almost everything, however, since my nodes have a lot of content the proportion between them and the expand/collapse buttons is way off. I'd like to make them bigger. I've been tinkering with the content of the buttonContent but without success.

Seems like you require dynamic node Width and node Height, which library already supports, you can customize each node width and height using

```javascript
chart.nodeWidth(d=> {
 return 200// or different based on the d
})
.nodeHeight(d=> {
 return 200// or different based on the d
})
```


> Now I only have one last related issue, which is that my nodes can vary in height which makes the position of the button sometimes a bit off. Is there a way to dynamically change node heights based on the generated content?

This part is more complex, I had similar requirements once. This is roughly what I did (don't exactly remember names, but you will get the idea)
```javascript

function nodeContent(){
   // return some html string
}
chart
.nodeHeight(d=> {
   content = nodeContent(d)
 contentNode =  d3.create('div').html(content);
 body.addChild(contentNode.node()) // not sure if add child is actual function, 

 boundingCLient = contentNode.node().getBoundingClientRectl
contentNode.remove()
return boundingClient.height
})
```

Hope this will make sense. So you are actually generating the content and taking the height, then removing content
