### ISSUE TITLE
How to add a text on a link between to node?

### ISSUE THREAD

**Issue by JulianAffaire** [bumbeishvili/org-chart#232]
Hello,

first thank you for this integration for angular it works great.
I'm wondering how can I acheive my goal that is to add a text on a link between 2 nodes (the text is in the datas).

Is it possible with the module?

Thank you.

**Comment by bumbeishvili** [comment]
Hi, you probably want to utilize either `onNodeUpdate` or `onLinkUpdate` method. `this` refers to the DOM element and you can use that reference to add text where you want (you also have an access to data, `x,y,width`, height properties)

**Comment by JulianAffaire** [comment]
Hi, ok thanks, I tried it but I can't find a clean way to "override" linkUpdate" and keep the default beahaviour + adding the new text on the link. Do you have some examples?
Thank you for your time :)
Julian

**Comment by bumbeishvili** [comment]
No, unfortunately I don't have any examples
