### ISSUE TITLE
The org cannot have two or more people as supreme leader

### ISSUE THREAD

**Issue by MateoCaicedoW** [bumbeishvili/org-chart#238]
**Describe the bug**
when there are two or more people as a leader the library doesn't work

**Comment by bumbeishvili** [comment]
Yes. we don't support two parents. For the workaround, it's possible to use connections, to connect any node to any node 

https://stackblitz.com/edit/js-tpbt7r?file=index.html

**Comment by devjaof** [comment]
Or you could set a "fake-root" as the supreme leader and then just set its properties so it doesnt appears to be on screen: 


`.childrenMargin((d) => {
       return d.depth === 0 ? -100 : 120;
 })
 .linkUpdate(function (d) {
    d3.select(this){
        if (d.depth === 1) {
           d3.select(this).attr('display', 'none');
         }
    }
  })
  .nodeUpdate(function (d) {
         if (d.depth === 0) {
            d3.select(this).attr('display', 'none');

            d.height = 0;
            d.width = 0;
         }
   })
`

**Comment by bumbeishvili** [comment]
check #59, #138

**Comment by MateoCaicedoW** [comment]
is there any way to expand the 3 first levels? @bumbeishvili

**Comment by bumbeishvili** [comment]
I don't think that currently there is another way.

In the future, you will be able to set `expandLevel`initially, it does not work currently

https://github.com/bumbeishvili/org-chart/blob/c8ebb0490ecfcf1424c16a8528a4a835d3efde53/src/d3-org-chart.js#L37

**Comment by devjaof** [comment]
> I don't think that currently there is another way.
> 
> In the future, you will be able to set `expandLevel`initially, it does not work currently
> 
> https://github.com/bumbeishvili/org-chart/blob/c8ebb0490ecfcf1424c16a8528a4a835d3efde53/src/d3-org-chart.js#L37

Great!

**Comment by MateoCaicedoW** [comment]
I made this to solve this problem 
` 
   let secondLevel = rawData.filter((d) => d.parentId == 1);
        rawData.forEach((d) =>{
            if (d.parentId !== 1 && secondLevel.some((e) => e.id == d.parentId)) {
                d._expanded = true;
            }
        });
`

My first level is a node with 1 as ID.
