### ISSUE TITLE
Button that set the chart to its initial state.

### ISSUE THREAD

**Issue by devjaof** [bumbeishvili/org-chart#240]
I've created a personalized initial state to orgchart where i start the chart with the two fake roots at the top of the svg. 

What i need to do is to create a button that set the chart to this initial state again, does anyone know if there's a way of doing this?

**Comment by bumbeishvili** [comment]
Have a boolean parameter, which would be set after the button click, use this bool parameter inside your nodeContent function and finally redraw after the button click (using `chart.render()`)

**Comment by devjaof** [comment]
Button that sets boolean paramenter:
![image](https://user-images.githubusercontent.com/94070775/219755754-05184a4f-389c-4837-9ac5-099e2898d58c.png)

And this is my nodeContent function:
![image](https://user-images.githubusercontent.com/94070775/219756626-72802a69-1ca1-4a53-9bbe-35c0d6b0874f.png)


Are you saying that i need to render the chart inside of the nodeContent function?

**Comment by bumbeishvili** [comment]
Something like this
```javascript
let isInitial = false;

let chart = new OrgChart()
...
.nodeContent(d=>{
  if(isInitial) {
   //   then generate content for initial node  
 }else{
  // do multi root version
}
})

//  when button is clicked change variable and rerender graph
button.onClick = ()=>{
  isInitial = true;
  chart.render()
}



```
