### ISSUE TITLE
How can I solve this? Is it possible? 

### ISSUE THREAD

**Issue by MateoCaicedoW** [bumbeishvili/org-chart#241]
I made a dropdown inside of nodeContent function but, when it is displayed it looks like this. How can I get it overlay to the other nodes?
<img width="425" alt="image" src="https://user-images.githubusercontent.com/104871275/219792944-4813a8f0-b294-47a7-90c1-10d5c68e55f6.png">

**Comment by bumbeishvili** [comment]
@MateoCaicedoW 

If you can somehow get access to the wrapper dom element, you can invoke `d3.select(element).raise()` and it should fix that issue

**Comment by bumbeishvili** [comment]
In your place, I'd probably listen to a mouse enter events for a `.node-foreign-object-div`


Let me know if it works

```javascript
chart.onNodeUpdate(function()=>{
  d3.select(this).select('.node-foreign-object-div')
    .on('mouseenter.hover',d=>{  // named events won't cause performance burden 
        d3.select(this).raise()
    })
})
```

**Comment by MateoCaicedoW** [comment]
Thanks, it works, but the drop-down list should be scrolling but, when I try to scroll it, the zoom doesn't allow it.

https://user-images.githubusercontent.com/104871275/220637692-bafe59a7-26ac-4c76-be31-ab0ac2abd3c0.mov

**Comment by bumbeishvili** [comment]
Not exactly sure how to help there. I am guessing you need somehow to catch the scrolling event for dropdown and don't bubble up

**Comment by MateoCaicedoW** [comment]
how could I make the zoom not apply to the list?
