### ISSUE TITLE
change data to empty list & page didnot render?

### ISSUE THREAD

**Issue by yangxuy** [bumbeishvili/org-chart#244]
```js
 chart
            .data(list)
            .render();
```

when i change list to empty. page dose not change and keep before data

**Comment by bumbeishvili** [comment]
Is list null or empty array?

**Comment by yangxuy** [comment]
empty array not null

**Comment by yangxuy** [comment]
In your source code I found the following code
```js
  if (!attrs.data || attrs.data.length == 0) {
            console.log('ORG CHART - Data is empty')
            return this;
        }
```
This is causing my problem now

**Comment by yangxuy** [comment]
I found that someone already had a similar problem by this [method](https://github.com/bumbeishvili/org-chart/pull/242)

**Comment by bumbeishvili** [comment]
That entirely different issue, but yes, you can use similar function (or even remove parent SVG completelly)
