### ISSUE TITLE
React D3-org-Chart - Zoom behavior Update

### ISSUE THREAD

**Issue by ganeshmuthukrish** [bumbeishvili/org-chart#245]
Hi David, 
[org-chart.zip](https://github.com/bumbeishvili/org-chart/files/10810835/org-chart.zip)
I am using your d3-org-chart  react library and have built Org Chart(attached sample project). In this, I can disable zoom behavior by updating  the components/orgchart.js by the below code (to include .scaleExtent([1,1])).

const chart = new OrgChart();
    if (props.data && d3Container.current) {
      chart
        **.scaleExtent([1,1])** // disable zoom behavior
        .container(d3Container.current)
        .data(props.data)
        .nodeWidth((d) => 300)
        .nodeHeight((d) => 140)
        .compactMarginBetween((d) => 80)
        .onNodeClick((d) => {
          toggleDetailsCard(d);
        })
        .buttonContent((node, state) => {
          return ReactDOMServer.renderToStaticMarkup(
            <CustomExpandButton {...node.node} />
          );
        })
        .nodeContent((d) => {
          return ReactDOMServer.renderToStaticMarkup(
            <CustomNodeContent {...d} />
          );
        })
        .render();
    }

In the above i want to include zoom behavior **only when ctrl key is pressed(like google map zoom behavior)** instead of  just by moving wheel. I have tried multiple options like adding Event Listener for d3 conatiner , updating chart.scaleextend based on keypress event etc. Nothing has worked out also how to add scroll bars when chart goes beyond the limit. is there any option available for this.? please help me on this

**Comment by bumbeishvili** [comment]
I am assuming, you still want panning to work, right?

**Comment by ganeshmuthukrish** [comment]
yes. still I want to Zoom, but when pressing the ctrl key it should happen.

**Comment by bumbeishvili** [comment]
I am not exactly sure how to approach this.

Looking at the d3-zoom source code, in your place, I'd try to stop the `wheel` event on `svg` element when the CTRL key is not pressed (stopPropagation might work), otherwise, I really have no idea

https://github.com/d3/d3-zoom/blob/077f87cc52297f893eaeca9f43dce4b17676a268/src/zoom.js#L75

**Comment by ganeshmuthukrish** [comment]
Hi david Thanks for your quick response. I have already tried like below code

const zoomBehavior = d3
        .zoom()
        .on("zoom", () => {
          const transform = d3.event.transform;
          chart
            .transform({
              x: transform.x,
              y: transform.y,
              k: transform.k,
            })
            .update();
        })
        .on("wheel.zoom", (event) => {
          if (!event.ctrlKey) {
            event.preventDefault();
          }
        });
      d3.select(d3Container.current).call(zoomBehavior);

and also tried these options too 

d3Container.current.addEventListener("wheel", (event) => {
        if (!event.ctrlKey) {
          event.preventDefault();
        }
      });
      d3Container.current.addEventListener("wheel.zoom", (event) => {
        if (!event.ctrlKey) {
          event.preventDefault();
        }
      });
      d3Container.current.addEventListener("wheelDelta", (event) => {
        if (!event.ctrlKey) {
          event.preventDefault();
        }
      });

also tried 
window.addEventListener("keydown", handleKeyDown);
      window.addEventListener("keyup", handleKeyUp);
      window.addEventListener("wheel", handleWheel, { passive: false });

      chart.render();

      return () => {
        window.removeEventListener("keydown", handleKeyDown);
        window.removeEventListener("keyup", handleKeyUp);
        window.removeEventListener("wheel", handleWheel);
      };

Nothing has worked out. Thanks Again

**Comment by bumbeishvili** [comment]
> .on("wheel.zoom", (event) => {
> if (!event.ctrlKey) {
> event.preventDefault();
> }
> });

I think you need to add this event to the SVG element, not the zoom behavior

d3Container.current. - refers to div element (parent of svg element), so you need to get actual svg element
```javascript
d3.select(d3Container.current).select('svg')
 .on("wheel.zoom", (event) => {
 if (!event.ctrlKey) {
 event.preventDefault();
}
});
```

**Comment by ganeshmuthukrish** [comment]
Thanks. I got you. But I already tried like below 
 // Create a d3-zoom behavior
      const zoom = d3
        .zoom()
        .on("zoom", (event) => {
          if (event.sourceEvent.ctrlKey) {
            chart.zoom(event.transform);
          }
        });

      // Apply the zoom behavior to the SVG element
      d3.select(d3Container.current)
        .select("svg")
        .call(zoom)
        // Disable scroll wheel zooming by default
        .on("wheel.zoom", null)
        // Enable scroll wheel zooming when the Ctrl key is pressed
        .on("wheel.zoom", (event) => {
          if (event.ctrlKey) {
            zoom(event);
          }
        });
    }

also
 d3.select(d3Container.current).select('svg')
        .on("wheel", (event) => {
          if (!event.ctrlKey) {
            event.preventDefault();
          }
        });

No luck.. Any clue do you get on the above code

**Comment by bumbeishvili** [comment]
Ok, here is a hacky way which works 

```javascript
 const listener = d3.select(d3Container.current).select('svg')
        ._groups[0][0].__on[0].listener;
d3.select(d3Container.current)
        .select('svg')
        .on('wheel.zoom', function (e, b, c, d) {
          if (e.ctrlKey) {
            listener.bind(this)(e, b, c, d);
          }
        });
```

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-kynqim?file=OrgChart.js

**Comment by ganeshmuthukrish** [comment]
Thank you. This is working. Awesome.
