### ISSUE TITLE
In React d3-org-chart, how to Include scroll bars and stay root node on top when all child collapsed and how to achieve horizontal layout

### ISSUE THREAD

**Issue by ganeshmuthukrish** [bumbeishvili/org-chart#246]
Hi David,  I have a few questions on org-chart implementation. Can you please provide details on how to achieve these  things?

1. How to include scroll bars in Org charts(attached sample code). I have  50 child nodes, able to see all levels through a scroll bar 
2. when collapsing all the child nodes, the root node is centered, but in initially its top aligned. i want the same position after making the collapse of all children.
3. How to make horizontal layout instead of  the default vertical.
4. Marking/highlight  child to root node is possible?  do we have  any example for these?

[org-chart.zip](https://github.com/bumbeishvili/org-chart/files/10821051/org-chart.zip)

Thanks,
Ganesan M

**Comment by bumbeishvili** [comment]
Hi, I don't think that the first one is possible (it's possible artificially, but not with native scroll and it will require some work)

As for other questions, I'd suggest checking examples in the dev version and I think some of the examples will answer your questions.
https://github.com/bumbeishvili/org-chart/tree/dev#features

**Comment by ganeshmuthukrish** [comment]
Thanks for your Quick Response. I want to implement [](https://codesandbox.io/s/react-org-chart-d3-forked-8110t) template in 
[](https://codesandbox.io/s/org-chart-oiih3c) this. I want a stable chart without active node focus. Can you please guide me this pls

**Comment by ganeshmuthukrish** [comment]
Thanks David

**Comment by ganeshmuthukrish** [comment]
Thanks David for your Quick response
