### ISSUE TITLE
how to include horizontal and vertical scroll bar in D3-org-chart

### ISSUE THREAD

**Issue by ganeshmuthukrish** [bumbeishvili/org-chart#247]
Hi David,  This is my configuration for org-chart. I have made compact as false, now I want vertical and horizontal scroll bars when user expands the nodes. Is there any hacky way to achieve this. 

const OrganizationalChart = (props) => {
  const d3Container = useRef(null);
  useLayoutEffect(() => {
    const chart = new OrgChart();
    if (!isEmpty(props.data) && d3Container.current) {
      chart
        .scaleExtent([0.4, 1.5])
        .container(d3Container.current)
        .data(props.data)
        .compact(false)
        .setActiveNodeCentered(false)
        .nodeWidth((d) => 350)
        .nodeHeight((d) => 150)
        .compactMarginBetween((d) => 100)
        .onNodeClick((d) => {
        })
        .buttonContent((node, state) => {
          return ReactDOMServer.renderToStaticMarkup(
            <CustomExpandButton {...node.node} />
          );
        })
        .nodeContent((d) => {
          return ReactDOMServer.renderToStaticMarkup(
            <CustomNodeContent {...d} />
          );
        })
        .render();
      const listener = d3
        .select(d3Container.current)
        .select("svg")
        ._groups[0][0].__on[0].listener;
      d3.select(d3Container.current)
        .select("svg")
        .on("wheel.zoom", function (e, b, c, d) {
          if (e.ctrlKey) {
            listener.bind(this)(e, b, c, d);
          }
        });
    }
  }, [props, props.data]);

My overflow changes are not reflecting in 'svg-chart-container' , but width and height changes are reflecting.  how to make it scrollable when expanding. Has any one come across use case like this?
Thanks

**Comment by ganeshmuthukrish** [comment]
I am not able to get/set the exact width and height of the svg element and make it scrollable when expanding. Has any one come across use case like this?

**Comment by bumbeishvili** [comment]
I don't think that content within SVG can be scrollable

**Comment by 4Michael1Angelo5** [comment]
I'm not sure if this solution is the one you're looking for but you could set the container height of the chart to a specified amount say 500px, then set the SVG height to something larger like 800. Then set the CSS of the SVG/ chart container to overflow-y: scroll.
