### ISSUE TITLE
can we implement mouse over, mouse leave and mouse events same as onNodeClick() on React d3-org-chart 

### ISSUE THREAD

**Issue by ganeshmuthukrish** [bumbeishvili/org-chart#249]
Hi david, I want to implement  **chart.setUpToTheRootHighlighted** when mouse over and **chart.clearHighlighting** when mouse  out of Node content on d3-org-chart. is it possible? (i could see only onNode Click() event.  )  thanks.

**Comment by bumbeishvili** [comment]
You can attach custom events in `nodeUpdate` method, where `this` refers to current dom element. From that point, you are free to manipulate HTML elements in the way you want (change colors of lines and nodes, stroke-width of lines e.t.c)
