### ISSUE TITLE
How can I solve this problem? This is on safari and mozilla.

### ISSUE THREAD

**Issue by MateoCaicedoW** [bumbeishvili/org-chart#251]
https://user-images.githubusercontent.com/104871275/221578096-a90bcca5-af4c-4b53-a9e3-427719db6ea2.mov

**Comment by MateoCaicedoW** [comment]
But on Google chrome it works well

**Comment by bumbeishvili** [comment]
![image](https://user-images.githubusercontent.com/6873202/221579855-2d9d8c7e-f428-4140-a733-eb9e739e3d65.png)

@MateoCaicedoW make sure absolute or fixed positions aren't used and make sure content inside the node, does not overflow defined width and height in any way 

You can leverage bigger width and height and apply some paddings to wrapper element
https://stackblitz.com/edit/js-rvwpza?file=index.html

**Comment by MateoCaicedoW** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/104871275/221584392-1b1f2785-744f-483c-b8cc-a5d60ee61a6a.png">
it means that I cannot make it in safari? right?

**Comment by MateoCaicedoW** [comment]
@bumbeishvili

**Comment by bumbeishvili** [comment]
No, issue is visible when you move org chart around, so in your place I'd close that dropdown once the zooming started

**Comment by MateoCaicedoW** [comment]
Thanks for answering. I appreciate it.
