### ISSUE TITLE
Responsive org chart

### ISSUE THREAD

**Issue by maciccioli** [bumbeishvili/org-chart#252]
Hi, how are you? I am trying to reuse my org chart on mobile by creating a WebView. My idea is that users can use and view the org chart in the same way as on the web. However, I am facing some UI problems when I try to use it in mobile devices. I am attaching an image that shows how the org chart looks today on the web and on mobile.

**Comment by bumbeishvili** [comment]
Interesting. Not sure to help there, to be honest. In your place, I'd check if the default version is working

https://stackblitz.com/edit/web-platform-sgsxzp?file=index.html
