### ISSUE TITLE
Bug when changing state

### ISSUE THREAD

**Issue by maciccioli** [bumbeishvili/org-chart#256]
Hello! How are you doing? I hope you are fine.

I am currently working on developing an org chart using React. However, I have encountered an issue related to changing the language of the website. Whenever I attempt to change the language, the org chart reverts back to its original position. I suspect that this issue is due to state changes in React.

Would you happen to have any suggestions on how I can fix this bug? 

Here,I attach a video with the issue.

https://user-images.githubusercontent.com/97119930/224506315-695aeb99-292a-4de3-8bab-9a11b07e81a5.mov

Thank you for your time and help in advance!

**Comment by bumbeishvili** [comment]
I think what's happening is that new data is getting passed (not only array reference, but new objects as well). 

As I remember org chart mutates passed objects and adds _expanded flag to track which nodes were expanded when state changes. I suspect this property is getting removed when language changes and that's why it reloads

**Comment by maciccioli** [comment]
Hi there,

Thank you for getting back to me so quickly.

I would like to know if it is possible to create a React state that can save the state of each node, specifically whether it is expanded or not, and then use this state when changing languages. Maybe, this could prevent the node from returning to its initial position each time a language switch occurs.

**Comment by bumbeishvili** [comment]
You can treat passed data as state and don't create it everytime language changes and it will probably work

**Comment by maciccioli** [comment]
Thank you for your suggestion. I'm curious, do you have an example of how to implement this approach? It would be very helpful to see an example to better understand how to treat the passed data as state

**Comment by bumbeishvili** [comment]
Unfortunately no, I don't have any. And don't even know if this is a core issue, it's just a guess
