### ISSUE TITLE
Drag and click event confusion

### ISSUE THREAD

**Issue by bumbeishvili** [bumbeishvili/org-chart#259]
Sometimes node is clicked, but the drag event is firing. Need to address this

**Comment by yyqsg888** [comment]
Can be fixed by adding .clickDistance(10) to d3.zoom()
Example : 

 // Get zooming function
behaviors.zoom = d3.zoom()
                .clickDistance(10) // Added to allow a leeway distance of 10 before registering a click as a drag/pan event
                .on('start', (event, d) => attrs.onZoomStart(event, d))

**Comment by bumbeishvili** [comment]
@yyqsg888 wow, did not know about it, and every time I had to implement that clickDistance-like method by myself. Thank you for mentioning it
