### ISSUE TITLE
Adding arrows and labels to links

### ISSUE THREAD

**Issue by PavelRusetsky** [bumbeishvili/org-chart#260]
Hi, is it possible to add arrows and labels to links?
example:
![image](https://user-images.githubusercontent.com/49963615/227256621-0188eb5d-8f82-4d1d-a3fa-de6c848582e5.png)

**Comment by bumbeishvili** [comment]
In theory yes -  you have the possibility to modify path (link) svg element in `onNodeUpdate` and `onLinkUpdate` method.

**Comment by kanth609** [comment]
@bumbeishvili dou you have any example where the Arrow and Label is available on links. If yes, please share link of it.
Thanks!

**Comment by chirag-acto** [comment]
Hi @bumbeishvili, I can see the `[defs](https://github.com/bumbeishvili/org-chart/blob/cb1f376656bc83360a4fea6872597fd427fcd775/src/d3-org-chart.js#L264)` function which is setting the marker for the connections, but not sure how to enable it? can you help me with that?
