### ISSUE TITLE
Prevent scroll zoom unless ctrl key is pressed

### ISSUE THREAD

**Issue by eSaner** [bumbeishvili/org-chart#264]
I'd like to be able to scroll the page while the cursor is over the chart, but enable zoom if ctrl key is pressed while scrolling over the chart. I see [this was addressed here with React](https://github.com/bumbeishvili/org-chart/issues/245). [This issue was also helpful](https://github.com/bumbeishvili/org-chart/issues/148).

How can I do this in vanilla JS? Something like below works if ctrl + scroll is done over the chart before just a scroll. Maybe I need to redefine chart.getChartState().svg to something other than null before returning? This is being called after .render().

`d3.select('svg').call(d3.zoom().on('zoom', (e) => {
        // Disable zoom if ctrl key is not pressed
        if (e.sourceEvent.type === 'wheel' && !e.sourceEvent.ctrlKey) {
          chart.getChartState().svg.on('wheel.zoom', null);
        }

        return d3.select('.chart').attr('transform', e.transform);
 }));`

**Comment by bumbeishvili** [comment]
I remember someone posting the similar issue, I'd recommend checking out issues

**Comment by eSaner** [comment]
This worked.

`const listener = d3.select('svg')._groups[0][0].__on[0].listener;
      d3.select('svg')
        .on('wheel.zoom', function (e, b, c, d) {
          if (e.ctrlKey) {
            listener.bind(this)(e, b, c, d);
          }
        }
      );`
