### ISSUE TITLE
When adding or removing nodes, animations start at the root

### ISSUE THREAD

**Issue by dr-hongjae** [bumbeishvili/org-chart#265]
Hi, I've seen this issue before. https://github.com/bumbeishvili/org-chart/issues/261
Sorry for posting the same question issue, I think I may have misunderstood.

`chart.update(node)`
It says that writing this code will fix it, but I'm not sure how.

https://stackblitz.com/edit/web-platform-lwyild?file=index.html
I want to use the site here as an example.

`chart.removeNode('O-6069')`
When I write this code, 
or when I write it with addNode,
```
chart.addNode({
		      name: "test",
		      imageUrl: "",
		      area: "AP",
		      profileUrl: "",
		      office: "kilo",
		      tag: "something",
		      isLoggedUser: false,
		      positionName: "CTO",
		      id: 'O-6069_1',
		      parentId: 'O-6069',
          _expanded: true
		    });
```

how do I prevent the animation from starting on root?

**Comment by bumbeishvili** [comment]
I think there can be many ways to achieve the result you want.

The simplest way would be to retrieve the parent node of the node you are adding

(you can get all nodes by calling chart.getState() and then look into props and find property which stores all nodes, then filter them by id)

After you get that node, you can invoke 

`chart.addNode` and then immediately invoke chart.update(foundParentNode). 

This might work, but again, not sure , haven't tested

**Comment by dr-hongjae** [comment]
Ah, I get it now.
Thanks for the quick reply.

**Comment by dr-hongjae** [comment]
Sorry, it still animates from root.

I do `chart.addNode `and then immediately invoke `chart.update(foundParentNode)`.

Can you let me know if this is the way to go?

const currNode = chart.getChartState().allNodes.find(obj => obj.id === nodeId);
1. chart.addNode
2. chart.update(currNode)

**Comment by bumbeishvili** [comment]
If it does not work, then no. 

What I'd suggest now, is to update the data itself (push some dummy node to the data array)

And then invoke

`chart.update(currNode)`

So, you need to do this part manually

https://github.com/bumbeishvili/org-chart/blob/c8ebb0490ecfcf1424c16a8528a4a835d3efde53/src/d3-org-chart.js#L503

And then you need to override this part

https://github.com/bumbeishvili/org-chart/blob/c8ebb0490ecfcf1424c16a8528a4a835d3efde53/src/d3-org-chart.js#L1188

Hope this makes sense, if not, then I am out of options

**Comment by dr-hongjae** [comment]
Thanks for being so kind to let me know.
The code you gave me didn't work, but it was a great hint.

I gave the buttons on the node that I open when I draw the chart an id of class.

I don't know if my approach is correct, but this is how I did it.

1. call addNode without giving _expanded: true
2. click the node button with the specific node id

**Comment by bumbeishvili** [comment]
Interesting approach
