### ISSUE TITLE
Is tooltip available org-chart?

### ISSUE THREAD

**Issue by Karthik-code1010** [bumbeishvili/org-chart#266]
I have org-chart. if I hover single element I need to get name in tooltip.

![image](https://user-images.githubusercontent.com/97900968/233552281-ecfb4fcf-5900-4c0a-9426-fa4dbfe4e7af.png)

**Comment by bumbeishvili** [comment]
No, but you have an exposed method called to`onNodeUpdate` method, where you can access the DOM elements of each node (`this` refers to the DOM element) and attach anything to them

**Comment by Karthik-code1010** [comment]
ok thanks.
