### ISSUE TITLE
Add a hook to wait for the completion of fit

### ISSUE THREAD

**Issue by m-gallesio** [bumbeishvili/org-chart#269]
Greetings.
I think it would be useful to have a way to know when a `fit()` operation has actually concluded instead of having to rely on timeouts.
D3 transitions natively provides a `end()` method which returns a `Promise`: https://observablehq.com/@d3/transition-end.
Similar hooks could be useful in other spots I am not aware of.

**Comment by bumbeishvili** [comment]
Added the following callback support in the dev

<img width="496" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/ea9f91b9-fe90-4f73-a522-a938de1b9842">

Will be merged with this PR
