### ISSUE TITLE
Right way to make a remove node button on every node

### ISSUE THREAD

**Issue by thp44** [bumbeishvili/org-chart#273]
Hi,
I really enjoy d3-org-chart :) Thanks for making an awesome tool!

Recently, I tried to add a hide button that displays a remove button on every node. I was able to achieve this, but I'm having difficulty making the button work repeatedly on multiple components without having to click the remove button again.

I'm wondering what the best approach would be to create such a button? It seems like I need to add an event listener every time the chart is updated, but I'm struggling with "calling a function from HTML string javascript."

Could anyone provide some guidance on the best practices and methodologies for implementing this feature?

![image](https://user-images.githubusercontent.com/8833382/236137533-a86ca185-9a80-4e27-b597-1563a9e08095.png)

**Comment by thp44** [comment]
Great thanks, it works! 👍 
 
The removed node somehow still appear when expanding the chart if I make show/hide button for the remove button. I think it a state issue outside org-chart though..

**Comment by bumbeishvili** [comment]
Can you share a recording of the screen?  And if you are using any libraries

**Comment by bumbeishvili** [comment]
Additional thoughts - yes, it's most probably a state issue, and the same/previous data (with removed node) is getting passed probably
