### ISSUE TITLE
How do I make it mobile responsive?

### ISSUE THREAD

**Issue by hjh-enders** [bumbeishvili/org-chart#274]
Before submitting an issue, please make sure to check whether the similar question was asked before. 
You can search for it here - https://github.com/bumbeishvili/d3-organization-chart/issues

I developed a d3-org-chart for my project, but I can't make it mobile responsive.
The futuristic version and the chart in my project look the same,
default version appears to be mobile responsive.

Futuristic.ver looks like:
![image](https://user-images.githubusercontent.com/104335407/236781965-4cc57f6c-4cfa-45af-8b77-a15ebcfd75c8.png)

Default.ver looks like:
![image](https://user-images.githubusercontent.com/104335407/236781491-9663766a-bd5e-4acd-b1b2-5a168a9c6efb.png)

**Comment by bumbeishvili** [comment]
It looks like you are testing it in Safari which has some problems, there are only two versions that work well in Safari.

Default and sky layout.

If you check the new version in the dev branch - https://github.com/bumbeishvili/org-chart/tree/dev

I also made sure the styled tree would work in safari. 

Generally it's mobile-friendly, you just need to make sure that inner content does not overlap and absolute positions aren't used

**Comment by hjh-enders** [comment]
I've been doing some testing.
display, position should not be used.

Thank you.
Your library is very useful.
Have a great day!
