### ISSUE TITLE
d3-org-chart styles break in Safari browser

### ISSUE THREAD

**Issue by risgpta** [bumbeishvili/org-chart#275]
**Describe the bug**
The styles of d3-org-chart break when open in Safari browser

**To Reproduce**
1. Go to Safari browser
2. Go to https://www.npmjs.com/package/d3-org-chart
3. Click on first example link
4. https://stackblitz.com/edit/web-platform-o5t1ha?file=README.md

<img width="1431" alt="Screenshot 2023-05-16 at 00 54 20" src="https://github.com/bumbeishvili/org-chart/assets/34606242/b0f10f85-5df8-4eb8-a9c8-578713d77557">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1(a)
 - Browser : Safari

**Comment by bumbeishvili** [comment]
It's known issue. 

If you want safari safe version, don't use the absolute position.

<img width="837" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/b45fffcc-45be-4086-8dc8-f82cea9c1567">

Or styled tree

https://github.com/bumbeishvili/org-chart/tree/dev#features

<img width="235" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/ebf5880b-65c7-4e93-a185-3873c15f54c5">

**Comment by risgpta** [comment]
Can you elaborate further? What should be used in place of absolute position then?
Any example code?
