### ISSUE TITLE
How to set initial focused node

### ISSUE THREAD

**Issue by jptheripper** [bumbeishvili/org-chart#276]
Is there a way via url parameters to set the initial focused node? if I have
1 -
- 2 -
- - 4 -
- - 5 - 
- - - 7 -
- - - 8 -
- - 6-
- 3 -

If I wanted to load this graph with 5 as the centered/selected node, 7&8 expanded below, and 1&2 (parent and grandparent) collapsed above, is that possible

**Comment by jptheripper** [comment]
Is there also a _filtered property that can, for example, select a department or another attribute such as office location?

**Comment by bumbeishvili** [comment]
Not exactly sure what you mean, data is entirely independent in the org chart and the org chart does not know about it  (you just need to specify id and parentId), it's  up to you how you will generate the content based on your data or how you will filter them

**Comment by jptheripper** [comment]
Looking at the example, i think i can implement

          .render()
          .setCentered("O-6067")
          .setExpanded("O-6067")
          .render();x

setCentered works, setExpanded does not seem to do anything.  I would like the result to be similar to how the chart looks after clicking the expand button at the bottom of the card.

**Comment by jptheripper** [comment]
is this possible?

**Comment by jptheripper** [comment]
Thank you for the clarification.  I replied to the issue.  I do not believe
.setExpanded("O-6067").render() is working, or I am not understanding what
it should do.  I think it should expand as if you clicked the arrow at the
bottom of the node, but it does not, in the sample or my code.

Any advice is appreciated.  I have integrated this into a GIS Operations
Dashboard. Its amazing

[image: image]

**Comment by jptheripper** [comment]
Hello, just seeing if this is a bug or if i am doing something incorrectly

**Comment by bumbeishvili** [comment]
Hi, if you can prepare an online sample highlighting the issue you are having, I might be able to check it out

**Comment by bumbeishvili** [comment]
@jptheripper if you want children of those nodes to be expanded, you'll need to add _expanded property to all its children.
