### ISSUE TITLE
Adding a node that its input typed from the user in a form

### ISSUE THREAD

**Issue by Splashx0** [bumbeishvili/org-chart#277]
Please how can i add a button on every node when i click on this button  a form appears to the user to write data to make the new node

**Comment by bumbeishvili** [comment]
Hi, I think there was a similar questions asked already, suggest to look for them and link here in case others are also end up here

**Comment by Splashx0** [comment]
yeah its the same probleme as issue  #125 but i didnt find a solution :( i really need that

**Comment by bumbeishvili** [comment]
Do you need for to be updatable in the actual org chart or just a modal after button is clicked?

**Comment by Splashx0** [comment]
after i click on a node it displays me a modal input  to put the user inforamtion then click on submit so it add the new node

**Comment by Splashx0** [comment]
please how can i solve this :( i need it for my graduation project and im stuck for 3 days

**Comment by marcellino-ornelas** [comment]
@Splashx0 Is the issue that when after filling out your form information the new node doesn't appear? or whats happening exactly. Can you paste the error and a snippet? or Do you have a repo somewhere where I can see the code? 

Using react and this library could be a little difficult when trying to mix the two states together. 
have you seen this Stackblitz yet?

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-hdgvst?file=index.js,OrgChart.js,Counter.tsx

its using react and has adding node ability already integrated

**Comment by Splashx0** [comment]
> @Splashx0 Is the issue that when after filling out your form information the new node doesn't appear? or whats happening exactly. Can you paste the error and a snippet? or Do you have a repo somewhere where I can see the code?
> 
> Using react and this library could be a little difficult when trying to mix the two states together. have you seen this Stackblitz yet?
> 
> https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-hdgvst?file=index.js,OrgChart.js,Counter.tsx
> 
> its using react and has adding node ability already integrated

hello I already fix it , thank you man for your effort

**Comment by marcellino-ornelas** [comment]
Just in case anyone else wants to do something similar 😃 

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-fhqcje?file=index.js,OrgChart.js,Counter.tsx
