### ISSUE TITLE
Link radius

### ISSUE THREAD

**Issue by Maximaximum** [bumbeishvili/org-chart#279]
Hello!

Thanks for the awesome library, and for your support to Ukraine! We really appreciate that.

Would you be so kind to give me a hint on whether it is possible to override the link radius?

![image](https://github.com/bumbeishvili/org-chart/assets/5593500/f71a803e-ba54-4055-b859-6ca14919d8cf)

**Comment by bumbeishvili** [comment]
Yes, it's possible

You can override linkUpdate function and apply additional svg attributes (stroke-width in your case)

https://github.com/bumbeishvili/org-chart/blob/c8ebb0490ecfcf1424c16a8528a4a835d3efde53/src/d3-org-chart.js#L72

**Comment by Maximaximum** [comment]
Thanks for your fast feedback!

I'm talking about changing the **radius**, not the line **thickness**. Do you have any ideas on how to do that?

**Comment by bumbeishvili** [comment]
Ah, ok,
in that case you will need to override this specific function

https://github.com/bumbeishvili/org-chart/blob/c8ebb0490ecfcf1424c16a8528a4a835d3efde53/src/d3-org-chart.js#L191

This is the function that is responsible for the curvature 

https://github.com/bumbeishvili/org-chart/blob/c8ebb0490ecfcf1424c16a8528a4a835d3efde53/src/d3-org-chart.js#L1048

You can play with it here

https://observablehq.com/@bumbeishvili/curved-edges
