### ISSUE TITLE
Multiple roots support

### ISSUE THREAD

**Issue by Maximaximum** [bumbeishvili/org-chart#281]
**Is your feature request related to a problem? Please describe.**
I'm trying to render a tree with multiple roots (ie, render multiple trees in a single component), but I get a 'multiple roots' error.

**Describe the solution you'd like**
It would be great if we could render multiple roots on the same component, so that all the root nodes are located at the same top level of the hierarchy.

---

**Comment by bumbeishvili** [comment]
Org chart cannot have multiple roots (a.k.a. two parents for a single node)

If you just want multiple nodes displayed at the top, create a dummy node data which will be the parent of these nodes, and then hide this node and link with CSS or inside in nodeUpdate & linkUpdate methods
