### ISSUE TITLE
ReferenceError: Cannot access 'fn' before initialization Angular 14?

### ISSUE THREAD

**Issue by kapil26021994** [bumbeishvili/org-chart#286]
Hi Team,
I am using d3-org-chart for implementing org chart in our angular app with 14 version i have tried each and everything according to doc but after loading **Cannot access 'fn' before initialization ReferenceError:** below version for "d3-org-chart as well as d3 i am sharing my component code snippet i am not understand what's the issue can anybody help me on that how to fix above issue. can you please help me on that ?

 "d3": "5.15.1",
  "d3-org-chart": "^1.0.12",

```
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import   OrgChart from "d3-org-chart";  
import * as d3 from "d3";

@Component({
  selector: 'app-user-genealogy',
  templateUrl: './user-genealogy.component.html',
  styleUrls: ['./user-genealogy.component.scss']
})
export class UserGenealogyComponent implements OnInit {
  @ViewChild("chartContainer") chartContainer: ElementRef;
  chart;
  data:any;
  constructor() { }

  ngOnInit() {
    d3.json(
      'https://gist.githubusercontent.com/bumbeishvili/dc0d47bc95ef359fdc75b63cd65edaf2/raw/c33a3a1ef4ba927e3e92b81600c8c6ada345c64b/orgChart.json'
    ).then((data) => {
      this.data = data;
      this.chart = new  OrgChart();
      this.updateChart();
    });
  }

  updateChart() {
    if (!this.data) {
      return;
    }
    if (!this.chart) {
      return;
    }
    this.chart
      .container(this.chartContainer.nativeElement)
      .data(this.data)
      .svgWidth(500)
      .initialZoom(0.4)
      .onNodeClick((d) => console.log(d + ' node clicked'))
      .render();
  }

}
```

**Comment by bumbeishvili** [comment]
<img width="336" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/33a2d6c4-575b-4087-85e0-734133f25b50">

Notice brackets, probably this is an issue

**Comment by kapil26021994** [comment]
hi @bumbeishvili  i have already install that plugin but still same issue,can you tell me what we do for above issue?

**Comment by bumbeishvili** [comment]
@kapil26021994 please provide an online sample where the issue is reproduced.

You can fork angular integration sample and try to reproduce issue there, then I can check it
