### ISSUE TITLE
[QUESTION] Is there a way to prevent a node being collapsed?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [bumbeishvili/org-chart#287]
Is there a way to prevent a node being collapsed?

I've set this:

`    chart.buttonContent(({ node, state }) => null)`

Which stops the expand/collapse button showing, but it still collapses when I tap near where the button was.

**Comment by kokorevdev** [comment]
Hi, I've had the same problem and while I haven't found the "clean" solution yet, here is a workaround:

**1. Set the button content to null, as you have already done:**
`chart.buttonContent(({ node, state }) => null)`

2. Assign the chart to a variable and set the onButtonClick callback to null afterwards:
`const chart = new OrgChart().container('#chartDiv)...;
chart.onButtonClick = null;`

This should solve your issue.

**Comment by JeremyBradshaw7** [comment]
> chart.onButtonClick = null;

Ah, but I want some nodes expandable and others not, so I cannot use this approach.

**Comment by JeremyBradshaw7** [comment]
> In nodeUpdate you can check which nodes should be collapsible and then set pointer-events to none to the responsible element class (don't remember exact name)

`pointer-events` is already `null` on the `node-button-div` class:

![image](https://github.com/bumbeishvili/org-chart/assets/36155348/b1ee6425-b4b4-4a2f-9e1c-c6332d71c18f)

**Comment by bumbeishvili** [comment]
Click event is bound to .node-button-g, so either remove that or set pointer events to none

**Comment by JeremyBradshaw7** [comment]
Thanks will give that a go.

**Comment by JeremyBradshaw7** [comment]
To get it to work I had to set pointer-events on `.node-button-rect`:

`    .nodeUpdate(function (d, i, arr) {
      d3.select(this)
      if (d.data.name === '') { // conditionally prevent collapse
          d3.select(this)
        .select('.node-button-rect')
        .attr("style", "pointer-events:none");
      }
    })`

**Comment by JeremyBradshaw7** [comment]
Thanks for your help @bumbeishvili, have closed this now.
