### ISSUE TITLE
[QUESTION] Is there a way to set the zoom level?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [bumbeishvili/org-chart#288]
I can call `chart.fit()` to zoom in/out to make the chart fill the screen but is there a way to reset the zoom level to 1 and center? I'm looking to make a zoom toggle.

**Comment by bumbeishvili** [comment]
there are chart.zoomIn and zoomOut functions, you might want to use them

`
    zoomIn() {
        const { svg, zoomBehavior } = this.getChartState();
        svg.transition().call(zoomBehavior.scaleBy, 1.3);
    }
`

You can also get hands of inner state  and something like this should do the trick

```javascript
const { svg, zoomBehavior } = chart.getChartState();
 const desiredZoomChange = 1.5; // 50% zoom increase
 svg.transition().call(zoomBehavior.scaleBy, desiredZoomChange);
```
