### ISSUE TITLE
get node's data from NodeId

### ISSUE THREAD

**Issue by AnkushSarkar10** [bumbeishvili/org-chart#289]
Is there a way to directly access a node's data from its NodeId without iterating over all the data like this?

```
.onNodeClick((nodeid) => {
            dataFlattened.filter(data => {
               if (data.id === nodeid) {
                   console.log(data)
            }
      });
 })
```

**Comment by bumbeishvili** [comment]
I don't think so. If you worry about performance, you can use Map instead and access will be constant, I would not worry about it though (in this specific case)
