### ISSUE TITLE
`onNodeClick` impacts node collapse/expand behaviour

### ISSUE THREAD

**Issue by JeremyBradshaw7** [bumbeishvili/org-chart#290]
`onNodeClick` when implemented to highlight the clicked node seems to screw up node collapse/expand behaviour. Collapsed nodes seem to fly off the top of the screen instead of being collapsed into the parent, and on expansion again every child that was expanded is shown collapsed, so they all have to be expanded again one by one.

```
    .onNodeClick((d) => {
      chart.clearHighlighting();
      chart.setHighlighted(d.id).render();
    })
```

This method is firing on the node even when just clicking expand/collapse, so I think there is some auto-expansion happening inside the `setHighlighted` call, but I'm not sure. Can we avoid firing this method as well when the expand/collapse button is clicked?

**Comment by bumbeishvili** [comment]
I am aware of this behavior and was meaning to fix it someday. For the workaround you can attach custom click events in the nodeUpdate (where this refers to dom element) method and write your code in that

**Comment by JeremyBradshaw7** [comment]
Thanks @bumbeishvili that's actually what I ended up doing, calling this function via onclick:

```
  selectNode = function(id) {
    var attrs = chart.getChartState();
    var node = attrs.allNodes.find(d => attrs.nodeId(d.data) === id);
    // clear existing highlighting
    attrs.allNodes.forEach(d => {
      d.data._highlighted = false;
      d.data._centered = false;
    })
    // highlight and centre new node
    node.data._highlighted = true;
    node.data._centered = true;
    chart.update(attrs.root);
  }
```
