### ISSUE TITLE
search for a node through the data values of the node itself

### ISSUE THREAD

**Issue by corrado1970** [bumbeishvili/org-chart#294]
how can i lookup a node by the values of that node and focus it by expanding all parents and siblings

**Comment by bumbeishvili** [comment]
If you have a search box, roughly you need to do the following:

1. Listen to seach input change event
2. In the handler function, get chart data
3. Find all nodes which match your search and set _expanded to it (you can also use _selected)
4. rerender graph


Rough implementation

```javascript
function handleSearch(searchText){
  const data = chart.date();
   data.forEach(d=>{
   if(d.nameOrOtherProperty.includes(searchText)){
    d._expanded = true;  // if you just want expand
   d._selected = true;    // if you also want it to be selected, not remember if it's possible to select multiple nodes so not sure if this will work
     }
   })

chart.data(data).render()

}
```

**Comment by corrado1970** [comment]
1 node {value 10}
   2 node {value 20} 
      3 node {value 30} 
      4 node {value 40 }
5 node {value 50} 
   6 node {value 60} 

if i want to search value 30 (passed value at my function)  i want expand parents at the end my node.
it's possible to do this?

**Comment by bumbeishvili** [comment]
Yes, you can  use following code. Probably not precise, but it will give you directions

```
function handleSearch(searchText) {
  const data = chart.data();
  data.forEach(d => {
    if (d.value.includes(searchText)) {
      d._expanded = true;  // if you just want expand
      d._selected = true;    // if you also want it to be selected, not remember if it's possible to select multiple nodes so not sure if this will work
    }
  })

  chart.data(data).render()

}
```
