### ISSUE TITLE
Is there a way to set a background image for the chart?

### ISSUE THREAD

**Issue by chartuser** [bumbeishvili/org-chart#296]
Hello, is there a way to set a background image for the chart and have it in the exported image file?

**Comment by bumbeishvili** [comment]
I think so, but it needs to be set as base64 and inner style

![image](https://github.com/bumbeishvili/org-chart/assets/6873202/521f2d17-e8d2-43e4-9342-7ebc2f4c1cd0)

You can see how it works here

https://stackblitz.com/edit/web-platform-o5t1ha?file=index.html

**Comment by chartuser** [comment]
That works, thanks!
