### ISSUE TITLE
How to change node button width and height

### ISSUE THREAD

**Issue by vakers2** [bumbeishvili/org-chart#298]
Hello, in my org chart I set custom text for node button which can be pretty long. I would like to ask how can I increase node button's width so that text can be fit inside?

**Comment by bumbeishvili** [comment]
Overriding those parameters should do the trick (`chart.nodeButtonWidth(500)`)


https://github.com/bumbeishvili/org-chart/blob/6080ad592cc1d5d4d257b22ab34a912bd7dddbc2/src/d3-org-chart.js#L58-L61
