### ISSUE TITLE
Dropdown overlapping from the nodes

### ISSUE THREAD

**Issue by JowenGonzales** [bumbeishvili/org-chart#299]
So I've add a dropdown inside the nodes and it seems to be overlapping from other nodes. I've already tried using z-index in my dropdowns

![image](https://github.com/bumbeishvili/org-chart/assets/80776754/ea65cee4-020b-4fde-a049-45007a24c50a)

**Comment by bumbeishvili** [comment]
Try for the node, for which dropdown is opening 

`d3.select(this).raise()` - `this` to node html element (it does inside `nodeUpdate`) method

**Comment by JowenGonzales** [comment]
thanks, it works perfectly :)
so here is the solution

`.nodeUpdate(function (d, i, arr) {
        d3.select(this).raise().render();
 })`

**Comment by JowenGonzales** [comment]
sorry for the late response, but it seems like it wasn't working. here is my code:
```
.nodeUpdate(function (d, i, arr) {
    d3.select(this).raise();
    console.log("Raised");
})
```
I've tested that the nodeUpdate only calls when the load pages at the first time and not when the dropdown shows, so maybe the reason is that when i click the node it doesn't raise it. Do you have any suggestions in mind?

**Comment by bumbeishvili** [comment]
Yes, that's the reason. What you did is to raise each node, so nothing changed, but you need to raise a specific node for which dropdown is opening

**Comment by JowenGonzales** [comment]
ok i get it ..thank you very much, it worked
