### ISSUE TITLE
extra links

### ISSUE THREAD

**Issue by gtorrezani** [bumbeishvili/org-chart#3]
It would be possible to create extra links
Example: https://balkangraph.com/OrgChartJS/Demos/clink

**Comment by bumbeishvili** [comment]
Currently it is not possible but it is pretty easy to modify source code to add that functionality

**Comment by bumbeishvili** [comment]
FYO, in the new, coming version, we will have multi links functionality. You will be able to specify connections with labels between any nodes

https://github.com/bumbeishvili/d3-organization-chart/blob/ee33e5ed64afa0be1ca2c695ed4d525aae67f98e/tree.html#L138

It will look like this

<img width="1672" alt="Screenshot 2021-07-29 at 17 46 20" src="https://user-images.githubusercontent.com/6873202/127504411-b50ab9a4-493a-4e4f-84b1-ce4df2f6e8c2.png">

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
