### ISSUE TITLE
Is there an option to add sibling nodes?

### ISSUE THREAD

**Issue by agtenr** [bumbeishvili/org-chart#300]
I am trying to create a layout where there is also a possibility of siblings (see screenshot below). So when I have a vertical layout, the sibling should be added horizontally? I noticed that there is a method on the chart object '.siblingsMargin()'. I tried adding a siblingId to the node objects, but this doesn't seem to work. Can you tell me if this is supported? Thanks in advance

![image](https://github.com/bumbeishvili/org-chart/assets/19812462/6dddf2bf-69c9-459d-be2d-1d81dbe9f48d)

**Comment by bumbeishvili** [comment]
Hi, could not understand the issue.

Can you let me know how it works now and how would you want it to work?

**Comment by agtenr** [comment]
To give more context, I'm building an organizational sturcture where for each manager the n-1 are rendered below. Some managers have an assistant. I don't want to render the assistant as a child below the manager but as a sibling next to the manager. Something like this:
![image](https://github.com/bumbeishvili/org-chart/assets/19812462/8e66d848-d2c0-40a8-a55d-f550ff727ee7)

**Comment by bumbeishvili** [comment]
Ah ok, the org chart does not support a similar layout, but for the workaround, you can attach assistant data to the manager.

Have a different width for each manager and in node content method generate different HTML for Managers (it will include manager and assistant cards)

You'll also probably want to override where the link joins to manager nodes.

If I remember correctly this is the property responsible

https://github.com/bumbeishvili/org-chart/blob/6080ad592cc1d5d4d257b22ab34a912bd7dddbc2/src/d3-org-chart.js#L343

**Comment by agtenr** [comment]
Thanks for the information. I was indeed able to solve it like that. I will close. 

Also, thanks for all the hard work that went into the creation of this component!

**Comment by agtenr** [comment]
Yes sure. I basically extended my data model so that each node has all the needed data for the sibling. The most work went into formatting the data correctly but unfortunately this is something I cannot share. The node model looks like this:
```
export interface IPersonItem {
  id: string;
  parentId: string | null;
  personId: string;
  managementAssistant: {
    id: string;
    personId: string;
  };
}
```

Then in the orgChart (I'm using react) I use the ReactDOM to render a custom React component.
```
.nodeContent((node: HierarchyNode<IPersonItem>) => {
  return ReactDOMServer.renderToStaticMarkup(
    <OrgNode node={node} />
  );
})
```

Lastly, in de OrgNode component I just render different HTML depending if there is a managementAssistant or not:
```
return (
  <>
    <div>
      {node.data && (
        <div className={classNames.container}>
          <div className={classNames.info}>{node.data.personId}</div>
        </div>
      )}
      {node.data.managementAssistant && (
        <div className={classNames.container}>
          <div className={classNames.info}>{node.data.managementAssistant.personId}</div>
        </div>
      )}
    </div>
  </>
);
```

Hopefully this helps

**Comment by WorkPedroCampelo** [comment]
Just in case this helps somebody, my aproach to this problem was quite different, I needed a sibling node to show some text, I ended up creating a flex container  to make something like this.
![image](https://github.com/user-attachments/assets/d2f53c43-67bc-41ba-858a-2faf56051128)

Its a container with 3 divs inside, one for the node, another that has only a width and a border bottom red and the text (with a red border left)

It aint exactly what this issue was about but I hope this may be helpful for soomebody :)
