### ISSUE TITLE
SVG Export: Uncaught ReferenceError: h is not defined

### ISSUE THREAD

**Issue by Jack-Fawcett** [bumbeishvili/org-chart#306]
[Description]
When using export SVG function reports an error when used:
`
d3-org-chart@3.0.1-next.1:69 Uncaught ReferenceError: h is not defined
    at t.OrgChart.downloadImage (d3-org-chart@3.0.1-next.1:69:24027)
    at t.OrgChart.exportSvg (d3-org-chart@3.0.1-next.1:69:23585)
    at HTMLButtonElement.onclick ((index):1:7)
`

1. Go to [example page for export function](https://stackblitz.com/edit/js-ue1cpj?file=index.html)
2. Click on EXPORT SVG button

Expected behavior: Download SVG file

Desktop
 - OS: Mac
 - Browser: chrome

**Comment by bumbeishvili** [comment]
It seems the issue has something to do with the minified file 

![image](https://github.com/bumbeishvili/org-chart/assets/6873202/a48b5c88-d8b9-4df3-9f6d-5a701530cc24)

In the original version, h (serializeString) is not in the else section, so it's accessible

<img width="850" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/8af88a20-88c3-4b8b-ab17-7192061d79eb">

**Comment by Jack-Fawcett** [comment]
@bumbeishvili is there a way to avoid this error in the minifying process?

**Comment by bumbeishvili** [comment]
I have no idea, If you can, just use this class

https://github.com/bumbeishvili/org-chart/blob/6080ad592cc1d5d4d257b22ab34a912bd7dddbc2/src/d3-org-chart.js#L23

And don't forget to include d3 and flextree

```
 <script src="https://d3js.org/d3.v7.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/d3-flextree@2.1.2/build/d3-flextree.js"></script>
```
