### ISSUE TITLE
Start with empty chart

### ISSUE THREAD

**Issue by DStein4711** [bumbeishvili/org-chart#308]
I want to start with an empty chart and let the user add node over an interface.
I got it working with one node in the data-option and then adding node with the addNode-Function. But if I leave the data empty, it is not working.

Is this possible and how?

**Comment by bumbeishvili** [comment]
Made relevant changes. You can use `3.1.1` version of the org chart and addNode will be able to add a root node from now on

**Comment by DStein4711** [comment]
Thank you. I tried it, but can't get it working.

I'm getting the following Error, when adding the first Node:
d3-org-chart_3.1.1.js:69 Uncaught TypeError: a.generateRoot is not a function
    at t.OrgChart.addNode (d3-org-chart_3.1.1.js:69:7863)

**Comment by bumbeishvili** [comment]
I've tested it here and it works as expected

https://stackblitz.com/edit/js-bict6t?file=index.html

Clicking add root node adds root node. Clicking add child node adds child node

**Comment by DStein4711** [comment]
There was a typo in my code. Now it's working.

Great! Thank you!
