### ISSUE TITLE
link height / connection

### ISSUE THREAD

**Issue by n1crack** [bumbeishvili/org-chart#309]
Hey,

How can I fix this part? It is from the 'search' example, the only thing I change is compact(false). 

![image](https://github.com/bumbeishvili/org-chart/assets/712404/d02e53b5-7106-4a15-a35d-e20cbc4aca69)

**Comment by bumbeishvili** [comment]
I think increasing childrenMargin should do the trick

<img width="464" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/6d443a3b-169a-4ec8-9b81-80718fab13ef">

If it won't work, fork and post the sample with the issue reproduced and I can take a look.

**Comment by n1crack** [comment]
yes that worked. It increases the space between nodes but it is better.
