### ISSUE TITLE
@types/d3-org-chart is not updated for the latest version

### ISSUE THREAD

**Issue by moeindev** [bumbeishvili/org-chart#314]
**Seems like the types package is not updated**

**To Reproduce**
1.install the latest version => 
`"d3": "^7.8.5",
    "d3-org-chart": "^3.1.1",`
2. install the latest type version => 
`"@types/d3": "^7.4.1",
    "@types/d3-org-chart": "^2.6.4",`

**Expected behavior**
It should work without any issues

**Issue**
As you mentioned in the #213 , the typo `neightbourMargin` has changed but When I use the latest version in my angular project, the `neighbourMargin` is not defined along with other changes 

Angular version => 14.2.0

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser: Chrome
 - Version: 117.0.5938.150 (Official Build) (64-bit)

**Comment by bumbeishvili** [comment]
I am not maintaining typings for the library (and nor intend to maintain it in the future)

@m-gallesio has worked on it if I remember correctly.

**Comment by moeindev** [comment]
Well in that case, I'll see what I can do 👌🏼

**Comment by moeindev** [comment]
Here is the Merge request for the types, I added some documents and the missing methods for the new version: 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66996
@m-gallesio please take a look, 

And since there is no point of having this issue open, I'm closing it.
