### ISSUE TITLE
children of at the same level are not aligned 

### ISSUE THREAD

**Issue by akshay-developer-2021** [bumbeishvili/org-chart#317]
**Describe the bug**
children of different parents, at the same level, are not aligned if one of those parents has button content.

**To Reproduce**
1. Go to https://stackblitz.com/edit/web-platform-nmjezm?file=index.html
2. look for children at the same level, ( like the screenshot below, look for "Laura")

**Expected behavior**
children at the same level should be aligned.

**Screenshots**
<img width="724" alt="Screenshot 2023-10-24 at 8 27 38 AM" src="https://github.com/bumbeishvili/org-chart/assets/86369928/29a76e80-69f5-4f27-bb31-470a5d25b45b">

**Desktop (please complete the following information):**
 - OS: Mac Ventura 13.4.1 (22F82)
 - Browser Version 118.0.5993.88 (Official Build) (x86_64)
 - Org chart Version - 3.1.1

**Comment by bumbeishvili** [comment]
Hi, they aren't on the same level. On the left nodes are one level up, that's the behavior of compact layout

You can set `chart.compact(false)` if you want non compact layout.

**Comment by akshay-developer-2021** [comment]
Hi,

I want to keep the compact layout but at the same time I need to get rid of the small 10px gap which making it look a little misaligned. Is there a way I can shorten the link by some amount? or change the start point of the link whenever there is an expand/collapse button?

**Comment by bumbeishvili** [comment]
Ah, in that case, you have to play with the following properties

https://github.com/bumbeishvili/org-chart/blob/61d458c028ffeb0e023dfe675f137b002a5209b2/src/d3-org-chart.js#L54-L58

**Comment by akshay-developer-2021** [comment]
conditionally changing the childrenMargin work. 

`
.childrenMargin((d) => {
          return d.children ? 45.5 : 60;
        })
`
