### ISSUE TITLE
collapsing root node then trying to expand a descendent node with chart.setExpand throws Uncaught TypeError

### ISSUE THREAD

**Issue by emmanuelrflores** [bumbeishvili/org-chart#32]
pre-req: open chrome dev tools
STR: 
Go to the demo site https://observablehq.com/@bumbeishvili/d3-v5-organization-chart
Collapse root node (Ian Devling)
Click on button `expand node with id O-111`

Expected Result: Nodes should expand, no errors thrown
Actual Result: Error thrown in console; nothing happens. 

The error is being thrown from this line https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L1074

The root has no children when everything is collapsed.

**Comment by bumbeishvili** [comment]
Right, this is a bug, I will look into it once I will find a time

Thanks for reporting

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
