### ISSUE TITLE
Few general questions from newb! - chart, photos, data.

### ISSUE THREAD

**Issue by Kumite89** [bumbeishvili/org-chart#320]
Hello everyone! 

First of all, I would like to thanks for amazing work which you were done  (@bumbeishvili )! The chart is awesome! Secondly, please bear in mind I am a new in coding world and community, hence my level of understanding things could be not as you (professionals) .  I already made some simple website, and I not perfectly, but I know and understand CSS and HTML (nothing about JavaScript). In advance thanks for understanding a let move to questions & problems.

I would like to create chart with this view: https://stackblitz.com/edit/web-platform-3gwnsg?file=index.html 

but as source of inserted data I want to use not csv file but code below: 
`const data = [
    { customId: 1, customParentId: null, customName: 'node1' },
    { customId: 2, customParentId: 1, customName: 'node2' },
    { customId: 3, customParentId: 1, customName: 'node3' },
  ];`

1. In mentioned solution can I added photos - in the same line as different data?
2. If the photos of people are store in our internal server they will appear ?
3. I followed instruction in video, but text changed but photos didn't appear. 

BR,
Mat

**Comment by bumbeishvili** [comment]
> In mentioned solution can I added photos - in the same line as different data?
I think so, but you certainly need js knowledge

> If the photos of people are store in our internal server they will appear ?
As long as photo is accessible from browser, yes

> I followed instruction in video, but text changed but photos didn't appear.
Don't know why

Did you follow the instructions in the video linked bellow? This is a different video and it's for people who don't know coding, they can build org charts directly on their website and integrate them into their websites using iframe.

https://youtu.be/0jYtNOUJW_8?si=JwjdR6pWvSjPNBfU

**Comment by Kumite89** [comment]
Photos are storage locally - SharePoint and they aren't loading, look at the screen:
![image](https://github.com/bumbeishvili/org-chart/assets/75325926/ad3e5f72-875f-4719-90dd-ac7a3720e0b8)

yes I followed the instructions, but still doesn't work. I want to add code SharePoint. I already added this code: `<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/d3-org-chart@3.0.1"></script>
<script src="https://cdn.jsdelivr.net/npm/d3-flextree@2.1.2/build/d3-flextree.js"></script>

<div class="chart-container"></div>

<script>
  const data = [
    { customId: 1, customParentId: null, customName: 'Mateusz' },
    { customId: 2, customParentId: 1, customName: 'Sorin' },
    { customId: 3, customParentId: 1, customName: 'Mijo' },
	{ customId: 3, customParentId: 2, customName: 'Kazi' },
	{ customId: 3, customParentId: 2, customName: 'Dyzio' },
	{ customId: 3, customParentId: 2, customName: 'Kazi1' },
	{ customId: 3, customParentId: 2, customName: 'Dyzio1' },
	{ customId: 3, customParentId: 2, customName: 'Kazi2' },
	{ customId: 3, customParentId: 2, customName: 'Dyzio2' },
	
  ];

  new d3.OrgChart()
    .nodeId((dataItem) => dataItem.customId)
    .parentNodeId((dataItem) => dataItem.customParentId)
    .nodeWidth((node) => 100)
    .nodeHeight((node) => 100)
    .nodeContent((node) => {
      return `<div 
        style="background-color:aqua;width:${node.width}px;height:${node.height}px"
      > 
           ${node.data.customName}
       </div>`;
    })
    .container('.chart-container')
    .data(data)
    .render();
</script>'

and I have i have the this result:
 
![image](https://github.com/bumbeishvili/org-chart/assets/75325926/0cb110b2-481c-41f5-a559-bc3fd9747365)

If you can support me how can i customize and change frontend I will be grateful. If It is demanding process tell me, I will looking for different solution.

And please send me link I want to buy a coffee for you at least!

**Comment by Kumite89** [comment]
David,

Please let me know how much you will charge to align the chart to my needs?
I would like to implement this, but of course company doesn't have the
money for this, so I may be able to pay for this from my own pocket.



pon., 30 paź 2023 o 18:29 David Bumbeishvili ***@***.***>
napisał(a):

**Comment by bumbeishvili** [comment]
https://stackblitz.com/edit/web-platform-qz8dlm?file=index.html

**Comment by Kumite89** [comment]
Ok thanks a lot! More or less I know how to change data which appear in the boxes but, please let me know how can I add photo:
`{
          customId: 1,
          customParentId: null,
          customName: 'Mateusz',
        },`  
        
        is any line of code what can I add to indicate the photo?

**Comment by bumbeishvili** [comment]
@Kumite89 if you just add `imageUrl` property in that object, it will automatically try to load images, since it's specified in nodeContent

![image](https://github.com/bumbeishvili/org-chart/assets/6873202/954826e7-64d2-4653-b526-342345b11f55)
