### ISSUE TITLE
+/- buttons not centered in Firefox

### ISSUE THREAD

**Issue by emmanuelrflores** [bumbeishvili/org-chart#33]
On Firefox 68.12.0 it appears that the '+' and '-' sign are not centered in the circle. I'm seeing this in both mac and windows. At first I thought this had to do with how we were doing some styling in the nodes, but I went to the [observable d3 org chart](https://observablehq.com/@bumbeishvili/d3-v5-organization-chart) to look at the demo and it's doing the same there. 

see the attached screenshot. 

<img width="907" alt="Screen Shot 2020-09-28 at 5 50 38 PM" src="https://user-images.githubusercontent.com/348952/94497178-a5f4f500-01b3-11eb-80a2-ff4e9de7b1d5.png">

**Comment by bumbeishvili** [comment]
Thank you, I will look into it

**Comment by Dvoretska** [comment]
Hi! It's not aligned in Chrome as well.
![Screenshot from 2021-01-04 12-56-13](https://user-images.githubusercontent.com/27019320/103530357-ebe6e680-4e8f-11eb-92b2-b2d4a1f208ad.png)

**Comment by Dvoretska** [comment]
Suggested fix: https://github.com/bumbeishvili/d3-organization-chart/pull/46/files

**Comment by bumbeishvili** [comment]
@Dvoretska thank you for opening PR, I'll test it once I will have time and will merge it then

**Comment by bumbeishvili** [comment]
In the new version, we will have new icons for expand collapse, and that button will be user-configurable as well

<img width="802" alt="Screenshot 2021-07-18 at 00 36 51" src="https://user-images.githubusercontent.com/6873202/126048822-52b41dfc-1fbd-4897-a3ae-e248b2c9045d.png">

1. https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L626

2. https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L65

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
