### ISSUE TITLE
Multiple parents only with leaf nodes possible?

### ISSUE THREAD

**Issue by PatK19** [bumbeishvili/org-chart#340]
Hi, i want to use this library in my Master's thesis. 
In an existing project it is possible for a node to have multiple parents (Summarization has the same ID).

![Bild1](https://github.com/bumbeishvili/org-chart/assets/50517642/9d442acd-98dd-432d-85f3-4602ba383c9e)

I now want to use the same implementation with a bigger database where also inner nodes can have multiple parents. However when trying to load in the data (in the same way) i get the Unhandled Runtime Error "Error: ambiguous: {NodeId}". 
Is this library only able to process multiple parents for leaf nodes?

**Comment by bumbeishvili** [comment]
This library can only process strict hierarchy (one parent, multiple children), multiple parents aren't possible

**Comment by PatK19** [comment]
Ok thanks for the info. 
Do you then understand how my colleague was able to use it with mutliple parents (as shown in the screenshot)?

**Comment by bumbeishvili** [comment]
This is not multiple parents, every node in here only has a single parent

**Comment by PatK19** [comment]
Summarization at the bottom has both the parents Information Extraction and Text Generation tough

**Comment by kanth609** [comment]
@PatK19 , do you got to know how your colleague has formed this chart? like placing same node under different parent nodes?

**Comment by PatK19** [comment]
@kanth609 in this case there is no issue as the parentNodeID - childNodeID combination is unique.
The data for this graph came from the Database (Neo4j) where multiple connections are allowed. 
I was also able to use it for multiple parents by multiplying the parent nodes and adding a unique identifier (like _001) to the id. This surely is not optimal, but was sufficient for my usecase.
