### ISSUE TITLE
nodeButtonX

### ISSUE THREAD

**Issue by mamjerez** [bumbeishvili/org-chart#342]
You can change the position of all nodeButtons with .nodeButtonX(() => -20).
 Is it possible to change the position of each nodeButtonX individually for each node?
 
 Thanks

**Comment by bumbeishvili** [comment]
Yes, it works in the same way as `nodeContent`

```javascript
chart.nodeButtonX((d)=>{
    if(d.id=='node1) return 20
    if(d.id=='node2') return 30;
   return 6-
})
```

**Comment by mamjerez** [comment]
Thank you very much for your quick and effective response. It works perfectly.
