### ISSUE TITLE
Assistant Node 

### ISSUE THREAD

**Issue by mnurichsan** [bumbeishvili/org-chart#352]
Before asking, I would like to express my gratitude for the existence of this library. It's great, thank you.

is it possible to create a chart like this? with Assistant node in neck ?

<img width="767" alt="Jepretan Layar 2024-01-25 pukul 09 30 35" src="https://github.com/bumbeishvili/org-chart/assets/41501730/61e9203c-1901-479b-b61e-d7b2286e6ac1">

thanks!

**Comment by bumbeishvili** [comment]
Hi, not directly, but there can be workaround

#300

**Comment by mnurichsan** [comment]
> Hai, tidak secara langsung, tapi ada solusinya
> 
> #300

is it possible for certain nodes ?

**Comment by bumbeishvili** [comment]
You can change node width and node height of any node and you have the ability to have any content inside any node, so potentially you can do it for any node

**Comment by mnurichsan** [comment]
> You can change node width and node height of any node and you have the ability to have any content inside any node, so potentially you can do it for any node

any example to create Assistant node ?

**Comment by bumbeishvili** [comment]
Not that I am aware of

**Comment by mnurichsan** [comment]
i see, Thanks for the information..
i will close the issue
