### ISSUE TITLE
When moving the diagram, there tends to be a smudge of colors left behind

### ISSUE THREAD

**Issue by JamesCovar** [bumbeishvili/org-chart#362]
**Describe the bug**
When moving the diagram, there tends to be a smudge of colors left behind

**To Reproduce**
1. Open Safari (It only happens in Safari) 
2. Move the diagram and look around
4. You will see colored spots from the diagram 

**Screenshots**
<img width="532" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/40534772/5728cf97-acc7-494e-815b-08c9bba711e5">

<img width="466" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/40534772/0cfdee64-1766-49f7-9674-1aa8b1c808f9">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: d3-org-chart: "3.0.1"

**Comment by bumbeishvili** [comment]
Safari has that bug, you have to make sure that all content stays within defined width and height(and not overflow) and no absolute positioning is used. You can utilize margins for that

**Comment by JamesCovar** [comment]
Oh, I see. Thanks for your prompt response, @bumbeishvili 
I'll keep it in mind
