### ISSUE TITLE
How to Expand/Collapse onclick of Entire Node, not just the special button

### ISSUE THREAD

**Issue by mzhukovs** [bumbeishvili/org-chart#366]
To make it easier for users to expand or collapse a node, especially when zoomed out a bit, I was trying to make it such that when the node is clicked ANYWHERE (not just the special, designated button) it would do so - how to achieve this? Tried using chart.onNodeClick() method coupled with setExpanded(node.id).render() but nothing happens.

Would appreciate any insight on this. And thanks to the creators/maintainers for the amazing library - truly great stuff.

**Comment by bumbeishvili** [comment]
This is the code which is invoked after the designated button
```javascript
.on("click", (event, d) => this.onButtonClick(event, d))
```

`event` is `click` event, `d` is the data. So I guess you could add your own event listener in `nodeUpdate` method, and the invoke this method in the handler

```javascript
chart.nodeUpdate(function(){
  d3.select(this).select(`yourElementSelector`).on('click',(e)=>chart.onButtonClick(e,d))
})
```
