### ISSUE TITLE
make svg responsive

### ISSUE THREAD

**Issue by sidyes** [bumbeishvili/org-chart#37]
Hey, it's me again. ;-)

Is there a way to make the org chart responsive or to be more precise: to make the canvas responsive?
Once resizing the browser window the canvas does redraw itself. Is there a way to force this without listening to the window resize event and call the `render` method again?

**Comment by bumbeishvili** [comment]
You could move this part - https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L334

  In a new class method called  `resizeGraph` for example

and then just invoke `chart.resizeGraph()` in your app

**Comment by sidyes** [comment]
Alright, but I want still to depend on your project. Do you have plans in `v2` to provide more methods for the outside to use like for example a resize method?

**Comment by bumbeishvili** [comment]
No, I don't have similar plans, but I think I can easily make that part optional for v2 since it will offer more flexibility

So,
* I'll expose a method for resizing (like I suggested above)
* I'll introduce parameter for enabling or disabling `automatic resize detection` 

But v2 version depends on my free time, which I don't expect to have in near future, so I  don't know exactly when I will start working on v2 features

I'll keep this issue open for a remainder

**Comment by ebitsdev** [comment]
Hello,

I am trying to make the generated chart responsive but it is not working. Below is the code I am using. All I get is a black rectangle covering the chart area when resizing the window.

What I am doing wrong? Can you please help with this?
``` 
function resizeGraph(container, width, height) {    
    
    let svg = container.selectAll('svg').data([null]);
    svg = svg.enter().append('svg')
            .merge(svg) 
            .attr('width', width)
            .attr('height', height)
    
    const g = svg.selectAll('g').data([null]);
        g.enter().append('g')
            .merge(g) 
            .attr('width', width)
            .attr('height', width)                    
    const rect = g.selectAll('rect').data([null]);
        rect.enter().append('rect')
            .merge(rect) 
            .attr('width', width)
            .attr('height', height)                    

}
```
And I am calling it as follows inside the render method:
```
            d3.select(window).on('resize.' + attrs.id, function () {               
                resizeGraph(attrs.svg, attrs.svgWidth, attrs.svgHeight)                
            });
```

**Comment by bumbeishvili** [comment]
So, v2 versions are already in progress and about 50% of features are already done

In the new version, we will be listening to resize events and automatically adjusting SVG width (not height)

https://github.com/bumbeishvili/d3-organization-chart/blob/ebd5568321b91f10df4d84f090ec6c562a1784f5/src/d3-org-chart.js#L343

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
