### ISSUE TITLE
Mobile rendering issue

### ISSUE THREAD

**Issue by nemanja-hallokarla** [bumbeishvili/org-chart#378]
Hi,

Diagram is perfectly working in my angular app. Even responsive version tested in browser. But on real device,diagram is not rendered properly, as you can see custom component used for nodes is stucked in top left corner while technicaly is still there and I can move it around. Any ideas why this happens and how to fix it

**Comment by bumbeishvili** [comment]
Hi, this is most probably related to Safari browser

The fix is not to overflow content out of defined width and height and not to use absolute positions, but utilize negative margins instead for the same effect

https://github.com/bumbeishvili/org-chart/issues?q=safari

**Comment by nemanja-hallokarla** [comment]
@bumbeishvili  thanks for the answer. I didn't use safari, but yes problem is there also on ios and chrome.  On android I have no problem. I am not using absolute positioning, but I have overflow: hidden on parent div since I use dynamic width. I will try to find solution from link you provided

**Comment by bumbeishvili** [comment]
> but yes problem is there also on ios and chrome

Chrome on ios is just a safari wrapper
