### ISSUE TITLE
On applying zoom behaviour, setHighlighted Method no longer centers the node

### ISSUE THREAD

**Issue by saaagarsingh** [bumbeishvili/org-chart#382]
Before submitting an issue, please make sure to check whether the similar question was asked before. 
You can search for it here - https://github.com/bumbeishvili/d3-organization-chart/issues

When I'm applying zoom behaviour on my chart and using the setHighlighted method to highlight a node It no longers supports the transform of the chart.

Is there a way to use both the functionality without any issue?

**Comment by bumbeishvili** [comment]
@saaagarsingh  can you reproduce issue with the online sample? You can fork and extend one of the examples linked in readme

**Comment by saaagarsingh** [comment]
@bumbeishvili Thanks for the reply. I have resolved that issue.

**Comment by saaagarsingh** [comment]
resolved.
