### ISSUE TITLE
How to get graph back to initial zoom/position

### ISSUE THREAD

**Issue by marcellino-ornelas** [bumbeishvili/org-chart#383]
## Description

👋🏽 Im trying to get the graph to go back to the initial zoom & position it was in when it was first rendered. When initially rendered, the top most root node is in the center of the screen but at the top of my elements container. This makes the graph nice and easy to see. 

I tried to use `fit()` but it always position the whole graph in the center of the screen not just the root node like on initial render and zoom level is always more out.

I think I need something like this but haven't gotten anything to work yet 🤔 

```
attrs.centerG.attr("transform", () => {
                return attrs.layoutBindings[attrs.layout].centerTransform({
                    centerX: calc.centerX,
                    centerY: calc.centerY,
                    scale: attrs.lastTransform.k,
                    rootMargin: attrs.rootMargin,
                    root: attrs.root,
                    chartHeight: calc.chartHeight,
                    chartWidth: calc.chartWidth
                })
            });
```

**Comment by bumbeishvili** [comment]
@marcellino-ornelas 

`fit` function also receives  some arguments:
```javascript
    chart.fit({
      animate: true,   // animate when fitting
      scale: false,      // Don't change the current scale
      nodes: centeringNodes,  // Fit current screen without changing scale around centering nodes
    });
```

Utilizing above, you can find nodes with specific IDs and center the chart around it, mimicking initial render

```javascript
  function centerSomeNodes() {
    const centeringNodes = chart
      .getChartState()
      .allNodes.filter((d) => ['100', '114', '120'].includes(d.data.id));

    chart.fit({
      animate: true,
      scale: false,
      nodes: centeringNodes,
    });
  }
```

Here is a working sample - https://stackblitz.com/edit/js-cjlevq?file=index.html

**Comment by marcellino-ornelas** [comment]
Thank you for the fast reply @bumbeishvili 🙌🏽 

Unfortunately it didn't fit my exact need 1:1 but was definitely better than the original `fit()`. In your solution the zoom level was left the same which I needed it to go back to `scale(1)`.

I ended up getting zoom to go back to normal with. 

```tsx
const zoom = chart.zoomBehavior();

/**
 * Scale back to the inital zoom level
 */
chart
    .getChartState()
    // @ts-expect-error `transition` is available on d3 Selection https://d3js.org/d3-zoom#zoom_transform
    .svg.transition()
    // @ts-expect-error `scaleTo` is available on `zoomBehavior` https://d3js.org/d3-zoom#zoom_scaleTo
    .call(zoom.scaleTo, 1);
```

This took me a while to get right so I just left the position the same for now 😆 Thank you again 🙏🏽
