### ISSUE TITLE
Error: multiple roots

### ISSUE THREAD

**Issue by walissonwaal** [bumbeishvili/org-chart#386]
It is not possible to have multiple nodes in root

In the hierarchy of the company for which I am implementing the organization chart, there are two people at the highest level, which means that there are two nodes at the root of the organization chart.

It would be quite interesting if the library didn't have this limitation.

**Comment by bumbeishvili** [comment]
@walissonwaal  you can add one dummy node at the top and hide it during drawing, this way you can simulate multiple roots.

**Comment by taruntadikonda** [comment]
@bumbeishvili How to hide a node. Can you provide a example.

**Comment by bumbeishvili** [comment]
@taruntadikonda check the multi roots example in here

https://github.com/bumbeishvili/org-chart?tab=readme-ov-file#features

**Comment by taruntadikonda** [comment]
I am using a angular project. In the linkUpdate and nodeUpdate event emitters `this` refers to the DOM element of the node or the link. Is there any equivalent thing to get the DOM element in Typescript.
