### ISSUE TITLE
Mix compact and non-compact mode

### ISSUE THREAD

**Issue by MilicaJovanovicIngsoftware** [bumbeishvili/org-chart#390]
Hi @bumbeishvili,
Is there any possibility to mix compact and non-compact mode, for example, to render first level with compact mode and for all other levels to have compact mode on?

Thanks in advance.

**Comment by bumbeishvili** [comment]
Hi, no, it's not possible without doing manual adjsutments

**Comment by MilicaJovanovicIngsoftware** [comment]
Thanks for quick answer. What kind of manual adjustments do you mean? Changing the source code, or I can do it inside my code?

**Comment by MilicaJovanovicIngsoftware** [comment]
Thanks for quick answer. What kind of manual adjustments do you mean? Changing the source code, or I can do it inside my code?

**Comment by bumbeishvili** [comment]
No, it will require changing the source code
