### ISSUE TITLE
Can I have menu option having multiple items on right side of each node?

### ISSUE THREAD

**Issue by sandipeq** [bumbeishvili/org-chart#396]
I need menu option having multiple items. Where menu should be right side of each node. So is this kind of feature or functionality is available or any workaround solution for same.

Response on this is highly appreciated, Thanks in advance!!

![Screenshot 2024-05-02 223652](https://github.com/bumbeishvili/org-chart/assets/104617814/3202e1b7-91a8-4ca4-bcc9-c4f4a1e08c5e)

**Comment by bumbeishvili** [comment]
Hi, you are supposed to implement that feature by yourself. In `nodeUpdate` you have access to current dom element (`this`) of the node, which gives you ability to add interactivity to node elements

**Comment by sandipeq** [comment]
yes, exactly I wanted to implement that feature by myself. Can you help me out if any live/demo example for same?

Thanks @bumbeishvili for you reply.
