### ISSUE TITLE
Unsafe Use of Eval triggers CSP.

### ISSUE THREAD

**Issue by michael-lumley** [bumbeishvili/org-chart#40]
The use of naked `eval()` calls is triggering a CSP error when I try to use this library. I have submitted a PR here: https://github.com/bumbeishvili/d3-organization-chart/pull/39 to address the issue.

**Comment by bumbeishvili** [comment]
Let me check more about this Error.

 I can't accept PR, since it breaks major functionality of org-chart and proposed changes are not supplemental to the `eval` related functionality as well

**Comment by bumbeishvili** [comment]
@michael-lumley can you provide a screenshot of errors? I want to know more about it. When does it happen?

**Comment by michael-lumley** [comment]
@bumbeishvili Can you explain the functionality `eval()` is supposed to be achieving? My colleague and I can't quite figure out why it's written in that way.

**Comment by michael-lumley** [comment]
![image](https://user-images.githubusercontent.com/8387649/98875525-65db9000-244a-11eb-9564-838826e35aa4.png)

We get this on occasion instead of the hierarchy graph.

**Comment by michael-lumley** [comment]
For more general background: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!

**Comment by michael-lumley** [comment]
Also, I tested the PR on the data from the `jsFiddle` (https://jsfiddle.net/k2ucqayn/) and everything worked fine - is the `eval()` supposed to be handling some kind of edge case?

**Comment by bumbeishvili** [comment]
Testing it now and it seems you are right, but I need to check this more carefully, I don't exactly remember why I put eval here when I could get rid of it

**Comment by bumbeishvili** [comment]
I will use your suggested approach in my d3 project, I am working currently on, and if it will go without noticeable issues, I will replace this part here as well

**Comment by michael-lumley** [comment]
What would your expected timeline be? We can probably wait a week or so, but otherwise we will probably wind up having to fork and maintaining the fork ourselves.

**Comment by bumbeishvili** [comment]
I'd suggest fork approach for now

**Comment by bumbeishvili** [comment]
In the new version, eval will be removed

https://github.com/bumbeishvili/d3-organization-chart/blob/ebd5568321b91f10df4d84f090ec6c562a1784f5/src/d3-org-chart.js#L157

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
