### ISSUE TITLE
The folding/folding function causes the image within the node to flash

### ISSUE THREAD

**Issue by tangtingtt** [bumbeishvili/org-chart#408]
Hello author,
Currently, when I fold/unfold child nodes, the elements of the parent node will be reloaded (the avatar img will be re rendered). Is there a way to solve this problem?
![2](https://github.com/bumbeishvili/org-chart/assets/26892355/5426e58e-62ea-43c9-b1fd-c196133124ef)
I wrote the avatar implementation in the nodeContent function
![image](https://github.com/bumbeishvili/org-chart/assets/26892355/c65aa9d6-36e0-4a31-a914-8d9679c83122)

**Comment by bumbeishvili** [comment]
Hi, that only happens if caching is disabled (for example when you are checking out the chart with dev tools open). I don't think that there is a way around it  since when expanding and collapsing, everything is being rendered, including images

**Comment by tangtingtt** [comment]
thanks,😊Do you mean when caching is disabled in browser developer tools?



---Original---
From: "David ***@***.***&gt;
Date: Wed, May 29, 2024 19:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bumbeishvili/org-chart] The folding/folding function causes theimage within the node to flash (Issue #408)




 
Hi, that only happens if caching is disabled (for example when you are checking out the chart with dev tools open). I don't think that there is a way around it  since when expanding and collapsing, everything is being rendered, including images

**Comment by bumbeishvili** [comment]
Yes, when caching is disabled, flickering happens, because the image is being loaded once again, if caching is allowed, then image loading is instantaneous and while image loading still happens from a cache, it's not noticeable

**Comment by tangtingtt** [comment]
Ok, I will go to the company tomorrow to have a try, thank you for your reply, good luck!



---Original---
From: "David ***@***.***&gt;
Date: Wed, May 29, 2024 20:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bumbeishvili/org-chart] The folding/folding function causes theimage within the node to flash (Issue #408)




 
Yes, when caching is disabled, flickering happens, because the image is being loaded once again, if caching is allowed, then image loading is instantaneous and while image loading still happens from a cache, it's not noticeable

**Comment by tangtingtt** [comment]
After testing, it is indeed caused by disabling browser caching, so this is not a problem. Thank you very much! 😀However, en...，I have another small question. If I want to use the mouse to select elements within a node (ordinary text implemented by div tags) for copying, what kind of attribute should I set?

**Comment by bumbeishvili** [comment]
@tangtingtt When you are trying to select the text, panning event fires and chart is being panned

This is controlled by built-in d3.zoom class.

In that example, we are passing different d3. zoom class and we override the behavior, basically saying that don't apply panning to TR,TD, TH elements. 

If you require text selection of specific divs, you can assign a specific class to them and then check if `e.srcElement` has that class inside this function (instead of checking if it is TR,TD or TH elements)

![image](https://github.com/bumbeishvili/org-chart/assets/6873202/a4e48d64-6b30-4cb8-8c7c-5782c8b7f964)

**Comment by tangtingtt** [comment]
> @tangtingtt When you are trying to select the text, panning event fires and chart is being panned
> 
> This is controlled by built-in d3.zoom class.
> 
> In that example, we are passing different d3. zoom class and we override the behavior, basically saying that don't apply panning to TR,TD, TH elements.
> 
> If you require text selection of specific divs, you can assign a specific class to them and then check if `e.srcElement` has that class inside this function (instead of checking if it is TR,TD or TH elements)
> 
> ![image](https://private-user-images.githubusercontent.com/6873202/335083766-a4e48d64-6b30-4cb8-8c7c-5782c8b7f964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTQ1MDMsIm5iZiI6MTcxNzA1NDIwMywicGF0aCI6Ii82ODczMjAyLzMzNTA4Mzc2Ni1hNGU0OGQ2NC02YjMwLTRjYjgtOGM3Yy01NzgyYzhiN2Y5NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDczMDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWNkZDA0ZjViN2IzZDg2MGU2YjNmZmZhNmU5NmM5NWVlOGEwYTNkMjZjNjQ4MjliMGRkNGFiYThmNGRhOTEwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qmTclYNKVsxx3zrxj9iM_CvCi2ITbn1Sbjb10_jCMWk)

According to your method, I succeeded. Thank you very much!
