### ISSUE TITLE
Node Coloring persisting when chart rerenders

### ISSUE THREAD

**Issue by IceBoxAlex** [bumbeishvili/org-chart#418]
Hi There! 

Firstly, thank you so much for putting the time and work into this library. It is an absolute joy to use.

I do however have a quick question, I want to be able to color the nodes and have that nodes coloring persist even when the chart rerenders.

I have this built out in react to handle the node highlighting:
```
   /**
     * handleNodeClick
     * Handles the click event on a chart node to highlight and show details in the sidebar.
     * @param {Object} d - The data object of the clicked node
     * @param {Object} chartInstance - The chart instance
     */
    const handleNodeClick = useCallback((d, chartInstance) => {
        if (chartInstance) {
            if (d.data._highlighted) {
                d.data._highlighted = false;
                setHighlightedEmployeeNumber(null);
                setHighlightedNodeId(null);
                setShowSidebar(false); // Hide sidebar
            } else {
                chartInstance.data().forEach(node => {
                    node._highlighted = false;
                });

                d.data._highlighted = true;
                setHighlightedEmployeeNumber(d.data.id);
                setHighlightedNodeId(d.data.id);
                setShowSidebar(true); // Show sidebar
            }

            chartInstance.render();
        } else {
            console.log('Chart instance is not available');
        }
    }, []);
```
    
I have this sidebar component built out that pops up when a node is highlighted: 
```
            <div className="sidebar-content">
                <p>Employee ID: {employeeId}</p>
                <select onChange={handleChange}>
                    <option value="">Select Color</option>
                    <option value="#1AA260">Green</option>
                    <option value="#F70D1A">Red</option>
                    <option value="#1974D2">Yellow</option>
                </select>
            </div>
```

I pass the color value to the OrgChart component I have and then to .nodeContent to make the style change.
But I cannot figure out a way to have the nodes maintain the chosen color when the chart rerenders. Has anyone tried to do something similar and can point me in the right direction?

**Comment by bumbeishvili** [comment]
Hi, can you prepare an online sample with the issue highlighted?

You can fork and extend this sample

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks?file=index.js

**Comment by IceBoxAlex** [comment]
Thanks for the quick reply!

I am not too familiar with Stackblitz so I just reformatted most of my code to make it work on the IDE.
[https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-tbebk2?file=src%2Fcomponents%2FSidebar.js](url)

So a quick rundown of code:

1. FeedPage.js will invoke OrgChart.js in the components folder
2. OrgChart.js will create the OrgChart based off of the csv and it also houses some user interaction events like search, highlighting, and view manipulation.
3. When you click on a node, OrgChart.js will highlight, then invoke Sidebar.js to create the pop up
4. Sidebar.js allows you to select a coloring option for the nodes.

Now if you go through an color a node, you will see that the color disappears if I click on another node. The color only returns when the other node is colored. Another issue is that when I expand the chart and try to color a child node, the chart will re-render and collapse to the first depth.

So my question is: Is is possible to have the chart re-render in all states with the newly applied color value for the specific node(s)? I may be missing something simple because I have been staring at this for a few hours. Apologies in advance if that's the case.

**Comment by bumbeishvili** [comment]
Had a quick look, I don't think that it's correctly integrated into the React app, since on every change a new Org Chart component is created,  instead of updating . Most probably here lies the problem

Here is a pattern of how it should be integrated
<img width="650" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/a006e171-fb07-4a23-aa5f-7a1c258512fe">

**Comment by IceBoxAlex** [comment]
Thank you so much for your help. I indeed was just rerendering on what was meant to be updates. Once I made the changes to update and a reimplemented the node coloring functionality it worked beautifully. 

Cheers!
