### ISSUE TITLE
is there a way to update the svg width without calling render()?

### ISSUE THREAD

**Issue by kanth609** [bumbeishvili/org-chart#427]
Hello :), 
so basically, i'm trying to update the `svg` width dynamically using `svgWidth(<value>)` but i have to call the `render()` function to update width in the DOM, as i'm loosing the added classes when the `render()` is called. So checking here if  is there a way to update the svg width without calling `render()`?

**Comment by bumbeishvili** [comment]
svg is exposted through state, so in theory you could do

```javascript
chart.svgWidth(300);
chart.getState().svg.attr('width,300)
```

But something feels wrong with this approach

**Comment by bumbeishvili** [comment]
> thanks @bumbeishvili , can you pls let me know why do you feel it is wrong, so that i can find the different approach to update the width of svg. thanks!

Because render should be working normally and you should not be losing anything?

**Comment by kanth609** [comment]
yeah you're ryt, as i'm applying some styles to the selected node and if i call the `render()`, it is getting removed also if nodes are huge, i don't wanna re-render the chart. so thinking to go ahead with the approach which you suggested above. :)
