### ISSUE TITLE
Whenever I try to change the parentId of a node, the parent node automatically expands, can this be prevented?

### ISSUE THREAD

**Issue by seanpmaxwell** [bumbeishvili/org-chart#432]
I have my own custom code for updating the parent of a data item in the array. After I update the parentId of the data item and call: 
`chart.data(data).render();` the parent node automatically expands. I've tried all kinds of hacky things to prevent this but to no avail. This does not happen when I add a new node. Only when I change the `parentId` of an existing node.

**Comment by bumbeishvili** [comment]
@seanpmaxwell  can you provide a sample stackblitz link with with that reproduced?

**Comment by seanpmaxwell** [comment]
Thanks for the quick response, I couldn't reproduce on stackblitz. When I was fetching the data item through the allNodes from the chart I had the issue. When I updated the data array directly the problem went away. Weird.
