### ISSUE TITLE
Support JSON Schema

### ISSUE THREAD

**Issue by kuncevic** [bumbeishvili/org-chart#433]
Would you consider supporting JSON Schema?

I assume that the best way to do that is by converting JSON Schema into a proper data format, right?

here is an example https://raw.githubusercontent.com/fge/sample-json-schemas/master/json-home/json-home.json

**Comment by bumbeishvili** [comment]
@kuncevic it's already possible to load and serve JSON data, so not exactly sure what supporting JSON schema is about

https://stackblitz.com/edit/js-36myfl?file=index.html
