### ISSUE TITLE
How to properly implement OrgChart in React/NextJS.

### ISSUE THREAD

**Issue by jrso15** [bumbeishvili/org-chart#437]
Hello,

I’m currently trying to implement OrgChart in d3-org-chart but I’m getting OrgChart is not a constructor. I can’t find any solution for this. can someone please help me?

Here’s sample of my code:

```
import React, { useRef } from "react";
import dynamic from "next/dynamic";
import styles from "@/styles/OrganizationChart.module.scss";

const OrgChart = dynamic(
  () =>
    import("d3-org-chart").then((mod) => {
      console.log(mod); 
      return mod.OrgChart;
    }),
  { ssr: false }
);

const OrganizationChart = ({ organizationItemData, onNodeClick }) => {
  const d3Container = useRef(null);
  const chartRef = useRef(null);

  // Initialize the chart directly in the render function if the container is ready
  if (organizationItemData && d3Container.current && !chartRef.current) {
    chartRef.current = new OrgChart(); // Adjust this based on the module structure

    chartRef.current
      .container(d3Container.current)
      .data(organizationItemData)
      .nodeWidth(() => 200)
      .nodeHeight(() => 120)
      .onNodeClick((d) => {
        console.log(d, "Id of clicked node ");
        onNodeClick(d);
      })
      .render();
  }

  return (
    <div className={styles.orgWrapper}>
      <div ref={d3Container} />
    </div>
  );
};

export default OrganizationChart;
```

Thanks in advance!

**Comment by bumbeishvili** [comment]
Hi, there is a react integration sample.

Was not it useful?

https://github.com/bumbeishvili/org-chart?tab=readme-ov-file#featured-customizations

I also wrote a general guide about integration of d3 visualization (check out the integration section), it might be useful

https://medium.com/@bumbeishvili/best-d3-coding-convention-subjective-practice-proven-through-years-of-work-03c521715b05

**Comment by jrso15** [comment]
Hi Bumbeishviili,

I followed some of your documentation.

And this is exactly what I’m getting:

![IMG_1714](https://github.com/user-attachments/assets/ca4fe934-fc0a-4705-b365-979cbda4e494)


And I can’t find any solution for this.

I want to implement something like this:

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-topjz5?file=index.js

**Comment by bumbeishvili** [comment]
It does not have a specific structure.

The only thing is necessary is to be able to tell hierarchy, for that default `id` and `parentId` or `nodeId` and `parentNodeId` is checked (which you can also override)

There is one JSON sample here - https://github.com/bumbeishvili/org-chart?tab=readme-ov-file#features

But again, it does not matter what structure you have as long as you have a hierarchy extractable. Also you can't have multiple roots, so be aware of that

**Comment by jrso15** [comment]
Thank you!❤️
