### ISSUE TITLE
No export

### ISSUE THREAD

**Issue by Rudresh24** [bumbeishvili/org-chart#44]
I think that export functionality could be the most useful for users. There is any solution to that. I trying to download the chart using some npm packages like html2canvas, domtoimage. It works but the images are not shown. So kindly let me know any other possible ways to download the chart.
![Chart (25)](https://user-images.githubusercontent.com/68742199/101145801-4c3ff980-3640-11eb-96c4-1e99f57f1f77.jpg)

**Comment by bumbeishvili** [comment]
@Rudresh24  I think that option should be outside org-chart code since it's general SVG to and png downloading functionality 

I am aware of the issue you are facing though. It's because a chart uses a foreign object to display its content.

When I needed foreign object exporting, I used a workaround

Here is a relevant code, It should be fairly easy for you to modify the code and fit your needs
https://observablehq.com/@bumbeishvili/foreignobject-exporting-issue

**Comment by Rudresh24** [comment]
@bumbeishvili  
![Screenshot from 2020-12-04 19-17-47](https://user-images.githubusercontent.com/68742199/101171416-bae37e00-3665-11eb-8f1b-9c96be2ba88d.jpg)
From the above image where does the 'svg' represents and I have sent the svg to serializestring function it throws me an error i.e., svg.cloneNode is not  a function
Kindly guide me and tell me where I committed the mistake

**Comment by bumbeishvili** [comment]
To be more specific, this is the function which you need to invoke, and you should pass SVG node to it. If you only have d3 svg selection, you can use `svg.node()` method


```javascript
function downloadImage(foreignObjectSVG) {
      // Retrieve svg node
      const svgNode = foreignObjectSVG;


        // Get image quality index (basically,  index you can zoom in)
        const quality = 2
        // Create image
        const image = new Image();
        image.onload = () => {
          // Create image canvas
          const canvas = document.createElement('canvas');
          // Set width and height based on SVG node
          const rect = svgNode.getBoundingClientRect();
          canvas.width = rect.width * quality;
          canvas.height = rect.height * quality;

          // Draw background
          const context = canvas.getContext('2d');
          context.fillStyle = '#FAFAFA';
          context.fillRect(0, 0, rect.width * quality, rect.height * quality);
          context.drawImage(image, 0, 0, rect.width * quality, rect.height * quality);

          // Set some image metadata
          let dt = canvas.toDataURL('image/png');

          // Invoke saving function
          saveAs(dt, 'graph.png');
        };


        var url = 'data:image/svg+xml; charset=utf8, ' + encodeURIComponent(serializeString(svgNode));

        image.src = url// URL.createObjectURL(blob);
      

      // This function invokes save window
      function saveAs(uri, filename) {
        // create link
        var link = document.createElement('a');
        if (typeof link.download === 'string') {
          document.body.appendChild(link); // Firefox requires the link to be in the body
          link.download = filename;
          link.href = uri;
          link.click();
          document.body.removeChild(link); // remove the link when done
        } else {
          location.replace(uri);
        }
      }

      // This function serializes SVG and sets all necessary attributes
      function serializeString(svg) {
        const xmlns = 'http://www.w3.org/2000/xmlns/';
        const xlinkns = 'http://www.w3.org/1999/xlink';
        const svgns = 'http://www.w3.org/2000/svg';
        svg = svg.cloneNode(true);
        const fragment = window.location.href + '#';
        const walker = document.createTreeWalker(svg, NodeFilter.SHOW_ELEMENT, null, false);
        while (walker.nextNode()) {
          for (const attr of walker.currentNode.attributes) {
            if (attr.value.includes(fragment)) {
              attr.value = attr.value.replace(fragment, '#');
            }
          }
        }
        svg.setAttributeNS(xmlns, 'xmlns', svgns);
        svg.setAttributeNS(xmlns, 'xmlns:xlink', xlinkns);
        const serializer = new XMLSerializer();
        const string = serializer.serializeToString(svg);
        return string;
      }
    }
```


so, you either will need 
`downloadImage(svg)`
or
`downloadImage(svg.node())`

**Comment by Rudresh24** [comment]
Is that function is also applicable image elements?? Because only text template inside the foreign objects is only visible after downloading.
Image files inside a foreign object not visible Bro

**Comment by bumbeishvili** [comment]
@Rudresh24 Just tried it, looks like you are right, images weren't loading

Not sure how can I help, if you find the answer, can you post it here as well? Probably,  It will help others

**Comment by Rudresh24** [comment]
@bumbeishvili  I have some other doubts too bro. While downloading the chart, If the Chart is in Zoomed state the downloaded image capturing only the zoomed part. So is there any possible ways to overcome that??
And is that possible for us 
1. To set the SVG width manually from component.ts file
2. To Limit the Scaling factor in Zooming 
Kindly help me with your valuable inputs

**Comment by bumbeishvili** [comment]
>  While downloading the chart, If the Chart is in Zoomed state the downloaded image capturing only the zoomed part. So is there any possible ways to overcome that

Not really - it captures only the visible part. In theory, it's possible to zoom into bounds, but I don't currently have time to implement this feature. 

>  To set the SVG width manually from component.ts file
Currently, it fits the container, so I guess, you could set the width to a container element and the chart would receive the same width, haven't tested this

> To Limit the Scaling factor in Zooming
https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L167
You could change this line to set the scaling factor
https://github.com/d3/d3-zoom/blob/master/README.md#zoom_scaleExtent

**Comment by bumbeishvili** [comment]
For your information

I was able to overcome the image exporting issue within foreignObject (I am converting images to base 64 string, which looks like to be doing the trick.)

https://github.com/bumbeishvili/d3-organization-chart/blob/317f70da2407d4ea468bc9b4a29d10c5e8d0ecd1/src/d3-org-chart.js#L1110

Exporting feature will be built-in into the next version of org chart (Which should be ready within month)

https://user-images.githubusercontent.com/6873202/126205313-8e8783f0-dcb6-40f8-9c94-473a720dc519.mp4

As for your next question

> I have some other doubts too bro. While downloading the chart, If the Chart is in Zoomed state the downloaded image capturing only the zoomed part. So is there any possible ways to overcome that??

I've exposed yet another method called fit (you can see that functionality in the above video), which will fit the graph into the viewport.

It will be possible to combine these commands to achieve desired result
```javascript
chart
  .fit({animate:false})
  .exportImg()
```

**Comment by bumbeishvili** [comment]
BTW, I will also provide a snippet, which you can use to export chart as PDF, but this functionality won't be built-in, the chart will only expose base64 image and it will be your job to put it into PDF (snippet will be provided)


https://user-images.githubusercontent.com/6873202/128852618-2f6d0f0b-ef40-491b-a00a-786827e22341.mp4

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
