### ISSUE TITLE
Placing the same node under multiple parent nodes

### ISSUE THREAD

**Issue by kanth609** [bumbeishvili/org-chart#445]
Hi @bumbeishvili , is there any way to place a child node under multiple parent nodes? Thanks!

**Comment by aloisdg** [comment]
Same question I would like this when people belong to two interlaced org charts

**Comment by kanth609** [comment]
@bumbeishvili can you please let us know if there is any possibility to place a child node under multiple nodes please?

**Comment by bumbeishvili** [comment]
No, there is no direct way to place a child node under multiple parents.

But we have connections functionality so you can connect any node to any node and you can also restyle how this connections looks

https://stackblitz.com/edit/js-tpbt7r?file=index.html
