### ISSUE TITLE
Compact Layout

### ISSUE THREAD

**Issue by rajat-sf** [bumbeishvili/org-chart#50]
How can we minimise the distance between nodes when both of the nodes are expanded.

Please find below link for the better illustration of the problem.

@bumbeishvili could you please help me resolving this issue.

https://user-images.githubusercontent.com/77266357/115682028-b39de200-a372-11eb-9443-e2c7f7d22d44.mp4

and sample code pen is https://codepen.io/rajat-sf/pen/ZELmmLr?editors=1010

Thanks for this wonderful repository having almost ready to use code.

**Comment by bumbeishvili** [comment]
That's the default behavior of d3.tree, which this org chart uses.

It's possible to modify this code and force it to have a different layout, but it's a pretty complex task and currently won't be able to do it. I am only doing updates to the org chart when I have a corresponding project which involves d3 tree.

I plan to have this layout option in the v2 version, but as I said, I don't know when it will be ready

<img width="1168" alt="Screenshot 2021-04-22 at 12 37 03" src="https://user-images.githubusercontent.com/6873202/115683535-9ca5c280-a367-11eb-8d51-360c3e465b0f.png">

**Comment by bumbeishvili** [comment]
FYO above mentioned compact layout is in the development phase, it will land to development branch in 1-2 weeks time

<img width="872" alt="Screenshot 2021-08-02 at 13 11 44" src="https://user-images.githubusercontent.com/6873202/127836528-d1eecb22-a0d8-4b02-8954-992f62c84a8b.png">
<img width="862" alt="Screenshot 2021-08-02 at 13 11 54" src="https://user-images.githubusercontent.com/6873202/127836552-5d7e3508-0c45-4d67-9f97-737836507da2.png">
<img width="856" alt="Screenshot 2021-08-02 at 13 12 07" src="https://user-images.githubusercontent.com/6873202/127836562-8307276d-2ff0-4981-bec4-40aea0cf00cd.png">
<img width="592" alt="Screenshot 2021-08-02 at 13 12 30" src="https://user-images.githubusercontent.com/6873202/127836573-92739ca4-01f7-4af8-8c90-4c518cd69a70.png">
<img width="633" alt="Screenshot 2021-08-02 at 13 12 41" src="https://user-images.githubusercontent.com/6873202/127836583-46fb8153-a220-4220-9b57-116caed34038.png">
<img width="824" alt="Screenshot 2021-08-02 at 13 12 55" src="https://user-images.githubusercontent.com/6873202/127836587-d430f24e-9d94-4cf8-a188-6355ff52f015.png">

**Comment by bumbeishvili** [comment]
Here is a comparison for vertical version

## Normal
<img width="1353" alt="Screenshot 2021-08-08 at 14 03 33" src="https://user-images.githubusercontent.com/6873202/128628402-60b32e69-0bb8-41b1-86e9-e92d2e7e7346.png">
<img width="1363" alt="Screenshot 2021-08-08 at 14 04 43" src="https://user-images.githubusercontent.com/6873202/128628404-f0ca3357-74f7-43a3-8f6f-70b9aec8d7ff.png">


## Compact
<img width="1360" alt="Screenshot 2021-08-08 at 14 02 57" src="https://user-images.githubusercontent.com/6873202/128628408-2b708988-5fd7-408a-aeff-6bc03ae57907.png">
<img width="1364" alt="Screenshot 2021-08-08 at 14 06 07" src="https://user-images.githubusercontent.com/6873202/128628412-3724daaa-8dc7-4725-9eda-eef935b40b03.png">

**Comment by bumbeishvili** [comment]
You can check the [example of the new version]( https://stackblitz.com/edit/web-platform-jyncb9) from now on. I expect to publish a new version by the next week

https://user-images.githubusercontent.com/6873202/128749314-c58a20fb-f863-4dc0-8e65-78f94445d929.mp4

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
