### ISSUE TITLE
create links between nodes

### ISSUE THREAD

**Issue by zair07** [bumbeishvili/org-chart#57]
I am trying to obtain a functionality where I have to show some relationship of parent and child ( two levels down) is there any way to do that if it has been already implemented where can I get it?

**Comment by bumbeishvili** [comment]
No, it's not possible and nor it is implemented in the currently ongoing  development version

**Comment by bumbeishvili** [comment]
FYO, in the new, coming version, we will have multi links functionality. You will be able to specify connections with labels between any nodes

https://github.com/bumbeishvili/d3-organization-chart/blob/ee33e5ed64afa0be1ca2c695ed4d525aae67f98e/tree.html#L138

It will look like this

<img width="1672" alt="Screenshot 2021-07-29 at 17 46 20" src="https://user-images.githubusercontent.com/6873202/127504411-b50ab9a4-493a-4e4f-84b1-ce4df2f6e8c2.png">

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
