### ISSUE TITLE
Chart re-center on update using it with Angular 

### ISSUE THREAD

**Issue by NightLightSweden** [bumbeishvili/org-chart#58]
**Describe the bug**
When updating the org chart on Angular it is always re-centered in the svg.  This bug happens on the Angular example as well as reproduced in a test app (both on D3 v5 and v6 Angular 11). The problem is not happening on the Observable example

**To Reproduce**
Move around the chart and click the button

https://stackblitz.com/edit/d3-org-chart-angular-integration-muka3u?file=src/app/d3-org-chart/d3-org-chart.component.ts

**Expected behavior**
The chart should not re-center working fine on below example (move around the chart in the svg and add a new root node)

https://observablehq.com/@bumbeishvili/d3-v5-organization-chart

**Screenshots**
Please see example links

**Desktop (please complete the following information):**
Chrome latest as of 14 June 2021

**Smartphone (please complete the following information):**
Not tested

**Additional context**

---

Also, there is a **new** dev version in progress - check the roadmap here - https://github.com/bumbeishvili/d3-organization-chart/issues/14

**Comment by bumbeishvili** [comment]
The difference between the observable example and the angular sample is that in observable corresponding methods are invoked  and in the angular, it redraws everything (although my assumption was that it would work for that case as well)


I plan to start working on new features in about a week and will try to find solution for this case as well, will keep it open until

**Comment by JohanBrodinSinch** [comment]
Thank you for the quick answer! A fix would be fantastic and I am more than happy supporting with a donation supporting this great org chart. Please let me know.

**Comment by bumbeishvili** [comment]
>  A fix would be fantastic and I am more than happy doing a donation supporting this great org chart. Please let me know.

Ah, this sounds great and that would be the first time.

I would appreciate it since it will help me to allocate some time from my other projects (From which I actually have a revenue stream)

You can use ko-fi to make a donation
https://ko-fi.com/bumbeishvili

**Comment by JohanBrodinSinch** [comment]
Just bought you 10 cup of coffees! Keep up the good work!

**Comment by bumbeishvili** [comment]
@NightLightSweden Just for your information

I will be publishing a new, v2 version in the coming days. This issue is already fixed and many new features are also coming (will post a blog post URL about it shortly once I will fix every example)

As for angular integration, you can check how it works here - https://stackblitz.com/edit/d3-org-chart-angular-integration-halhxr?file=src%2Fapp%2Fapp.component.ts

As you can see subsequent data updates do not cause chart zoom state to restart

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
