### ISSUE TITLE
Change orientation Left to Right / Right to left

### ISSUE THREAD

**Issue by gangesh** [bumbeishvili/org-chart#6]
Chart Class is using D3 as base, so it is possible to change orientation of chart as well?

**Comment by bumbeishvili** [comment]
Currently, it's not possible and not planned as well, I will keep this issue open though

**Comment by bumbeishvili** [comment]
Here is an in-progress example of using horizontal layout - https://observablehq.com/d/e106c59dbd9f6151

You can pass layout options like this:
``` javascript
chart.layout('h') // horizontal
chart.layout('v') // vertical
```

**Comment by darshanagandhi90** [comment]
How can we set this layout option in angular?

**Comment by bumbeishvili** [comment]
In the new, dev version,4 layout types are implemented which can be changed at runtime

Layout can be set using

```javascript
chart.layout('left')
chart.layout('top')
chart.layout('right')
chart.layout('bottom')
```

https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L64


https://user-images.githubusercontent.com/6873202/126049326-a4b49ae4-f5ca-4a28-9710-92675c78ace1.mp4

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
