### ISSUE TITLE
Icon not always on top styling template with html

### ISSUE THREAD

**Issue by NightLightSweden** [bumbeishvili/org-chart#66]
**Describe the bug**
When styling the template with html the icon is not on top. (Using a div with background color)

**Expected behavior**
The icon should always be topmost (as well as the bottom low plus icon)

**Screenshots**
<img width="183" alt="d3 org chart" src="https://user-images.githubusercontent.com/50442378/128612776-7b6f4c2e-4d04-47ff-9e76-e5fcaad2fd62.png">

**Desktop (please complete the following information):**
Chrome but is for all browsers

**Comment by bumbeishvili** [comment]
Within the next 10 days, a new V2 version will be pushed, which will remove icon functionality completely and instead you will have a chance to include image within HTML body (`<img/>`), which will be on top of everything

If you want to give it try, check the development branch - https://github.com/bumbeishvili/d3-organization-chart/tree/development

The sample file is `tree.html` and just do `npm install` to generate necessary files

**Comment by NightLightSweden** [comment]
Amazing looking forward the new version! 

One small comment. In the current version it is great that the icon can be outside the template to leave more place for content. If the icon now is in the template body as a img tag I hope it is still possible to push it to the same location as today with some css magic.

**Comment by bumbeishvili** [comment]
Yes, it will be possible using CSS

It will be achievable using `position:absolute` and `margin-left:-30px;margin-top:-30px` manipulation

https://github.com/bumbeishvili/d3-organization-chart/blob/ee33e5ed64afa0be1ca2c695ed4d525aae67f98e/tree.html#L148

**Comment by bumbeishvili** [comment]
You can check the [example of the new version]( https://stackblitz.com/edit/web-platform-jyncb9) from now on

https://user-images.githubusercontent.com/6873202/128749314-c58a20fb-f863-4dc0-8e65-78f94445d929.mp4

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)
