### ISSUE TITLE
First re-centering zoom doesn't match initial zoom

### ISSUE THREAD

**Issue by chrisslazzz** [bumbeishvili/org-chart#72]
**Describe the bug**
First of all I want to thank you for the new version. I played around with it a bit and it works very well! 👏👏👏
The only thing I noticed is that when initialZoom is set, the first expansion of a node is zoomed in with ZoomLevel 1.

You can reproduce it with the example. So it shouldn't be an error in my config.

**To Reproduce**
1. Set initialZoom (e.g. initialZoom(0.3)
2. Expand a node
3. See that the expansion ignored the initial zoom level and zoomed in more (probably default zoom level 1)

**Expected behavior**
The zoom should match the initial zoom level.

**Screenshots**
Before expansion:
![image](https://user-images.githubusercontent.com/57229182/129528521-eb7ff0e2-30a5-4ad4-a207-c32a7ef3b6f5.png)

After expansion:
![image](https://user-images.githubusercontent.com/57229182/129528536-999cd330-76c5-4acd-b409-6b64b4187495.png)

**Comment by bumbeishvili** [comment]
Thanks for reporting

I fixed it with this commit - https://github.com/bumbeishvili/org-chart/commit/9a179c1d5ef74fec1c35045c109ab9808c2a8f1d

And published it on NPM as well

If you want to give it a try, load this version in your project  - https://cdn.jsdelivr.net/npm/d3-org-chart@2.3.1  , not sure when `jsdelivr` updates its cache to load the latest version

**Comment by chrisslazzz** [comment]
Thanks a lot for the really quick fix!
I noticed that with initial zoom the first expansion has a different animation that the other expansions. It doesn't bother me, but wanted to let you know.

**Comment by bumbeishvili** [comment]
@chrisslazzz  yes, I know about that. It's because by default active node gets centered. 

You can turn it off using the following snippet
```javascript
chart
    .initialZoom(0.5)
    .setActiveNodeCentered(false) //  Turns of default node centering
```
