### ISSUE TITLE
After adding one node it doesn't add more, same for delete node

### ISSUE THREAD

**Issue by harellevy** [bumbeishvili/org-chart#73]
**Describe the bug**

**To Reproduce**
1. open example
2. add node
3. add another node (not working)
4. delete node
5. delete another node (not working)

**Expected behavior**
multiple add / remove nodes

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome

**Comment by bumbeishvili** [comment]
@harellevy can you link the example? 

Please be aware that you can't add two nodes with the same ID. If I am encountering such cases, a warning message is issued in the console for the user to debug it better

**Comment by harellevy** [comment]
Oh, cool! So the example is trying to add the same node with same id again and again?

**Comment by bumbeishvili** [comment]
Exactly, you can see it in `onclick` handler of the button

<img width="1230" alt="Screenshot 2021-08-16 at 15 06 06" src="https://user-images.githubusercontent.com/6873202/129554392-7995e0ed-bc45-49ad-b14e-af14caca7f53.png">
