### ISSUE TITLE
Collapse All nodes and Zoom question

### ISSUE THREAD

**Issue by NightLightSweden** [bumbeishvili/org-chart#76]
Love the new version and especially that you now can do full html styling, routing is smarter and exporting to svg is great!

However I have two questions that also could be feature requests.

#Expanding/Collapsing
I want to be able to do expand/collapse all. You can do chart.expandAll() to expand but I did not find the corresponding collapse. I have found a workaround setting node._expanded = false in the data. However sometimes, often in combination with chart.zoomOut() or chart.zoomIn(), the org chart is inverted 180 degrade... So all to all a chart.collapseAll() would be great.

#Zoom In/Out
The old solution had chart.initialZoom(0.5) that now is removed. Great that you easily can zoom on/out in the new version however this input was very good so can you add it back? Doing expand all in the new version is not always keeping the zoom level so having it would fix that. Also having this function would make easier to set the first zoom level.

**Comment by bumbeishvili** [comment]
@NightLightSweden 

collapseAll will be a good addition, I can do that.

Not sure what you mean by inverting, can you record a gif or video and attach it?  

As for initialZoom that is still in place so you can use it.

**Comment by NightLightSweden** [comment]
Great adding collapseAll()! 

Here you go with a short video. The bug is not consistent reproducible and sometimes you have to click expand/collapse zoomIn/zoomOut more times to get it. As written above I use node._expanded and with you adding collapseAll I can skip that and hopefully this bug is not happening.


https://user-images.githubusercontent.com/50442378/129790250-f0f36ea7-ece1-4828-a4aa-ede82eb03e0f.mov

**Comment by bumbeishvili** [comment]
That's very strange, I have no idea why is it happening. 

As it looks, the layout is changing from `top` to `bottom` but very weirdly,  theoretically, it should not be related to anything you are doing.

Did you see some errors in the console which may guide us? I can't seem to reproduce it in the [online version](https://stackblitz.com/edit/web-platform-o5t1ha)

**Comment by NightLightSweden** [comment]
Yes I did check and no errors unfortunately. It's an angular app.

**Comment by NightLightSweden** [comment]
I did find the bug .initialZoom(x) was called with a negative value!

In the old version we used .initialZoom(x) on each render to zoom. But in the new version it only works first chart render.  (works great on your Angular example so something on our side) So instead we are doing zoomIn() and zoomOut() but did not remove .initialZoom(x) from all rendering except the first so after some key presses it did a negative value.

**Comment by bumbeishvili** [comment]
Interesting, in the code  `initialZoom` just sets scale. So, minus scale means it will also get rotated as well as scaled, did not think about that.

**Comment by bumbeishvili** [comment]
Added `collapseAll` functionality

If you want to give it a try include this version `2.3.2` , it may take up to 1 day until all examples fetch new version
`<script src="https://cdn.jsdelivr.net/npm/d3-org-chart@2.3.2"></script>`

**Comment by bumbeishvili** [comment]
I am going to close this one
