### ISSUE TITLE
Angular /TypeScript Support for v3

### ISSUE THREAD

**Issue by sidyes** [bumbeishvili/org-chart#77]
**Describe the bug**
I wanted to update to `v3` of `d3-org-chart` but ran into a problem.
First problem is that this lib does not provide a type definition file, so I have to add the following to my project to make it work:
```ts
//typings.d.ts
declare module 'd3-org-chart';
```

When running the application I get the following error:
![image](https://user-images.githubusercontent.com/11653185/130229682-20ca0a8f-8125-4b19-8c28-ef5e598b4fec.png)
`d3-flextree` produces this error and was not there before `v3` as `flextree` was newly added.

Did you ever try your new version with Angular and TypeScript? And do you have a fix for that?

Other than that this lib is awesome!!!

**To Reproduce**
1. Create a new Angular Project
2. Add this lib
3. Build a org chart in a component
4. Run the app

**Expected behavior**
No error is thrown when running the application.

**Comment by bumbeishvili** [comment]
Hello

> I wanted to update to v3 of d3-org-chart but ran into a problem.

There is not `v3` as of yet, the latest is `v2` version

> First problem is that this lib does not provide a type definition file, so I have to add the following to my project to make it work:

You are right, type definitions are not provided and nor planned since it will provide an additional burden of maintenance under limited resource

> Did you ever try your new version with Angular and TypeScript? And do you have a fix for that?

I've only provided an angular sample on stackblitz which was using angular v9. After I saw this, I've tried to provide examples of latest  `angular v12` version as well.

You can check it here 
https://stackblitz.com/edit/angular-ivy-gneris

I've tried downloading this example and running it locally, although I've faced different problems than you listed, so I did not proceed further

> Did you ever try your new version with Angular and TypeScript? And do you have a fix for that?

Not locally.  I am not sure how to solve it either, if you will find it, please post it here since it may help others

**Comment by sidyes** [comment]
As soon as `d3-flextree` publishes a new release, you need to update your dependency to make it work with webpack 5:
https://github.com/Klortho/d3-flextree/issues/21

**Comment by bumbeishvili** [comment]
Will keep it in mind

**Comment by bengray2** [comment]
Just leaving a little bread crumb with the error message as text so you can Google it.  

`./node_modules/d3-flextree/src/flextree.js:172:19-26 - Error: Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)`

You can go into ./node_modules/d3-flextree/src/flextree.js:172:19-26 and make the changes in fe01568 manually, until the NPM package is updated.

Hope that helps somebody.

**Comment by sidyes** [comment]
> Just leaving a little bread crumb with the error message as text so you can Google it.  
> 
> `./node_modules/d3-flextree/src/flextree.js:172:19-26 - Error: Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)`
> 
> You can go into ./node_modules/d3-flextree/src/flextree.js:172:19-26 and make the changes in fe01568 manually, until the NPM package is updated.
> 
> Hope that helps somebody.

Yes, easy to fix manually but not really an option for productive code.

**Comment by domdomegg** [comment]
I've added TypeScript definitions to DefinitelyTyped (would appreciate a review @sidyes if you're interested in the types)

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55624

**Comment by bumbeishvili** [comment]
@domdomegg  thank you, looks great (not sure yet if it works correctly in the TS environment)  

I might use it by myself in my projects

**Comment by sidyes** [comment]
@bumbeishvili 
Could you please publish a new version with the version of [d3-flextree](https://www.npmjs.com/package/d3-flextree)?
There is a new one since yesterday which contains the fix.

**Comment by bumbeishvili** [comment]
Will do it within this week (Most probably tomorrow or after tomorrow), first need to check that nothing broke

**Comment by bumbeishvili** [comment]
Merged it, let me know if issue is fixed

**Comment by sidyes** [comment]
> Merged it, let me know if issue is fixed

It is fixed and working just fine. Thanks a lot!
