### ISSUE TITLE
Question - Setting chart height

### ISSUE THREAD

**Issue by NightLightSweden** [bumbeishvili/org-chart#84]
I have a questions that I think are of interest to other users as well.

**Setting the chart height**
I use .svgHeight(svgHeight) to 100% fill the screen with a boarder around (below some buttons) . For some screen sizes it looks good and for some the chart height is higher then the screen. The height is not exactly set using svgHeight and it feels like there are some fixed heights build in. So the question is what is the recommended way to set the chart height?

Have a nice evening!

**Comment by bumbeishvili** [comment]
The height  you pass is set to SVG as an attribute

https://github.com/bumbeishvili/org-chart/blob/98850af142167ad958b25eb09e78998b1e4b885b/src/d3-org-chart.js#L411

I'd suggest just using javascript to calculate the optimal height and pass it

For example, if you want screen height with some minimal margin, you could pass
```javascript
window.innerHeight - 20
```

If you want container height you could pass this
```javascript
document.querySelector('<your container selector>').getBoundingClientRect().height
```

Be aware that later might not work if that container has height applied using external CSS. Sometimes JS code runs before external css and above code may return 0 as height
