### ISSUE TITLE
safari => node click issue

### ISSUE THREAD

**Issue by bumbeishvili** [bumbeishvili/org-chart#86]
Can't click to expand or collapse

https://user-images.githubusercontent.com/6873202/132627199-5fd78b11-4501-46f0-a8f6-b34ba906fb15.mp4

**Comment by kog13** [comment]
Can confirm also seeing this issue.

**Comment by Puller** [comment]
Same here... org-chart is not usable with Safari due to several bugs!

**Comment by bumbeishvili** [comment]
This particular issue should be fixed now
