### ISSUE TITLE
Show only highlighted nodes

### ISSUE THREAD

**Issue by neolution** [bumbeishvili/org-chart#87]
By selecting the upToTheRoot function the org chart highlights these nodes, but all other nodes are visible.

 Is it possible to show ONLY the highlighted nodes an not the others? After that it must be possible to reset the data. This would be simplify the visuals. Thank you.

**Comment by bumbeishvili** [comment]
it's possible to override default behavior in `linkUpdate` and `nodeUpdate` methods

https://stackblitz.com/edit/web-platform-vxtacm

https://user-images.githubusercontent.com/6873202/134763437-d1813343-843b-4907-9bf5-a4407a7126fb.mp4
