### ISSUE TITLE
Data source structure question

### ISSUE THREAD

**Issue by yizongk** [bumbeishvili/org-chart#88]
Is it a must that the input csv have a column called 'parentid' and a column called 'id'?

Is there a method in d3.OrgChart() to specify what column is the parent id, and what column is the row id?

And how does OrgChart() know which row is the root?

**Comment by bumbeishvili** [comment]
> Is there a method in d3.OrgChart() to specify what column is the parent id, and what column is the row id?

This is how it is implemented currently

<img width="421" alt="Screenshot 2021-09-30 at 09 48 09" src="https://user-images.githubusercontent.com/6873202/135394641-674d4fb1-5030-4b06-b404-37d0dc7de452.png">

You can override it using 
```javascript
chart
.nodeId(d=>d.yourNodeId)
.parentNodeId(d=>d.yourParentNodeId)
```

> And how does OrgChart() know which row is the root?

Org Chart considers a node to be a root if it does not have `parentId` specified

**Comment by yizongk** [comment]
Thanks! That worked.

For other who faced the same issue, this is my code snippet to do it:
```
<div id='chartContainerId'></div>
.
.
.
<script>

let temp = `last_name,pms,supervisor_pms
Joe,0710,
Jon,0864,0710
Jack,0931,0710`

let parsed_csv = d3.csvParse(temp)

chart = new d3.OrgChart().nodeId(
    d=>d.pms
).parentNodeId(
    d=>d.supervisor_pms
).container('#chartContainerId').data(parsed_csv).render();

</script>
```
