### ISSUE TITLE
Uncaught Error: multiple roots

### ISSUE THREAD

**Issue by yizongk** [bumbeishvili/org-chart#89]
Hi,

My data source is getting an error when I try to input to d3.OrgChart()

The line that caused the error:
```
chart = new d3.OrgChart().container('#chartContainerId').data(emp_data_csv_master).render();
```

My data structure for emp_data_csv_master:

last_name, first_name, id, parentid
JOHN, DOE, 111000,
WU, SHUN, 504060, 111000
LESY, INGRID, 025896, 111000
...
 

Can anyone help me?

**Comment by bumbeishvili** [comment]
Check if root node id is null

**Comment by yizongk** [comment]
Thank you,

but I actually find out the real reason. I missed spelled 'parentId' as 'parentid' with an lower case 'i'.

Cuz of this, it's giving me 'Uncaught Error: multiple roots'.

I fixed it like so:
```
<div id='chartContainerId'></div>
.
.
.

<script>
let emp_data_csv_master = `last_name,id,parentId
Joe,1100,
Rich,2320,1100
John,2450,1100`

let parsed_csv = d3.csvParse(emp_data_csv_master)

chart = new d3.OrgChart().container('#chartContainerId').data(parsed_csv).render()
</script>
```
