### ISSUE TITLE
Question - Boarder color of highlighted item

### ISSUE THREAD

**Issue by NordicLight** [bumbeishvili/org-chart#90]
When highlighting an item or all items up to root you can change the link color with below. But how do you change the border color around the item itself?

       .linkUpdate(function (d, i, arr) {
          var tmp:any = d;
          d3.select(this)
              .attr("stroke", d => tmp.data._upToTheRootHighlighted ? '#FF0000' : '#D3D3D3')
              .attr("stroke-width", d => tmp.data._upToTheRootHighlighted ? 4 : 1)

          if (d.data._upToTheRootHighlighted) {
              d3.select(this).raise()
          }
        })
        .render();

**Comment by bumbeishvili** [comment]
You can override default behavior in `nodeUpdate` function

Currently this is default behavior
```javascript
chart.nodeUpdate(d, i, arr) {
    d3.select(this)
        .select('.node-rect')
        .attr("stroke", d => d.data._highlighted || d.data._upToTheRootHighlighted ? '#152785' : 'none')
        .attr("stroke-width", d.data._highlighted || d.data._upToTheRootHighlighted ? 10 : 1)
}
```

**Comment by NordicLight** [comment]
Thank you working great!
