### ISSUE TITLE
 Calling chart.removeNode() then chart.addNode() causes data array to have missing data

### ISSUE THREAD

**Issue by yizongk** [bumbeishvili/org-chart#91]
**Describe the bug**
Let say you have a data array of size 10. When I called chart.addNode() 3 times, it does okay, and the data array is now of size 13. The newly added nodes are in the data array and can be accessed.

But then, at this point, if I call chart.removeNode() once (Or an arbitrary number of times), the size of the data array stays at 13. You would expect the data array to shrink, but the org chart visual seems to be working fine, so this issue may not be a big issue/bug yet. Right now, all previously added/removed/existing nodes can still be access in the data array.

Now at this point, you can try to call chart.addNode() as many times as you want, the data array will stay at size 13, and this is the bug I want to report. The org chart still seem to work fine because the new nodes are showing up in the visual. But in the data array, those newly created nodes are missing. We cannot access any of the new nodes (created after calling chart.removeNode()) in the data array.

**To Reproduce**
1. Go to https://stackblitz.com/edit/web-platform-2fwn8t?file=index.html
           The codes in question are at and after line 159
2. Open up console log by pressing ctrl+shift+i.
           It will output the necessary messages to you.
3. Click on any node to select them. And then click on the 'add node' button on the bottom left of the screen.
           This will add a node to under the current selected node.
4. Click and select the new node you just created. Now click on 'bug: check if current selected node is in array' button to check that you can access the newly created node in the data array.
           Everything is okay so far.
5. Now click on any node to select it. Then click on 'remove' button.
           This will remove the selected node and any of its children from the org chart visual. Everything SEEMS to be okay so far.
6. Now click on any node to select it. Then click on 'add node' button.
           This will create a new node under your current selected node.
7. Click on that newly created node, and click on 'bug: check if current selected node is in array' button.
           This is the bug, it will not find it in the array.

**Expected behavior**
After step 7, you should be able to access that newly created node and its properties.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Edge
 - Version: Version 94.0.992.31 (Official build) (64-bit)

---

Also, there is a **new** dev version in progress - check the roadmap here - https://github.com/bumbeishvili/d3-organization-chart/issues/14

**Comment by bumbeishvili** [comment]
The issue, in this case, is that `addNode` pushes the new node in the existing data array, while `removeNode` creates a new array.

Here are relevant code pieces

**Add**

https://github.com/bumbeishvili/org-chart/blob/a8c47bbdb2f41fb01338cc33e26b6da5d0185d53/src/d3-org-chart.js#L502

**Remove** 

https://github.com/bumbeishvili/org-chart/blob/a8c47bbdb2f41fb01338cc33e26b6da5d0185d53/src/d3-org-chart.js#L528


At this point, I am not exactly sure if it's a good idea to edit the passed data array in place or not (maybe it is, maybe it is not, I haven't given much thought to it). 

Although I agree that there is inconsistency which should be addressed. 

In the meantime, you can use 

`chart.data()` to get the currently used data after `removeNode` is invoked and synchronize it with the outside world

Thanks for the detailed explanation of the issue, appreciated

**Comment by yizongk** [comment]
Thanks, using chart.data() works so well. I didn't know about chart.data(), so I was using the original data array, haha.

I switched my code to reference chart.data() instead of the original data array in all places in my code.

**Comment by bumbeishvili** [comment]
Yes, basically every property under this object

https://github.com/bumbeishvili/org-chart/blob/a8c47bbdb2f41fb01338cc33e26b6da5d0185d53/src/d3-org-chart.js#L24

Has same-named getter and setter exposed 

`chart.data(data)` - Sets data

`chart.data()` - Gets data
