### ISSUE TITLE
Unhandled Runtime Error: linkUpdate.transition is not a function

### ISSUE THREAD

**Issue by timfuhrmann** [bumbeishvili/org-chart#92]
I'm currently trying to implement an org chart within my Next.js project. 

```
export const Chart: React.FC<OrganizationProps> = ({ organization }) => {
    const containerRef = useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        if (!containerRef.current) {
            return;
        }

        new OrgChart().container(containerRef.current).data(organization).render();
    }, []);

    return <ChartContainer ref={containerRef} />;
};
```

Where `organization` is an array of objects of type:
```
interface HierarchyLevel {
        id: string;
        parentId: string;
        designation: string;
        level: string;
}
```

Somehow I get the following unhandled runtime error: `linkUpdate.transition is not a function`.

How so? I don't see where I could've done something wrong.

**Comment by mheppner** [comment]
@timfuhrmann how were you able to solve this?

**Comment by KennBro** [comment]
I don't use parcel, and I receive the same error

**Comment by bry221996** [comment]
Any update on this ? How did you fixed it ?
