### ISSUE TITLE
Support for tree structured data on the roadmap?

### ISSUE THREAD

**Issue by DarrenXu94** [bumbeishvili/org-chart#93]
Were there any plans to allow data to be parsed in as a tree structure already? [Using the hierarchy structure?](https://observablehq.com/@d3/d3-hierarchy )

Eg If I wanted to use a structure like this would I have to flatten it manually first?
```javascript
var treeData = {
  name: 'Top Level',
  children: [
    {
      name: 'Level 2: A',
      children: [{ name: 'Son of A' }, { name: 'Daughter of A' }],
    },
    { name: 'Level 2: B' },
  ],
};
```

**Comment by bumbeishvili** [comment]
No, there weren't any plans. You can flatten that structure and pass the flattened data though

<img width="1186" alt="Screenshot 2021-10-09 at 10 46 55" src="https://user-images.githubusercontent.com/6873202/136647373-672c2ec7-f390-4e5c-b066-2f564232228c.png">



**Code** 

```javascript
d3.hierarchy({
  name: "root",
  children: [
    {name: "child #1"},
    {
      name: "child #2",
      children: [
        {name: "grandchild #1"},
        {name: "grandchild #2"},
        {name: "grandchild #3"}
      ]
    }
  ]
})
.descendants()
.map(d=>Object.assign(d,{id:d.data.name}))
.map(d=> Object.assign(d.data,{id:d.id, parentId:d.parent?.id}))
```
