### ISSUE TITLE
Example of removing connection

### ISSUE THREAD

**Issue by DarrenXu94** [bumbeishvili/org-chart#95]
Hi there, great library btw!

I was wondering if you had an example of how to remove a connection? I'm doing this in my code but it seems hacky and doesn't have the animate out effect.

```
const wrap = d3.select(".connections-wrapper");
wrap.selectAll("path").remove();
```

I've noticed this line in the source but am not sure how to use it

```
 const connExit = connectionsSel
            .exit()
            .transition()
            .duration(attrs.duration)
            .attr('opacity', 0)
            .remove();
```

**Comment by DarrenXu94** [comment]
Thanks! There's no exit animation/transition but that's fine.

I found a bug which was causing this not to work before. I had added 
```
  .connectionsUpdate(function (d, i, arr) {
          d3.select(this)
            .attr("class", "transition")
```

but turns out adding a class doesn't work well with the paths

**Comment by bumbeishvili** [comment]
```javascript
.attr("class", "transition")
```

This sets `transition` class but removes other classes which were already in place. it could cause  strange errors to happen, because previous classes may be used somewhere in the code.

I'd suggest using `classed` method in those cases
```javascript
  .connectionsUpdate(function (d, i, arr) {
          d3.select(this)
            .classed("transition", true)

```
