### ISSUE TITLE
Error: Should not import the named export 'version' (imported as 'version') 

### ISSUE THREAD

**Issue by joelcoxokc** [bumbeishvili/org-chart#96]
**Describe the bug**
I am having an issue running the d3-org-chart. 
I am using Angular v12
Typescript 4.2.4
d3 "7",
d3-org-chart "2",

When I try to compile I get the following Error

`./node_modules/d3-flextree/src/flextree.js:172:19-26 - Error: Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)`

**Comment by bumbeishvili** [comment]
@joelcoxokc this should be fixed now according to thread in #77 , so I am closing it
