### ISSUE TITLE
NodeContent as HTML element instead of HTML as string

### ISSUE THREAD

**Issue by angelfraga** [bumbeishvili/org-chart#97]
First of all thanks , it looks great 👍 

**Describe the solution you'd like**

As a developer using org-chart library, I would like to append HTML elements to each node `DIV` element instead of pure HTML as string.

That is very helpful when working with frameworks such as Angular, React, Vue, Svelte ...  which components can be attached to the chart nodes without missing all the power of the framework.

**Describe alternatives you've considered**

I found a workaround that allows me to attach an element to each Node `DIV` Element, it looks like that:
(angular context)

```
      .nodeContent((node, i, arr, attrs) => {
        const component = factory.create(this.injector);
        component.instance.hierarchy = node.data.data;
        component.changeDetectorRef.detectChanges();
        const content = component.location.nativeElement;
        /**
         * NOTE: We can not attach the angular component to the DOM yet.
         * so we return node content as empty string ''
         * After the renderization, we attach every component instance
         * to its own Node HTMLDivElement
         */
        setTimeout(() => {
          const nodeHTMLElement = (arr[i] as HTMLDivElement);
          nodeHTMLElement.innerHTML = '';
          nodeHTMLElement.appendChild(content);
        });
        return '';
      })
```
**Additional context**
It would be great to have an alternative method which append framework agnostic HTML Elements. 

---

**Comment by HCyberViper** [comment]
Hello @angelfraga ,
I was wondering if you had a simple angular example in stackblitz where your snippets of code commented above works? I am trying to make each node a component as well.

**Comment by gxferreira** [comment]
Hello @bumbeishvili and @angelfraga!

First of all, thanks for the tips!

I followed them to create an org chart with nodes as angular components.
However, it seems that `nodeUpdate` runs every time even just collapsing children from a node.

That way, the org chart floods the runtime with angular components that represent the same nodes.

Do you guys have any idea of how to optimize this behavior?

**Comment by bumbeishvili** [comment]
> However, it seems that nodeUpdate runs every time even just collapsing children from a node

 That's true and I don't see this behaviour changing in the near future, so I don't know how to optimise it

**Comment by marcellino-ornelas** [comment]
Want to use more react and less d3? check out this stackblitz link

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-2chluf?file=index.js,OrgChart.js

Instead of striping everything react away in the chart (`React.renderToString`) we were able to use this org chart but keep all react functionality by drawing the graph and linking react components to it by using [`createPortal`](https://reactjs.org/docs/portals.html)

Now you get the benefits of using this library to draw the graph but get all the benefits of react. We've been using this route for about 2 months now and have not run into any issues. We do use the basics of this graph (just draw the graph and thats it) although we do plan to implement some other functionality this library provides (centering, expanding, etc)

**Comment by alkanna** [comment]
Hey @marcellino-ornelas, it looks like upon expanding or collapsing a node in your example, the nodes are now empty. Did you ever come up with a solution ?

**Comment by marcellino-ornelas** [comment]
@alkanna I personally haven't tried expanding or collapsing the nodes yet. The farther I went with this was being able to add new nodes.

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-hdgvst?file=index.js,OrgChart.js,Counter.tsx

I worked on this in another issue and wrote some of my findings over there
https://github.com/bumbeishvili/org-chart/issues/131#issuecomment-1458870346

**Comment by marcellino-ornelas** [comment]
@alkanna I tried this out tonight but didn't go so well. 


I got react updating the data to add a `_expanded` property on the data.

initially, if you set `_expanded: true` on all the data everything will be expanded and vise versa with`false`

**Comment by marcellino-ornelas** [comment]
@alkanna got nodes to collapse and update but the solution is a little hacky in my opinion 🤷🏽‍♂️ 

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-wmkv7k?file=index.js,OrgChart.js,Counter.tsx

**Comment by bumbeishvili** [comment]
I've tried library to be as hackable as possible 🤷🏽‍♂️
